### ISSUE TITLE
HTTP Proxy

### ISSUE THREAD

**Issue by troyanskiy** [ionic-team/cordova-plugin-ionic-webview#1]
It's not a bug, it's an enhancement.
To avoid that CORS requests it would be nice if the local web server could redirect some requests to another outside device (network) server, exact same way as we have on ionic proxy config when we do `ionic serve`.
I think that will be a really great enhancement of the plugin.
For example, we can specify in the config.xml some proxy tag which will be used by the server to redirect the requests.
`<proxy src="/api" dst="https://api.my-server.com"/>`
Which means that all request to `http://localhost:8080/api` will be redirected to `https://api.my-server.com`.

Since the requests are done on `http` (from webview point of view) (not `https`) the proxy server also should check `set-cookie` headers from the response in order to remove `Secure` parameter to make the cookies work.

I'm not an ObjectiveC programmer, so I can't really help on that (but I know swift as a beginner).

Anyway, I'm open to discussing the solution to implement proxying on the device.

**Comment by manucorporat** [comment]
why not to use the http Cordova repo?

**Comment by troyanskiy** [comment]
@manucorporat Sorry, I did not get about what are you talking.

**Comment by troyanskiy** [comment]
@manucorporat 
If you are talking about `https://github.com/silkimen/cordova-plugin-advanced-http` than it's not a problem to use that on the app.
But in case of app which is used as an app (on device) and a website (in browser) then need to implement something like (which is the case now for all my apps)
```ts
if (isApp) {
// make a call with HTTP native plugin
} else {
// make a call with angular Http
}
```

And it's not really convenient.

**Comment by manucorporat** [comment]
doesn't your idea have the same problem?

**Comment by troyanskiy** [comment]
Nope.
Since we are calling `/api/...` (by angular http) on the app it will call `http://localhost:8080/api/...` (coz `index.html` is loaded from `http://localhost:8080/index.html`) and on the web it will call `http://my-server.com/api` (coz `index.html` is loaded from `http://my-server.com/index.html`) .
Then on the server, it's a role of the web server to forward requests `/api` to the back end.

**Comment by manucorporat** [comment]
It is very unlikely this will be ever be part of this repo, since it is not related with WK stuff or the app correctly, but a specific limitation of not implementing CORS.

I would suggest to look or create a new cordova plugin that only implements the proxy feature. I would be happy to add it to this section in the docs: https://ionicframework.com/docs/wkwebview/#i-cant-implement-cors
