### ISSUE TITLE
Strange issue on iPad 2 (iOS 9.3.5)

### ISSUE THREAD

**Issue by mifkys** [ionic-team/cordova-plugin-ionic-webview#10]
I recorder strange Ionic WebView's behavior (red blinking) on physical device iPad 2. Didn't see anything like this early: https://youtu.be/7mKPy48ITNo

**Comment by manucorporat** [comment]
Can you recreate this problem in a repo you can share?

**Comment by mifkys** [comment]
I found that red blink appears only when opened Safari Web Inspector. If I close it blinks has gone. It reproduce on device and emulator (checked on ios 9, 10).

**Comment by tobiasmuecksch** [comment]
That's perfectly normal for the web inspector. It highlights the elements on your device, that you're inspecting on the Mac. Please close this issue.

**Comment by mifkys** [comment]
I didn't inspecting element. I am tapping on it on device. This behavior is not exists on standard WebView.

**Comment by 93sky** [comment]
Hi. I'm experiencing the same behavior, with an iPhone X. It only happens when the developer is open, but I'm not inspecting. In my case it happens when you focus on the entry, and every time I insert (or delete) a character.

**Comment by jcesarmobile** [comment]
I don't think this is really related to the plugin and won't affect user apps as it only happens when using the web inspector. Closing
