### ISSUE TITLE
Cannot access local files on iOS 11.3

### ISSUE THREAD

**Issue by vevisystems** [ionic-team/cordova-plugin-ionic-webview#100]
On iOS 11.3, local files such as those saved from the camera cannot be accessed. For instance, a <img> tag with a local file as src does not show anything (just a blank box). Inspecting the app with Safari developer tools shows the local server is returning a 404 code.

It works ok on iOS 11.2 and below. We are using version 1.2.1, but we have also tested with v1.1.19 and v1.1.16, with the same result.

**Comment by sagrawal31** [comment]
Was this really an issue?
