### ISSUE TITLE
ERROR: ionic start helloWorld blank

### ISSUE THREAD

**Issue by TrevorBedsaul** [ionic-team/cordova-plugin-ionic-webview#107]
I downloaded npm, and then installed ionic cordova using npm. Now, when I try to start a document, I run into this issue. Please explain what I can do to fix this. I have both node and node-sass updated to their latest versions. However, as we can see in this, it mentions node-sass 4.7.2, even though node-sass is actually at 4.9.0 on my computer (I have checked and confirmed this). If it helps at all, I am using git bash on a windows computer to do all of this.

$ ionic start helloWorld blank

? The directory helloWorld contains file(s) that could conflict. Would you like
√ Creating directory .\helloWorld - done!
√ Downloading and extracting blank starter - done!

? Would you like to integrate your new app with Cordova to target native iOS an
√ Personalizing ionic.config.json and package.json - done!
> ionic integrations enable cordova --quiet
√ Downloading integration cordova - done!
√ Copying integrations files to project - done!
[OK] Added cordova integration!

Installing dependencies may take several minutes.

  *   IONIC  DEVAPP  *

 Speed up development with the Ionic DevApp, our fast, on-device testing mobile app

  -     Test on iOS and Android without Native SDKs
  -     LiveReload for instant style and JS updates

 ️-->    Install DevApp: https://bit.ly/ionic-dev-app    <--

> npm i
× Running command - failed!
[ERROR] An error occurred while running npm i (exit code 1):

        > node-sass@4.7.2 install C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\node-sass
        > node scripts/install.js

        Downloading binary from https://github.com/sass/node-sass/releases/download/v4.7.2/win32-x64-64_binding.node
        Cannot download "https://github.com/sass/node-sass/releases/download/v4.7.2/win32-x64-64_binding.node":

        HTTP error 404 Not Found

        Hint: If github.com is not accessible in your location
               try setting a proxy via HTTP_PROXY, e.g.

               export HTTP_PROXY=http://example.com:1234

        or configure npm proxy via

               npm config set proxy http://example.com:8080

        > uglifyjs-webpack-plugin@0.4.6 postinstall C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\uglifyjs-webpack-plugin
        > node lib/post_install.js

        > node-sass@4.7.2 postinstall C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\node-sass
        > node scripts/build.js

        Building: C:\Program Files\nodejs\node.exe C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
        gyp info it worked if it ends with ok
        gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
        gyp verb cli   'C:\\Users\\student\\AppData\\Roaming\\npm\\helloWorld\\node_modules\\node-gyp\\bin\\node-gyp.js',
        gyp verb cli   'rebuild',
        gyp verb cli   '--verbose',
        gyp verb cli   '--libsass_ext=',
        gyp verb cli   '--libsass_cflags=',
        gyp verb cli   '--libsass_ldflags=',
        gyp verb cli   '--libsass_library=' ]
        gyp info using node-gyp@3.6.2
        gyp info using node@10.1.0 | win32 | x64
        gyp verb command rebuild []
        gyp verb command clean []
        gyp verb clean removing "build" directory
        gyp verb command configure []
        gyp verb check python checking for Python executable "python2" in the PATH
        gyp verb `which` failed Error: not found: python2
        gyp verb `which` failed     at getNotFoundError (C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\which\which.js:13:12)
        gyp verb `which` failed     at F (C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\which\which.js:68:19)
        gyp verb `which` failed     at E (C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\which\which.js:80:29)
        gyp verb `which` failed     at C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\which\which.js:89:16
        gyp verb `which` failed     at C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\isexe\index.js:42:5
        gyp verb `which` failed     at C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\isexe\windows.js:36:5
        gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:165:21)
        gyp verb `which` failed  python2 { Error: not found: python2
        gyp verb `which` failed     at getNotFoundError (C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\which\which.js:13:12)
        gyp verb `which` failed     at F (C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\which\which.js:68:19)
        gyp verb `which` failed     at E (C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\which\which.js:80:29)
        gyp verb `which` failed     at C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\which\which.js:89:16
        gyp verb `which` failed     at C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\isexe\index.js:42:5
        gyp verb `which` failed     at C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\isexe\windows.js:36:5
        gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:165:21)
        gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (C:\\Users\\student\\AppData\\Roaming\\npm\\helloWorld\\node_modules\\which\\which.js:13:12)\n    at F (C:\\Users\\student\\AppData\\Roaming\\npm\\helloWorld\\node_modules\\which\\which.js:68:19)\n    at E (C:\\Users\\student\\AppData\\Roaming\\npm\\helloWorld\\node_modules\\which\\which.js:80:29)\n    at C:\\Users\\student\\AppData\\Roaming\\npm\\helloWorld\\node_modules\\which\\which.js:89:16\n    at C:\\Users\\student\\AppData\\Roaming\\npm\\helloWorld\\node_modules\\isexe\\index.js:42:5\n    at C:\\Users\\student\\AppData\\Roaming\\npm\\helloWorld\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:165:21)',
        gyp verb `which` failed   code: 'ENOENT' }
        gyp verb check python checking for Python executable "python" in the PATH
        gyp verb `which` failed Error: not found: python
        gyp verb `which` failed     at getNotFoundError (C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\which\which.js:13:12)
        gyp verb `which` failed     at F (C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\which\which.js:68:19)
        gyp verb `which` failed     at E (C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\which\which.js:80:29)
        gyp verb `which` failed     at C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\which\which.js:89:16
        gyp verb `which` failed     at C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\isexe\index.js:42:5
        gyp verb `which` failed     at C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\isexe\windows.js:36:5
        gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:165:21)
        gyp verb `which` failed  python { Error: not found: python
        gyp verb `which` failed     at getNotFoundError (C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\which\which.js:13:12)
        gyp verb `which` failed     at F (C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\which\which.js:68:19)
        gyp verb `which` failed     at E (C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\which\which.js:80:29)
        gyp verb `which` failed     at C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\which\which.js:89:16
        gyp verb `which` failed     at C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\isexe\index.js:42:5
        gyp verb `which` failed     at C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\isexe\windows.js:36:5
        gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:165:21)
        gyp verb `which` failed   stack: 'Error: not found: python\n    at getNotFoundError (C:\\Users\\student\\AppData\\Roaming\\npm\\helloWorld\\node_modules\\which\\which.js:13:12)\n    at F (C:\\Users\\student\\AppData\\Roaming\\npm\\helloWorld\\node_modules\\which\\which.js:68:19)\n    at E (C:\\Users\\student\\AppData\\Roaming\\npm\\helloWorld\\node_modules\\which\\which.js:80:29)\n    at C:\\Users\\student\\AppData\\Roaming\\npm\\helloWorld\\node_modules\\which\\which.js:89:16\n    at C:\\Users\\student\\AppData\\Roaming\\npm\\helloWorld\\node_modules\\isexe\\index.js:42:5\n    at C:\\Users\\student\\AppData\\Roaming\\npm\\helloWorld\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:165:21)',
        gyp verb `which` failed   code: 'ENOENT' }
        gyp verb could not find "python". checking python launcher
        gyp verb could not find "python". guessing location
        gyp verb ensuring that file exists: C:\Python27\python.exe
        gyp ERR! configure error
        gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
        gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\node-gyp\lib\configure.js:483:19)
        gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\node-gyp\lib\configure.js:508:16)
        gyp ERR! stack     at C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\graceful-fs\polyfills.js:284:29
        gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:165:21)
        gyp ERR! System Windows_NT 10.0.16299
        gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\student\\AppData\\Roaming\\npm\\helloWorld\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
        gyp ERR! cwd C:\Users\student\AppData\Roaming\npm\helloWorld\node_modules\node-sass
        gyp ERR! node -v v10.1.0
        gyp ERR! node-gyp -v v3.6.2
        gyp ERR! not ok
        Build failed with error code: 1
        npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
        npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

        npm ERR! code ELIFECYCLE
        npm ERR! errno 1
        npm ERR! node-sass@4.7.2 postinstall: `node scripts/build.js`
        npm ERR! Exit status 1
        npm ERR!
        npm ERR! Failed at the node-sass@4.7.2 postinstall script.
        npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

        npm ERR! A complete log of this run can be found in:
        npm ERR!     C:\Users\student\AppData\Roaming\npm-cache\_logs\2018-05-22T00_48_23_142Z-debug.log

The most confusing parts of this to me are the python and python2 error lines, as well as the "Unsupported platform for fsevents" line near the end.

**Comment by jcesarmobile** [comment]
I can't reproduce with latest CLI.

Please, try again and if the problem persists, report it on ionic repository as the problem seems to be there, this repository is about the webview plugin
