### ISSUE TITLE
Why  can't we use the file:// URL?

### ISSUE THREAD

**Issue by LvyLiu** [ionic-team/cordova-plugin-ionic-webview#108]
Why should we add <allow-navigation href="http://localhost:8080/*"/>in config.xml or WKWebView may not launch.

**Comment by AnkitMaheshwariIn** [comment]
Why can't we use the file:// URL?

**Comment by Ross-Rawlins** [comment]
is there a solution for this?

**Comment by jcesarmobile** [comment]
This plugin uses a web server because of WKWebView issues, so it's served from `http://` instead of from `file://`.
If you have `file://` urls returned from other plugins you can use `convertFileSrc` function to make them valid `http://` urls
