### ISSUE TITLE
Keep `RELEASENOTES.md` updated

### ISSUE THREAD

**Issue by timbru31** [ionic-team/cordova-plugin-ionic-webview#11]
It would be awesome if you could keep the changelog updated - maybe take a look at https://github.com/conventional-changelog/standard-version for automatic changelog generation?

Thanks in advance guys & girls! 🚀

**Comment by manucorporat** [comment]
Yeah, I had plans to start using the same release scripts we use for the rest of projects at ionic in this one. Thanks for opening an issue.

**Comment by manucorporat** [comment]
@timbru31 first step: same script for publishing than the ionic framework:
```
npm run deploy
```

It will update package.json and sync plugin.xml

**Comment by DanielAccorsi** [comment]
@manucorporat   RELEASENOTES.md remains outdated. 
;)

**Comment by timbru31** [comment]
Seems you guys are keeping the release notes up to date now. Awesome!
