### ISSUE TITLE
Failed to install 'cordova-plugin-ionic-webview': TypeError: Invalid Version: undefined at new SemVer

### ISSUE THREAD

**Issue by jacerider** [ionic-team/cordova-plugin-ionic-webview#12]
When I run

`ionic cordova plugin add cordova-plugin-ionic-webview --save`

I get the following error:

> [ERROR] An error occurred while running cordova plugin add cordova-plugin-ionic-webview --save (exit code 1):
> 
> 
>         Installing "cordova-plugin-ionic-webview" for ios
>         Failed to install 'cordova-plugin-ionic-webview': TypeError: Invalid Version: undefined
>              at new SemVer
>         (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/semver/semver.js:293:11)
>              at Range.test
>         (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/semver/semver.js:1036:15)
>              at Function.satisfies
>         (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/semver/semver.js:1085:16)
>              at checkEngines
>         (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:117:21)
>              at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:315:16
>              at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
>              at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
>              at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
>              at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:557:44
>              at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
>         Error: Invalid Version: undefined

Any idea why I might be getting this?

**Comment by RomanovX** [comment]
Meanwhile various new releases have been published to npm. Are you still getting this error?

**Comment by manucorporat** [comment]
seems like a bug in Cordova
