### ISSUE TITLE
Unused variable allowRemote

### ISSUE THREAD

**Issue by jcesarmobile** [ionic-team/cordova-plugin-ionic-webview#122]
[This](https://github.com/ionic-team/cordova-plugin-ionic-webview/pull/117
) PR added background support for iOS and added a new `WKAllowRemoteConnect` preference.

The preference is stored in an `allowRemote` variable, but the variable is never used.

`BOOL allowRemote = [settings cordovaBoolSettingForKey:@"WKAllowRemoteConnect" defaultValue:NO];`

cc @ghenry22

**Comment by ghenry22** [comment]
@jcesarmobile  Sorry my mistake, I was considering adding a variable to allow remote connections to the webserver as this can be very useful in some scenarios for testing and for enabling something along the lines of whatsapp web type functionality where a some of the app functionality can be made available to a remote browser through a web interface.

I thought I removed all references to this before submitting the PR as I wanted this PR to just be background mode and not include anything else new.

It won't hurt anything immediately but I will submit a PR to remove it and clean this up.

**Comment by jcesarmobile** [comment]
Ok, no problem. I thought you forgot to set the value somewhere.
If you send a PR, also delete it from the changelog

**Comment by ghenry22** [comment]
PR submitted to remove this.

**Comment by jcesarmobile** [comment]
Thanks @ghenry22, merged both PRs
