### ISSUE TITLE
WebView 2.0 Usage error

### ISSUE THREAD

**Issue by tetpsy** [ionic-team/cordova-plugin-ionic-webview#129]
Hi, followed steps to add new WebView 2.0 into component.

**$ ionic cordova plugin add cordova-plugin-ionic-webview**
**$ npm install --save @ionic-native/ionic-webview**

**import { WebView } from '@ionic-native/ionic-webview';**
**constructor(private webview: WebView) { }**
**img = this.webview.convertFileSrc('file:///Users/dan/camera-image-12345.png')**

Gives error:
**Can't resolve all parameters for Page: (?, ?).**

Thanks

**Comment by tetpsy** [comment]
Our app relies heavily on normalizeUrl. Please can you assist so we can setup for the new version.

**Comment by scottmizo** [comment]
Work around:

private win: any = window;

this.win.Ionic.WebView.convertFileSrc();

But you'll run into an error when trying to use the returned url.  See [Issue 133](https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/133)

**Comment by tetpsy** [comment]
Thanks so much for the reply.

i will test it out. 
regarding your workaround, workaround - *serverUrl = @"http://localhost:8080".

Where exactly do i add this change?

Does it mean that i must add an @ before my file path?
http://localhost:8080/Users/dan/camera-image-12345.png?

Thanks

**Comment by scottmizo** [comment]
It’s line 758 in CDVWKWebViewEngine.m of the plugin.

The url / path has to be generated from the window.Ionic.WebView.convertFileSrc

I ended up reverting to the previous version of the plugin due to a few other issues including an issue with playing videos and viewing images through local files.

**Comment by tetpsy** [comment]
Ah ok thanks man.

Yeah we also just reverted to the older version. We wanted to try new version because the new manual Pro features require the latest plugin.

We will just wait until the team solves these issues.

Thanks for your help.

Happy coding.

**Comment by olivermuc** [comment]
I'm seeing the same issues with accessing local files since the upgrade.
In the previous 1x version, a mere "file://" (or not for iOS) would do the trick.

I simply updated to cordova-plugin-ionic-webview v2 and it broke local file access for Android:
I tried both hardcoding the server address and using 
`window.Ionic.WebView.convertFileSrc(filePath);`
both produce the same result in fact, eg:
`http://localhost:8080/_file_/data/user/0/com....some.app/files/assets/e6d1ac1d14b6f15f1124dab9e7488ff8"`

I don't see any security/access related errors but also nothing shows, leaving images broken (on Android).

*On iOS everything works as expected*.

**Comment by tetpsy** [comment]
Yeah man

I'm hoping it gets fixed.

I'm just gonna wait until then.

**Comment by olivermuc** [comment]
I've been trying to troubleshoot this a little bit, frankly though, I don't know what I'm doing. So take the below with a grain of salt and my 2c in good faith.

Debugging this on AndroidStudio shows me a back and fort between:
`WebViewLocalServer.java:: handleLocalRequest()`
and
`AndroidProtocolHandler.java:: openAsset()`

**path** seems to be set to the current image I am referencing, see screenshot A below

In line 246 it attempts to open the asset, but ignores the actual path and passes on **startPath** and **assetPath** being "" empty.

Subsequent processing does not consider the actual asset path at all...

Again, this could all be just fine, but imho -even to my untrained eye- this looks wrong.

SCREENSHOT A
![image](https://user-images.githubusercontent.com/10549895/43459537-18068b5e-94ce-11e8-9033-2e503250bde2.png)

**Comment by olivermuc** [comment]
Well, this warrants an extra post.
I got it.
The above was a shot in the dark but it gave me enough light to see what the real issue is.
I was using hashed URLs as local file names and did not add the original extension back on.
Without the extension the java functions above treat an image like a web page essentially and not a local file reference.
Just slap the original (.png, .jpeg etc) extension back on the storage file name.
All good now!

**Comment by tetpsy** [comment]
I am building on IOS.

I managed to build with **convertFileSrc** however it causes app to terminate in Xcode.

![image](https://user-images.githubusercontent.com/6103599/43467073-3193ccf4-94e1-11e8-9228-5a740c0592d0.png)

and here

![image](https://user-images.githubusercontent.com/6103599/43467095-42ca1fa0-94e1-11e8-8021-a7203d53084f.png)

File url came out correctly as 
**http://localhost:8080/_file_/var/mobile/Containers/Data/Application/1AA83F7E-B30F-4221-890A-414C70A4B92A/Documents/file.pdf**

I tried @scottmizo's workaround, it removed the above error but app still froze with this error

![image](https://user-images.githubusercontent.com/6103599/43467986-34a9bafa-94e3-11e8-9623-7f9d1811d3d6.png)

i am hoping ionic issues a fix.

Thanks

**Comment by olivermuc** [comment]
see this 
https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/133

**Comment by tetpsy** [comment]
Thanks @olivermuc, @scottmizo.
@matejkramny Merge request solved the issue for me.

**https://github.com/ionic-team/cordova-plugin-ionic-webview/pull/135/commits/b18237209b398869ea70d34db6b53a0aee73094f**

**Comment by tetpsy** [comment]
fixed #129

**Comment by bparvizi** [comment]
You can also modify this in getCachedImagePath method:
` // check if file already exists in temp directory
              this.file.resolveLocalFilesystemUrl(tempDirPath + '/' + fileName)
                .then((tempFileEntry: FileEntry) => {
                  // file exists in temp directory
                  // return native path
                  // Replace file with localhost.
                  resolve(fileEntry.nativeURL.replace('file:///', 'http://localhost:8080/'));
                  //resolve(tempFileEntry.nativeURL);
                })`
