### ISSUE TITLE
CORS issues when cordova-plugin-code-push is installed

### ISSUE THREAD

**Issue by coreyroth** [ionic-team/cordova-plugin-ionic-webview#13]
As I was discussing in the Slack channel, I may have stumbled upon an issue with Microsoft's CodePush plugin cordova-plugin-code-push and this one.  Whenever both plugins are installed, the following behavior occurs:

- All network connections fail their Preflight check (CORS)
- i18n fails to load strings out of its resource file

Remove the CodePush plugin and everything works fine.  My end-point is set up to accept requests from http://localhost:8080.   I have managed to get it to work on 2 out of 4 of my apps that hit the same end-point.  However, the other two I haven't had as much luck.  I've tried removing my iOS platform and re-addig it as well.

Ionic info
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.1.1 browser 4.1.0 ios 4.4.0
    Ionic Framework    : ionic-angular 3.7.0

System:

    Android SDK Tools : 25.2.4
    ios-deploy        : 1.9.2 
    Node              : v8.6.0
    npm               : 5.4.2 
    OS                : macOS High Sierra
    Xcode             : Xcode 9.0 Build version 9A235 

Misc:

    backend : legacy

Other plugins installed:
code-push 2.0.1-beta "CodePushAcquisition"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-code-push 1.9.8-beta "CodePush"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-dialogs 1.3.3 "Notification"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-filepath 1.0.2 "FilePath"
cordova-plugin-firebase 0.1.24 "Google Firebase Plugin"
cordova-plugin-geolocation 2.4.0 "Geolocation"
cordova-plugin-inappbrowser 1.5.0 "InAppBrowser"
cordova-plugin-ionic-webview 1.1.14 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 4.0.0 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-whitelist 1.3.0 "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
cordova-sqlite-storage 2.0.0 "Cordova sqlite storage plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-barcodescanner 6.0.8 "BarcodeScanner"

**Comment by yanglongji** [comment]
me too

**Comment by polfernandez** [comment]
same [https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/31](https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/31)

**Comment by crapthings** [comment]
i've tested on new project, its working with code-push.

**Comment by jcesarmobile** [comment]
Looks like Microsoft fixed the problems, closing.
