### ISSUE TITLE
Question about platform requirements with v2.0.0+

### ISSUE THREAD

**Issue by kamilbrk** [ionic-team/cordova-plugin-ionic-webview#131]
Hi,

I'm really looking forward to having the same setup between iOS and Android, now that there's a local web server, html5 mode and simple URIs on both platforms.

That said, you mentioned that cordova-plugin-ionic-webview@2.x requires Android 5+ and iOS 10+ now.

Latest version of GCDWebServer requires iOS 8+ and I don't really have the experience to work out anything else by looking at the source code of @2.x.

Is there a technical reason behind this requirement bump?

Android supports Chromium based WebView since API 19 (4.4+) and, at least in our case, we still need to worry about at least iOS 9 (iPhone 4 era) and Android 4.4 users, which is a bummer.

Cheers!

**Comment by matejkramny** [comment]
I wonder if android requires the webserver at all. Not having it allows usage from android 4.4 phones

**Comment by AsteaDevelopment** [comment]
It says it requires iOS 10 but in the plugin.xml it still says 9.0, shouldn't this have been changed too?

**Comment by jcesarmobile** [comment]
Current README says it requires iOS 11 and it's also updated in plugin.xml
