### ISSUE TITLE
IOS - Video tag with local file not working

### ISSUE THREAD

**Issue by dhaval-patel** [ionic-team/cordova-plugin-ionic-webview#134]
Hi,

I am trying to use local file to in video tag. But somehow it's not woking on ios. Same is working fine on android.

audio and img tags are working just fine with local files.

If I remove this plugin and go with UIWebView, it's working fine. 

###### HTML
```
<video crossorigin="anonymous" playsinline="" type="video/mp4" src="http://localhost:8080/_file_/var/mobile/Containers/Data/Application/EA1F2841-910B-4D1E-A1F2-5C6BAA85A493/Library/NoCloud/resources/1532864905528_163475.mp4" loop=""></video>
```
###### Error in safari console

![screen shot 2018-07-29 at 7 56 08 pm](https://user-images.githubusercontent.com/3369527/43367379-985763ca-9369-11e8-9619-a8f81f1e3c90.png)

This is the only this, which is stopping me to migrate. 

Help is needed urgently, thanks.

**Comment by JRR-OSU** [comment]
I'm experiencing similar issues as well! Hopefully a solution can be implemented soon.

**Comment by dhaval-patel** [comment]
Video tag needs byte range request and I guess current implementation is not supporting it.

Found a quick workaround from https://github.com/swisspol/GCDWebServer/issues/44. Modified **setServerPath** method to following inside **CDVWKWebViewEngine.m**. 

```
-(void)setServerPath:(NSString *) path
{
    self.basePath = path;
    BOOL restart = [self.webServer isRunning];
    if (restart) {
        [self.webServer stop];
    }
//    NSString *serverUrl = self.CDV_LOCAL_SERVER;
    CDVWKWebViewEngine* engine = self;
    
    [self.webServer addGETHandlerForBasePath:@"/" directoryPath:path indexFilename:((CDVViewController *)self.viewController).startPage cacheAge:0 allowRangeRequests:YES];
    [self.webServer addHandlerForMethod:@"GET" pathRegex:@"_file_/" requestClass:GCDWebServerFileRequest.class asyncProcessBlock:^(__kindof GCDWebServerRequest * _Nonnull request, GCDWebServerCompletionBlock  _Nonnull completionBlock) {
        NSString *serverUrl = engine.CDV_LOCAL_SERVER;
        NSString *urlToRemove = [serverUrl stringByAppendingString:@"/_file_"];
        NSString *absUrl = [[[request URL] absoluteString] stringByReplacingOccurrencesOfString:urlToRemove withString:@""];

        NSRange range = [absUrl rangeOfString:@"?"];
        if (range.location != NSNotFound) {
            absUrl = [absUrl substringToIndex:range.location];
        }
        
        if ([absUrl hasSuffix:@".mp4"]) {
            GCDWebServerResponse* response = [GCDWebServerFileResponse responseWithFile: absUrl byteRange:request.byteRange];
            [response setValue:@"bytes" forAdditionalHeader:@"Accept-Ranges"];
            completionBlock(response);
        } else {
            GCDWebServerFileResponse *response = [GCDWebServerFileResponse responseWithFile:absUrl];
            completionBlock(response);
        }
    }];
    if (restart) {
        [self startServer];
    }
}
```

My all video files has .mp4 extension to it was easy for me to identify and differentiate between. Sorry for hard coded mp4 comparison. I needed a quick solution. 

Cheers

**Comment by JRR-OSU** [comment]
@dhaval-patel I love you. Thanks so much for posting this. My issue was with an audio tag element, and hard coding the file extension I need for audio works as well.

**Comment by dhaval-patel** [comment]
Working fine with 2.1.3
