### ISSUE TITLE
2.x on iOS: White-screen with HTTP-Status 404 in Ionic3 App

### ISSUE THREAD

**Issue by wilk-polarny** [ionic-team/cordova-plugin-ionic-webview#138]
Hi,

in order to get rid of workarounds within our Ionic3 cordova (cordova-ios 4.5.5) needed for #33, we have updated the ionic webview plugin to 2.0.2.

After changing our calls to normalizeURL, everything seems to work fine on Android.

On iOS we are not able to launch the app, because after starting the local server, the view cannot navigate to the root page, resulting in a white-screen. Within the JS-Console we only see a 404 Not Found HTTP-status for our index.html, which points to: http://`WKBind`:`WKPort`/`applicationDirectory`/www/index.html

Arent the app pages supposed to be served from the `_file_` prefix too?
Still, serving the pages on Android works...

Note that we are setting WKBind manually to `127.0.0.1`. The URLs correctly point to `127.0.0.1`, but I'm not sure whether the server binds correctly.

Please advise.

**Comment by Sudalaiyandi** [comment]
Hi,
I can also face same issue,Is there any fix for the issue to launch my app from document directory.

**Comment by Davidzhaojb** [comment]
I hava the same problem

**Comment by wilk-polarny** [comment]
This issue is not present in 4.x versions of the plugin - and has been an incompatibility with a third party plugin which has been solved by setting the server root using `setServerBasePath`.
This is related to issue #250
