### ISSUE TITLE
RESOLVE: OFF CORS on cordova-plugin-ionic-webview

### ISSUE THREAD

**Issue by oarsheo** [ionic-team/cordova-plugin-ionic-webview#140]
How to off **CORS** on **cordova-plugin-ionic-webview**?)))
download **cordova-plugin-wkwebview-file-xhr**
open **cordova-plugin-wkwebview-file-xhr/plugin.xml**
and remove row 
`<dependency id="cordova-plugin-wkwebview-engine" />`
next step install plugin from local path 
`cordova plugin add ../../plugins/cordova-plugin-wkwebview-file-xhr --save`

**Comment by bibounet** [comment]
Do not work for me on an ionic 4 application...

```
Ionic:

   ionic (Ionic CLI)  : 4.0.5 (C:\Users\toto\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.11

Cordova:

   cordova (Cordova CLI) : not installed
   Cordova Platforms     : android 7.0.0

System:

   NodeJS : v8.9.4 (C:\Program Files\nodejs\node.exe)
   npm    : 5.6.0
   OS     : Windows 10
```

**Comment by oarsheo** [comment]
maybe you have polyfill who reassigns XMLHttpRequest

**Comment by fakerLinXiao** [comment]
Thank you! It's work for me. 🍻

**Comment by alan-grixti** [comment]
@bibounet I am using the Http plugin too but I am having a hard time when it comes to cookies. Can you set cookies on the HTTP plugin? Used to work in UIWebView but when upgrading to WKWebView all of my cookies are being ignored. I am not setting them through Javascript calls, but through the native HTTP plugin directly.

**Comment by fakerLinXiao** [comment]
`
XMLHttpRequest.timeout cannot be set for synchronous HTTP(S) requests made from the window context.                                   — xhr-polyfill.js:1232
`
`Uncaught (in promise): InvalidAccessError (DOM Exception 15): The object does not support the operation or argument`
There has been no problem all the time, until today there was an error. Occur error on IOS10.3.1,  It's work on iOS11.

**Comment by jcesarmobile** [comment]
closing as this is not an issue
