### ISSUE TITLE
Android 7.0.0+ : Long local video file stuck after first few frames

### ISSUE THREAD

**Issue by dhaval-patel** [ionic-team/cordova-plugin-ionic-webview#141]
Hello,

I have some mp4 stored locally which I am using in video tag. If video file length is small (few seconds), then it is working just fine but if length is long then it stuck after first few frames.

Weird part is, It's working fine on 7.0.0 but not on 7.0.0+. (I have tested on 7.1.1 and 8.0. It freezes after few seconds).

Without this plugin installed, everything works just fine.

#### Ionic Info

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0
    Gulp CLI              : CLI version 3.9.1 Local version 3.9.1

local packages:

    @ionic/app-scripts : 3.1.11
    Cordova Platforms  : android 7.1.1 ios 4.5.5
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2
    ios-sim           : 5.0.4
    Node              : v6.9.1
    npm               : 3.10.8
    OS                : macOS High Sierra
    Xcode             : Xcode 9.4.1 Build version 9F2000

Environment Variables:

    ANDROID_HOME : /usr/local/opt/android-sdk

Misc:

    backend : pro

Help is needed urgently, thanks.

**Comment by ghenry22** [comment]
@dhaval-patel can you try the latest version of the plugin and see if it works now?  I believe this was related to content-length headers not being set by the web server.

Are you seeing the problem on ios as well or only on Android?

**Comment by ronaldborla** [comment]
any updates for this? has this been resolved?

**Comment by jcesarmobile** [comment]
Can you try with this changes? https://github.com/ionic-team/cordova-plugin-ionic-webview/pull/295
