### ISSUE TITLE
WKWebview runs fine in iOS 10, freezes in iOS 9

### ISSUE THREAD

**Issue by zhengjin** [ionic-team/cordova-plugin-ionic-webview#151]
Here is my access-origin and allow-navigation tag
`<access origin="*" />
<allow-navigation href="*" />`
What else do I need to do to make WKWebview work?
my ionic info:
`

- Cordova CLI: 6.3.1
- Gulp version:  CLI version 3.9.1
- Gulp local:   Local version 3.9.1
- Ionic Framework Version: 1.2.4-nightly-1917
- Ionic CLI Version: 2.1.1
- Ionic App Lib Version: 2.1.1
- ios-deploy version: 1.9.2 
- ios-sim version: Not installed
- OS: Mac OS X El Capitan
- Node Version: v9.6.1
- Xcode version: Xcode 9.3 Build version 9Q127n 

`

cordova plugins list:
`

- cordova-media-with-compression 2.1.1 "Media With Compression: Alpha Software Edition"
- cordova-plugin-app-version 0.1.9 "AppVersion"
- cordova-plugin-camera 2.3.1 "Camera"
- cordova-plugin-compat 1.2.0 "Compat"
- cordova-plugin-console 1.0.7 "Console"
- cordova-plugin-device 1.1.6 "Device"
- cordova-plugin-disable-ios11-statusbar 1.0.0 "cordova-plugin-disable-ios11-statusbar"
- cordova-plugin-file 4.3.3 "File"
- cordova-plugin-file-opener2 2.0.19 "File Opener2"
- cordova-plugin-file-transfer 1.6.3 "File Transfer"
- cordova-plugin-inappbrowser 1.7.1 "InAppBrowser"
- cordova-plugin-ionic-webview 2.1.0 "cordova-plugin-ionic-webview"
- cordova-plugin-jcore 1.1.10 "JCore"
- cordova-plugin-migrate-localstorage 0.0.2 "Migrate WebView Data"
- cordova-plugin-network-information 1.3.1 "Network Information"
- cordova-plugin-screen-orientation 2.0.2 "Screen Orientation"
- cordova-plugin-splashscreen 4.0.3 "Splashscreen"
- cordova-plugin-statusbar 2.2.3 "StatusBar"
- cordova-plugin-whitelist 1.3.2 "Whitelist"
- cordova-plugin-x-toast 2.6.0 "Toast"
- ionic-plugin-keyboard 2.2.1 "Keyboard"
- jpush-phonegap-plugin 3.2.11 "JPush"

`

I noticed an error "DOM Exception 18: An attempt was made to break through the security policy of the user agent."

![16_53_53__08_27_2018](https://user-images.githubusercontent.com/1713372/44654786-7ea42a80-aa25-11e8-9572-011dd0c061ca.jpg)

Please help!

**Comment by CarlosAyala** [comment]
Hi,
The version 2+ of this plugin require IOS10+, if you want to run for IOS9 you need to downgrade to version  1.
