### ISSUE TITLE
mediaPlaybackRequiresUserAction not working in iOS 12

### ISSUE THREAD

**Issue by linkito87** [ionic-team/cordova-plugin-ionic-webview#153]
Hi.

I'm trying insert an video with autoplay mode, but in iOS 12 isn't working, appears the play button... With the same code in iOS 11 its working. I think is the mediaPlaybackRequiresUserAction that is depercated.

Anyone knows what can I do it in iOS 12 to autoplay a video without user action?

This is my code:

HTML
`<video autoplay loop src="img/bg-login.mp4" preload="auto" webkit-playsinline playsinline muted></video>`

config.xml
`<preference name="AllowInlineMediaPlayback" value="true" />
<preference name="mediaPlaybackRequiresUserAction" value="false" />`

Thanks and greetings

**Comment by allanpoppe** [comment]
+1, any news?

**Comment by jcesarmobile** [comment]
This is working fine on 3.0.0, closing.

BTW, there is no `mediaPlaybackRequiresUserAction` preference, it just allows it.
