### ISSUE TITLE
Problems uploading file paths generated by convertFileSrc

### ISSUE THREAD

**Issue by kevinswartz** [ionic-team/cordova-plugin-ionic-webview#163]
Hi Guys,
Thanks for all your hard work on this!

I'm working on an issue uploading images after upgrading to version 2 of cordova-plugin-ionic-webview.  This happens when I'm taking new pictures, or loading something from the camera roll.  I've tried with both versions 2.1.1 and 2.1.2.  

I get a path like: http://localhost:8080/_file_/var/mobile/Containers/Data/Application/[...omitted...]/tmp/cdv_photo_003.jpg

This looks right, and if I display this path in an img tag and it's viewable.  

I then try and upload using cordova-plugin-file-transfer, and it gives me an error saying the file is not found.  I'm aware that the file transfer plugin is deprecated in favor of xhr (https://cordova.apache.org/blog/2017/10/18/from-filetransfer-to-xhr2.html), but this used to work ok when I was on version 1.2.1 of the webview plugin, using normalizeUrl().  

Is this no longer supported?  Should I rewrite my upload handling to use xhr?  Thanks!

**Comment by sfaizanh** [comment]
```
let fileURI = "http://localhost:8080/_file_/var/mobile/Containers/Data/Application/Sample/tmp/cdv_photo_003.jpg"
const prefix = `${(window as any).WEBVIEW_SERVER_URL}/_file_`;
if (fileURI.startsWith(prefix)) {
	fileURI = 'file://' + fileURI.substr(prefix.length);
}

```

**Comment by jcesarmobile** [comment]
Use convertFileSrc only when you are going to display the url in the WebView, for uploading use the path returned from Camera plugin, it will have file:// or content:// and should upload fine, but don't use localhost urls as they are only understood by the Ionic WebView.
