### ISSUE TITLE
This class is not key value coding-compliant for the key _requiresUserActionForMediaPlayback

### ISSUE THREAD

**Issue by dfiggtns** [ionic-team/cordova-plugin-ionic-webview#182]
I'm trying to use the xcode emulator, but keep getting this error on startup:

    Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<WKWebViewConfiguration 0x7f9dce800d40> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key _requiresUserActionForMediaPlayback.'

I've tried uninstalling/reinstalling cordova-plugin-ionic-webview and have exhausted all the solutions I can find here on SO, but they have made no difference. 

This is an ionic cordova project, so I can't change any code in xcode, as it will be overwritten the next time I build the project. Any other solutions will be gratefully received.

I'm not sure whether it's related, but when I do an ionic emulate on the command line, I get this error:

    /Users/path-to-project/platforms/ios/build/emulator/project.app/Info.plist file not found.

The problem is that no build folder under the ios one has been created, which is probably why it can't find anything there. I think I've tracked the problem to the following messages farther up the output:

    CONFIGURATION_BUILD_DIR = /Users/path-to-project/platforms/ios/build/emulator
    SHARED_PRECOMPS_DIR = /Users/path-to-project/platforms/ios/build/sharedpch

However, I don't know where these configs are set. Does anyone know where ionic gets these configs from?

One question comes to mind though: If CONFIGURATION_BUILD_DIR is set to this location, why isn't the build dir created here?

**Comment by jcesarmobile** [comment]
I can't reproduce.
Make sure you are using Xcode 9 or newer.

**Comment by tallcoder** [comment]
I keep running into the same error when trying to run on emulator: [<WKWebViewConfiguration 0x7fedc7f09500> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key _requiresUserActionForMediaPlayback.

But, I will say this didn't start until I added the "Background Mode" cordova plugin, so I'm leaning towards that being an issue.
