### ISSUE TITLE
Images without file extensions are loaded as text/html content type

### ISSUE THREAD

**Issue by lincolnthree** [ionic-team/cordova-plugin-ionic-webview#183]
Version of plugin: 2.1.4
Android version 9
Android chrome version 69.0.3497.100
-------

When loading images that do not have a file extension, they are served as text/html which breaks the browser (`img` tags, etc.) This causes images to be displayed as "missing" or blank, and the placeholder broken image link icon appears where the image should be.

This used to work fine when images were served from file://, but no longer with the 2.0 update using the http://localhost:8080/_file_, approach. I'm not sure if this is a problem with the browser or the built-in server.

Example URL that worked with 1.2.1/x: `file:///data/user/0/com.maritlabs.topdecked.mtg/cache/image-loader-cache/551799067`

But in 2.0 this breaks...

**For example, an URL such as:** `http://localhost:8080/data/user/0/com.maritlabs.topdecked.mtg/cache/image-loader-cache/551799067` (file is correctly named/addressed)

Displays a broken link with this plugin installed, it displays fine

**However the following URL displays fine** when the image extension is added to the url (assuming the actual file on disk is renamed as well): 
`http://localhost:8080/data/user/0/com.maritlabs.topdecked.mtg/cache/image-loader-cache/551799067.png` (file extension has been added to both file and address)

This seems like a problem with file-type detection on the server/browser, but I'm not actually sure how this is *supposed* to behave.

**Comment by graemeenglish** [comment]
I'm also running into this issue, anyone got a work around?

**Comment by kbala** [comment]
@graemeenglish yes, we have to allow local files as well. 
The same not working in iOS as well.

**Comment by kbala** [comment]
@manucorporat this web-view doesn't allow image file without file extension. some of the CDN returns image files without file extension, merely filename. for example, `http://graph.facebook.com/{user-id}/picture` 

Also we used to cache the downloaded file in the same name, and loading cached file(no extension) into img tag is not working.

Any fix?

Thanks

**Comment by lincolnthree** [comment]
Woohoo! I'll check it out and verify as soon as possible. Thank you!

**Comment by xinfengmich** [comment]
I tried version 3.0.0.  Now image-loader-cache is not loading on both iOS and Android. (Version 2.3.1 works on iOS but not Android).  Is there any additional config regarding CORS I need add? 
 
Errors from Android as below: 
1 Failed to load resource: the server responded with a status of 504 ()
/#/tabs/home/home:1 Access to XMLHttpRequest at 'https://api.ionicjs.com/monitoring/7dd2fed1/u' from origin 'http://localhost' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
... ... 
Common.js:334 Not allowed to load local resource: file:///data/user/0/edu.umich.mobile.MichTDev/cache/image-loader-cache/1328641875

**Comment by jcesarmobile** [comment]
Yeah, file urls won't work (they weren't working on 2.x neither), you have to use window.Ionic.WebView.convertFileSrc() function to convert the file url to a valid url.
