### ISSUE TITLE
[Android] Ionic Native stops working after upgrading to WKWebView

### ISSUE THREAD

**Issue by Vivek-abstract** [ionic-team/cordova-plugin-ionic-webview#184]
When I upgrade my app to WKWebView, the native plugins (camera, geolocation) stop working on Android. They work fine on iOS though. I don't know what is causing this. I tried creating a new app with WKWebView preinstalled and native plugins work fine there.

This is my first issue so I don't know what info I have to submit.
Here's my ionic info:
```

Ionic:

   ionic (Ionic CLI)  : 4.1.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.5.3
   @ionic/app-scripts : 2.0.2

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0
   Cordova Plugins       : no whitelisted plugins (5 plugins total)

System:

   Android SDK Tools : 26.1.1 (/home/samsep10l/Android/Sdk)
   NodeJS            : v8.10.0 (/usr/bin/node)
   npm               : 6.3.0
   OS                : Linux 4.15
```

**Comment by mstephano** [comment]
I also have issue with native plugins using the camera on Android (using Ionic DevApp) from a new project created today (by following the [tutorial](https://beta.ionicframework.com/docs/developer-resources/guides/first-app-v4/intro/)). Same project is fine on iOS using Ionic DevApp. Here is my ionic info:

```
Ionic:

   ionic (Ionic CLI)             : 4.6.0 (C:\Users\Steph\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.0
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, ios 4.5.5
   Cordova Plugins       : not available

System:

   NodeJS : v10.13.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

When I tried platform.platforms() on any of my Android device, I don't have the 'cordova' string, but it does show on my iOS devices. Can this be an hint to resolve the issue?

**Comment by mstephano** [comment]
Hi Vivek,

Thank you for your hint. I managed to test it directly via an apk and 'cordova' is returned properly so the camera is working fine now. I guess I will debug in Ionic DevApp only with iOS assuming everything is fine with Android until I build and test via apk.

Thanks again for your help!

**Comment by jcesarmobile** [comment]
I can't reproduce, Ionic Native is working fine on my apps if I build them or use live reload (`ionic cordova run android -l`)

DevApp is probably out of date, so some things might now work there

**Comment by mstephano** [comment]
what version of DevApp on Android do you have?

**Comment by jcesarmobile** [comment]
No, I mean the DevApp is out of date, not that the version you use is out of date.
I didn’t try on DevApp, but if it doesn’t work there then it’s a DevApp bug, not a webview plugin bug
