### ISSUE TITLE
Upgrading from 1.x to 2.x loses localStorage data on Android

### ISSUE THREAD

**Issue by malwatte** [ionic-team/cordova-plugin-ionic-webview#185]
I use local storage for data caching and SQLite for persistent data.

Issue is local storage data not moved when upgraded from 1.x to 2.x

Please help me to solve this.

**Comment by masimplo** [comment]
This is probably related to #181

**Comment by malwatte** [comment]
Yeah. Similar.

**Comment by jcesarmobile** [comment]
Yeah, it's the same, closing this one in favour of the other one
