### ISSUE TITLE
Android 4.4.4 not working 

### ISSUE THREAD

**Issue by deniscesar** [ionic-team/cordova-plugin-ionic-webview#188]
When running my app on android device 4.4.4 I get the following error

``` 
The key "viewport-fit" is not recognized and ignored. localhost/:9
Uncaught TypeError: Property '__zone_symbol__then' of object [object Promise] is not a function zone.js:240
Uncaught TypeError: Object [object Array] has no method 'fill' chunk-892e1642.js:190
```
Zone.js 0.8.27 promises to fix

If anyone has something that can help

**Comment by MrWeezle** [comment]
see https://github.com/angular/zone.js/issues/1078#issuecomment-401247740

**Comment by deniscesar** [comment]
I am waiting for the new version of zone.js

**Comment by jcesarmobile** [comment]
Closing as it's a bug in zone.js
