### ISSUE TITLE
deviceready event never fired with cordova --browserify

### ISSUE THREAD

**Issue by nicolashenry** [ionic-team/cordova-plugin-ionic-webview#19]
Using cordova `--browserify` [command option](https://cordova.apache.org/docs/en/latest/reference/cordova-cli/) with this plugin, the `deviceready` event is never fired.
For example :
```bash
cordova --browserify run ios
```

**Comment by lovelyelfpop** [comment]
I have the same problem, and it spent me a lot of time to figure it out

**Comment by nicolashenry** [comment]
Probably linked to https://issues.apache.org/jira/browse/CB-11311

**Comment by nicolashenry** [comment]
This option does not exist anymore, I close this.
