### ISSUE TITLE
Different apps share codes on iOS

### ISSUE THREAD

**Issue by stevesum** [ionic-team/cordova-plugin-ionic-webview#190]
We discovered if you have two apps what use the cordova-plugin-ionic-webview@2.1.4 then the javascript codes could messed up.
Seems if the wkwebview in the two different app share their cache and the app uses the codes from the other app's cache.

##Steps to reproduce
- Start your FIRST application and put into the background
- Start your SECOND application and you will see the app will load the code of the FIRST application

A small video from the problem available here:
[video example](https://drive.google.com/open?id=19h6P37DOfVByA1m7bVjUQ2D769JDlj-D)

##App info
- cordova CLI (8.1.2)
- cordova-ios (4.5.5)
- cordova-plugin-ionic-webview (2.1.4)
- Sencha ExtJS (6.5.2)

##System info
- iPhone 6s
- iOS 12.0.1

**Comment by mlynch** [comment]
This was resolved in 2.2.0. Make sure to update
