### ISSUE TITLE
Crash in version 2.2 when embedded in native application.

### ISSUE THREAD

**Issue by nrikiji** [ionic-team/cordova-plugin-ionic-webview#192]
I am using ionic on some screens of native application.
I implemented it like this.

1. open
```
let viewController = CordovaViewController()
viewController.view.backgroundColor = UIColor.white
otherViewontroller?.present(viewController, animated: true, completion: nil)
```
2. close
Plugin for closing modal
```
import Foundation

@objc(Close) class Dismiss : CDVPlugin {
    func main(_ command: CDVInvokedUrlCommand) {
        self.viewController.dismiss(animated: true, completion: nil)
    }
}
```

This plugin version 2.2 fixes the application to crash.
The first time you start ionic's viewcontroller it will succeed.

https://github.com/ionic-team/cordova-plugin-ionic-webview/commit/2b9e22a1251ffd10bb5b22d74333212733767ba0#diff-7044543564ea722137708c081ff83c04R863

An error occurs when activating ionic again after closing once.
Because "weakSelf" is nil.
If you have a solution please let me know.

help me...
thanks

**Comment by nrikiji** [comment]
There is no excuse, often.
I am trying to solve this problem.

However, since I want to follow the upgrade of this plug-in, I do not want to change the plug-in.

```
func main(_ command: CDVInvokedUrlCommand) {
    self.viewController.dismiss(animated: true, completion: nil)
}
```

Currently, I ended CordovaViewController like this, but I think that this is the cause
At this time, if we can explicitly terminate the web server, we think that this problem will be solved...
Is there a way to explicitly stop the web server?

I would like to try it.
help me.

**Comment by jcesarmobile** [comment]
The web server is gone on 3.0.0, so this should be fixed.
