### ISSUE TITLE
Ionic WKWebview doesnt load start page when the path of viewController.startPage is set as absolute

### ISSUE THREAD

**Issue by vittalpai** [ionic-team/cordova-plugin-ionic-webview#195]
Ionic WKWebview doesn't load start page when the path of `viewController.startPage` is set as absolute. However it works fine if relative path is set.

This API used to work till `1.2.1` version of WKWebview Plugin and broken afterwards.

Example : 

- Below appdelegate works fine if the startpage value is relative :

```
@implementation AppDelegate
    
- (BOOL)application:(UIApplication*)application didFinishLaunchingWithOptions:(NSDictionary*)launchOptions
    {
        self.viewController = [[MainViewController alloc] init];
        self.viewController.startPage = @"home.html"; // relative path works
        return [super application:application didFinishLaunchingWithOptions:launchOptions];
    }
    
    @end

```

 - Doesnt works if the value is set absolute like below.

` self.viewController.startPage = "file:///Users/vittal/Library/Developer/CoreSimulator/Devices/DAFABB98-CD5B-4B05-B32C-958430CA70A2/data/Containers/Bundle/Application/A0417DFF-BC82-41BA-B6B4-3141D85E8E3A/MyApp.app/www/index.html ";`

**Comment by wilk-polarny** [comment]
Yup, this is basically a showstopper for some frameworks out there. Is there any way to work around this issue without having to downgrade to an older version of the webview plugin?

**Comment by jcesarmobile** [comment]
Full path is not supported, but you can call `setServerPath` from `CDVWKWebViewEngine` class with the path to the folder where you `.html` start page is
