### ISSUE TITLE
Gives 401 (unauthorized) when loading audio source from tmp directory

### ISSUE THREAD

**Issue by ArkeshGKalathiya** [ionic-team/cordova-plugin-ionic-webview#196]
(IOS)
After recording with media-capture plugin, I am using file.fullPath as source input to the audio tag.

v2.2.0 is giving 401 status 

v1.2.1 is working fine

Network response of both plugin version

Not working

![screen shot 2018-10-16 at 4 40 27 pm](https://user-images.githubusercontent.com/28758546/47017615-58bb1c80-d170-11e8-974a-014488570d38.png)

Working

![screen shot 2018-10-16 at 2 39 07 pm](https://user-images.githubusercontent.com/28758546/47017627-61135780-d170-11e8-8421-7914aefccf85.png)

**Comment by genereg1** [comment]
Have a same problem

**Comment by ArkeshGKalathiya** [comment]
Hi, I actually managed to solve this issue by following code. You will just need file name. and rest you can depend on file plugin.

import { File } from '@ionic-native/file';

let tmpDirectory = this.file.tempDirectory;
let url = (window as any).Ionic.WebView.convertFileSrc(tmpDirectory+<<file>>.name);

**Comment by jcesarmobile** [comment]
Closing as the Author managed to fix it.
