### ISSUE TITLE
The compilation fails of cordova build ios

### ISSUE THREAD

**Issue by laiyinjie** [ionic-team/cordova-plugin-ionic-webview#200]
src/ios/GCDWebServer/Requests/GCDWebServerDataRequest.m
Please init _data as NSMutableData* _data in GCDWebServerDataRequest after line 38

**Comment by jcesarmobile** [comment]
Xcode version?

**Comment by jcesarmobile** [comment]
Probably related to the Xcode version, please, use Xcode 9 or newer as it's required for submitting apps to the App Store.
Also that class is now gone, so closing the issue
