### ISSUE TITLE
Videos served from file system thorugh local server are not seekable on android

### ISSUE THREAD

**Issue by yelhouti** [ionic-team/cordova-plugin-ionic-webview#205]
When using the html5 video tag with a video sotored in the assets, seek is not possible.

Possible cause/fix:
Server does not support "partial content":
`WebViewLocalServer:createWebResourceResponse` uses  `WebViewLocalServer:PathHandler` which always answers with 200 OK instead 206 PartialContent for videos. doing so would allow html5 video player to seek video and load in memory only the desired parts

**Comment by weiz18** [comment]
hi, any updates on this issue as I am also facing the same issue.

**Comment by lounai-chen** [comment]
Me too

**Comment by jcesarmobile** [comment]
Can you try with this changes? https://github.com/ionic-team/cordova-plugin-ionic-webview/pull/295

**Comment by yelhouti** [comment]
@jcesarmobile 
There are two main issue with that code:
1- if the vide is too big, the player crash be cause out of memory, and default maxRange should be used
2- When only a range is requested/returned, the response stream should only contain the desired data

**Comment by yelhouti** [comment]
@jcesarmobile support is broken, full stream is returned instead of correct range. please fix this.
