### ISSUE TITLE
Ionic 3 ios error: Failed to install 'cordova-plugin-ionic-webview': TypeError: Invalid Version: undefined

### ISSUE THREAD

**Issue by voxiel** [ionic-team/cordova-plugin-ionic-webview#218]
I'm working in an ionic 3 project and when trying to run "cordova platform add ios" I'm getting the following error:

"Failed to install 'cordova-plugin-ionic-webview': TypeError: Invalid Version: undefined"

Heres the full code: 

Using cordova-fetch for cordova-ios@~4.5.4 Adding ios project... Creating Cordova project for the iOS platform: Path: platforms/ios Package: io.ionic.starter Name: MyApp iOS project created with cordova-ios@4.5.5 Installing "cordova-plugin-device" for ios Installing "cordova-plugin-ionic-keyboard" for ios Installing "cordova-plugin-ionic-webview" for ios Failed to install 'cordova-plugin-ionic-webview': TypeError: Invalid Version: undefined at new SemVer (/usr/local/lib/node_modules/cordova/node_modules/semver/semver.js:305:11) at Range.test (/usr/local/lib/node_modules/cordova/node_modules/semver/semver.js:1112:15) at Function.satisfies (/usr/local/lib/node_modules/cordova/node_modules/semver/semver.js:1161:16) at checkEngines (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:116:20) at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:313:16 at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:854:54) at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:883:30 at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:13) at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:624:44 at runSingle (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:137:13) Invalid Version: undefined

ionic info:

Ionic:

   ionic (Ionic CLI)  : 4.3.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.3, (and 4 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/voxiel/Library/Android/sdk/)
   ios-deploy        : 1.9.4
   NodeJS            : v10.4.1 (/usr/local/Cellar/node/10.4.1/bin/node)
   npm               : 6.1.0
   OS                : macOS High Sierra
   Xcode             : Xcode 9.4.1 Build version 9F2000

Thanks for your help!

**Comment by jcesarmobile** [comment]
I can't reproduce.
Looks like a Cordova problem.

Try removing the platform and adding it again, and make sure cordova-plugin-ionic-webview have the version specified in both config.xml and package.json

**Comment by Endtry** [comment]
I have the same error

```
Failed to install 'cordova-plugin-ionic-webview': TypeError: Invalid Version: undefined
    at new SemVer (/Users/devmachine2/.nvm/versions/v10.16.0/lib/node_modules/cordova/node_modules/semver/semver.js:305:11)
    at Range.test (/Users/devmachine2/.nvm/versions/v10.16.0/lib/node_modules/cordova/node_modules/semver/semver.js:1112:15)
    at Function.satisfies (/Users/devmachine2/.nvm/versions/v10.16.0/lib/node_modules/cordova/node_modules/semver/semver.js:1161:16)
    at checkEngines (/Users/devmachine2/.nvm/versions/v10.16.0/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:116:20)
    at /Users/devmachine2/.nvm/versions/v10.16.0/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:313:16
    at _fulfilled (/Users/devmachine2/.nvm/versions/v10.16.0/lib/node_modules/cordova/node_modules/q/q.js:854:54)
    at /Users/devmachine2/.nvm/versions/v10.16.0/lib/node_modules/cordova/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/Users/devmachine2/.nvm/versions/v10.16.0/lib/node_modules/cordova/node_modules/q/q.js:816:13)
    at /Users/devmachine2/.nvm/versions/v10.16.0/lib/node_modules/cordova/node_modules/q/q.js:624:44
    at runSingle (/Users/devmachine2/.nvm/versions/v10.16.0/lib/node_modules/cordova/node_modules/q/q.js:137:13)
Invalid Version: undefined
```

```
Ionic:

   ionic (Ionic CLI)  : 4.3.1 (/Users/devmachine2/.nvm/versions/v10.16.0/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.5
   @ionic/app-scripts : 3.1.10

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.1, (and 7 other plugins)

System:

   ios-deploy : 1.9.4
   NodeJS     : v10.16.0 (/Users/devmachine2/.nvm/versions/v10.16.0/bin/node)
   npm        : 6.9.0
   OS         : macOS
   Xcode      : Xcode 10.3 Build version 10G8
```

How It looks like there is a bug on the install of cordova-plugin-ionic-webview
