### ISSUE TITLE
CORS issue with cordova-plugin-ionic-webview2.x in Ionic4

### ISSUE THREAD

**Issue by zcd0000** [ionic-team/cordova-plugin-ionic-webview#229]
### Ionic Info
```
Ionic:

   ionic (Ionic CLI)             : 4.4.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.16
   @angular-devkit/build-angular : 0.10.7
   @angular-devkit/schematics    : 0.7.5
   @angular/cli                  : 7.0.7
   @ionic/angular-toolkit        : 1.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.0.3, (and 4 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/cundongzhang/Library/Android/sdk)
   ios-deploy        : 1.9.4
   NodeJS            : v8.12.0 (/usr/local/bin/node)
   npm               : 6.4.1
   OS                : macOS
   Xcode             : Xcode 10.1 Build version 10B61
```

### Issues Descriptions
   I have installed Nginx reverse proxy server on my computer and configured it to allow CORS. 
When my application is opened in Chrome on mac, it can normally finish CORS request  without any issues . 
    But when I deploy it to android device by "cordova run android" command,  my application running in ionic-webview  doesn't work because of CORS issue.  Ionic-webview can normally send "options" 
request to my Nginx server,  but it has no next response to my server normal "options" response. 
    The below screenshot displays the network request and response from my device to Nginx server.

<img width="888" alt="wx20181129-162758 2x" src="https://user-images.githubusercontent.com/18573209/49214524-d4f87f00-f401-11e8-9412-7497e02abbaa.png">

   The below screenshot is my Nginx server config in nginx.conf file.
   
<img width="695" alt="wx20181129-181701 2x" src="https://user-images.githubusercontent.com/18573209/49215178-2ce3b580-f403-11e8-93f5-e2a1cf9fcde8.png">

**Comment by zcd0000** [comment]
I found the issue caused by the configuration of   `add_header 'Access-Control-Allow-Headers' *` not work when CORS  request is from cordova-plugin-ionic-webview.  I must list all  header types in this configuration just as the below, that's ok.
`     add_header 'Access-Control-Allow-Headers' 'Authorization, Expires, Pragma, DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';`

**Comment by rushabhmakwana-multidots** [comment]
@zcd0000 Did you get any solution for this issue?

**Comment by yigonglitech** [comment]
> @zcd0000 Did you get any solution for this issue?

I found the issue caused by the configuration of add_header 'Access-Control-Allow-Headers' * not work when CORS request is from cordova-plugin-ionic-webview. I must list all header types in this configuration just as the below, that's ok.
add_header 'Access-Control-Allow-Headers' 'Authorization, Expires, Pragma, DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
