### ISSUE TITLE
Error causing tabs to display white screen

### ISSUE THREAD

**Issue by chrisdelambert** [ionic-team/cordova-plugin-ionic-webview#23]
when I run an Ionic 3 project on the simulator using --livereload param I get an uncaught error.

Error: The old format of this exec call has been removed (deprecated since 2.1). Change to cordova.exec(null, null, 'Service', 'action', [arg1, arg2]); ......

It's making some tabs not display

**Comment by chrisdelambert** [comment]
Actually this happens in production builds too - it happens after I updated cordova-plugin-ionic to 2.0.0

**Comment by chrisdelambert** [comment]
![screenshot 2017-10-16 13 59 18](https://user-images.githubusercontent.com/19525279/31591276-7944f1ee-b27a-11e7-9d27-baa2f17374d0.png)

**Comment by manucorporat** [comment]
@chrisdelambert  can I see your deleteSnapshot() method?

**Comment by Fuiste** [comment]
This appears to be an issue related to the breaking JavaScript API changes released in `cordova-plugin-ionic` 2.0.0.

You're likely still including the app ID in your function calls, or using the old signature for some other function in the Deploy plugin.

Check out the plugin API here: http://ionicframework.com/docs/pro/deploy/plugin-api.html

**Comment by chrisdelambert** [comment]
Hi yes it was an issue with the docs I upgraded to 2.0.0 but the docs had
an appId parameter left. I took that out and all way well. You can close
the issue.

**Comment by TheMadBug** [comment]
Thanks, I had the same issue. Copied the example from that very page.
The API specification lower down does remove the appId. Still worth updating that example if you can.
