### ISSUE TITLE
[HIGH] Android app pointing issue

### ISSUE THREAD

**Issue by indraraj26** [ionic-team/cordova-plugin-ionic-webview#235]
What could be the issue >? why it is pointing to localhost?
Apk is pointing to localhost:8100 instead of file:///android_asset/www/index.html

> Ionic:
> 
> ionic (Ionic CLI) : 4.4.0 (C:\Users\HP\AppData\Roaming\npm\node_modules\ionic)
> Ionic Framework : ionic-angular 3.9.2
> @ionic/app-scripts : 3.2.0
> 
> Cordova:
> 
> cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
> Cordova Platforms : android 7.1.2
> Cordova Plugins : cordova-plugin-ionic-webview 1.2.1, (and 14 other plugins)
> 
> System:
> 
> Android SDK Tools : 26.1.1 (C:\Users\HP\AppData\Local\Android\Sdk)
> NodeJS : v8.14.0 (C:\Program Files\nodejs\node.exe)
> npm : 6.4.1
> OS : Windows 10

build gradle

> defaultBuildToolsVersion=“27.0.1” //String
> defaultMinSdkVersion=19 //Integer - Minimum requirement is Android 4.4
> defaultTargetSdkVersion=27 //Integer - We ALWAYS target the latest by default
> defaultCompileSdkVersion=27 //Integer - We ALWAYS compile with the latest by default

Testing on Redmi 4a with android version 7.1.2

Copy this link and paste in your browser
[https://forum.ionicframework.com/t/high-android-app-pointing-issue/149562](url)

**Comment by indraraj26** [comment]
I am using 1.2.1 and testing on Redmi4A (Android Version 7.1.2)
Package Json
> {
  "name": "test",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "start": "ionic-app-scripts serve",
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint"
  },
  "dependencies": {
    "@angular/animations": "^5.2.10",
    "@angular/common": "^5.2.10",
    "@angular/compiler": "^5.2.10",
    "@angular/compiler-cli": "^5.2.10",
    "@angular/core": "^5.2.10",
    "@angular/forms": "^5.2.10",
    "@angular/http": "^5.2.10",
    "@angular/platform-browser": "^5.2.10",
    "@angular/platform-browser-dynamic": "^5.2.10",
    "@ionic-native/android-permissions": "^4.18.0",
    "@ionic-native/background-geolocation": "^4.18.0",
    "@ionic-native/browser-tab": "^4.18.0",
    "@ionic-native/core": "~4.15.0",
    "@ionic-native/diagnostic": "^4.18.0",
    "@ionic-native/geolocation": "^4.18.0",
    "@ionic-native/keyboard": "^4.18.0",
    "@ionic-native/location-accuracy": "^4.18.0",
    "@ionic-native/native-geocoder": "^4.18.0",
    "@ionic-native/network": "^4.18.0",
    "@ionic-native/spinner-dialog": "^4.18.0",
    "@ionic-native/splash-screen": "~4.15.0",
    "@ionic-native/status-bar": "~4.15.0",
    "@ionic/storage": "2.2.0",
    "cordova-android": "7.1.2",
    "cordova-plugin-android-permissions": "^1.0.0",
    "cordova-plugin-browsertab": "^0.2.0",
    "cordova-plugin-compat": "^1.2.0",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-geolocation": "^4.0.1",
    "cordova-plugin-ionic-keyboard": "^2.1.3",
    "cordova-plugin-ionic-webview": "^1.2.1",
    "cordova-plugin-mauron85-background-geolocation": "^2.3.6",
    "cordova-plugin-native-spinner": "^1.1.3",
    "cordova-plugin-nativegeocoder": "^3.1.3",
    "cordova-plugin-network-information": "^2.0.1",
    "cordova-plugin-request-location-accuracy": "^2.2.3",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "cordova-sqlite-storage": "^2.5.2",
    "cordova.plugins.diagnostic": "^4.0.10",
    "intl": "^1.2.5",
    "ionic-angular": "3.9.2",
    "ionic-plugin-keyboard": "^2.2.1",
    "ionic-selectable": "^3.0.3",
    "ionic-tags-input": "^0.1.2",
    "ionic2-calendar": "^0.4.6",
    "ionic2-google-places-autocomplete": "^1.0.2",
    "ionicons": "3.0.0",
    "rxjs": "^5.5.2",
    "serverless": "^1.32.0",
    "sw-toolbox": "3.6.0",
    "typescript": "^2.4.2",
    "zone.js": "0.8.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "3.2.0"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-plugin-whitelist": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {
        "ANDROID_SUPPORT_ANNOTATIONS_VERSION": "27.+"
      },
      "cordova-plugin-ionic-keyboard": {},
      "cordova-plugin-android-permissions": {},
      "cordova-plugin-geolocation": {
        "GEOLOCATION_USAGE_DESCRIPTION": "To locate you"
      },
      "cordova.plugins.diagnostic": {},
      "cordova-plugin-browsertab": {},
      "cordova-plugin-mauron85-background-geolocation": {
        "GOOGLE_PLAY_SERVICES_VERSION": "11+",
        "ANDROID_SUPPORT_LIBRARY_VERSION": "23+",
        "ICON": "@mipmap/icon",
        "SMALL_ICON": "@mipmap/icon",
        "ACCOUNT_NAME": "@string/app_name",
        "ACCOUNT_LABEL": "@string/app_name",
        "ACCOUNT_TYPE": "$PACKAGE_NAME.account",
        "CONTENT_AUTHORITY": "$PACKAGE_NAME"
      },
      "cordova-plugin-request-location-accuracy": {},
      "cordova-plugin-network-information": {},
      "cordova-plugin-native-spinner": {},
      "cordova-plugin-nativegeocoder": {},
      "cordova-sqlite-storage": {},
      "ionic-plugin-keyboard": {}
    },
    "platforms": [
      "android"
    ]
  }
}

**Comment by jcesarmobile** [comment]
is it 8080, or 8010?
In the screenshot of the forum it says 8080

and how does your `<content src="" />` tag looks like in your config.xml?

**Comment by indraraj26** [comment]
Thank you @deliverymanager @jcesarmobile 
This was the  <content src="index.html" /> i don't how it got resolved today in morning i have reinstalled all of my plugins, platforms and node_modules now it is working fine. it is totally strange issue that i have ever faced. 
If i faced again then i will get back to here with all config.xml, index.html, package.json and ionic info. I am closing this issue for now as my issue got resolved and wont be able to reproduce again because i have no clue what was wrong.
Thank you Ionic Team for wonderful framework.

**Comment by indraraj26** [comment]
Today i was building another application i ran ionic app but in chrome inspect i can see my app is pointing to http://localhost:8080/ instead of file:///android_asset/www/index.html Please let me know what causing this 

Package Json

> > {
>   "name": "test",
>   "version": "0.0.1",
>   "author": "Ionic Framework",
>   "homepage": "http://ionicframework.com/",
>   "private": true,
>   "scripts": {
>     "start": "ionic-app-scripts serve",
>     "clean": "ionic-app-scripts clean",
>     "build": "ionic-app-scripts build",
>     "lint": "ionic-app-scripts lint"
>   },
>   "dependencies": {
>     "@agm/core": "^1.0.0-beta.5",
>     "@angular/animations": "^6.1.10",
>     "@angular/cdk": "^6.4.7",
>     "@angular/common": "^6.1.1",
>     "@angular/compiler": "^6.1.1",
>     "@angular/compiler-cli": "^6.1.1",
>     "@angular/core": "^6.1.1",
>     "@angular/forms": "^6.1.1",
>     "@angular/http": "^6.1.1",
>     "@angular/material": "^6.4.7",
>     "@angular/platform-browser": "^6.1.1",
>     "@angular/platform-browser-dynamic": "^6.1.1",
>     "@ionic-native/admob-free": "^4.18.0",
>     "@ionic-native/android-permissions": "^4.18.0",
>     "@ionic-native/core": "~4.15.0",
>     "@ionic-native/diagnostic": "^4.18.0",
>     "@ionic-native/geolocation": "^4.18.0",
>     "@ionic-native/splash-screen": "~4.15.0",
>     "@ionic-native/status-bar": "~4.15.0",
>     "@ionic-tools/emoji-picker": "^1.4.0",
>     "@ionic/storage": "2.2.0",
>     "cordova-admob-sdk": "0.21.0",
>     "cordova-android": "7.1.2",
>     "cordova-plugin-admob-free": "0.24.0",
>     "cordova-plugin-android-permissions": "1.0.0",
>     "cordova-plugin-device": "2.0.2",
>     "cordova-plugin-geolocation": "4.0.1",
>     "cordova-plugin-ionic-keyboard": "^2.0.5",
>     "cordova-plugin-ionic-webview": "2.3.1",
>     "cordova-plugin-splashscreen": "5.0.2",
>     "cordova-plugin-statusbar": "2.4.2",
>     "cordova-plugin-whitelist": "^1.3.3",
>     "cordova-promise-polyfill": "0.0.2",
>     "cordova.plugins.diagnostic": "4.0.10",
>     "ion-datetime-picker-sn": "^0.5.3",
>     "ionic-angular": "3.9.2",
>     "ionic-selectable": "^3.0.3",
>     "ionicons": "3.0.0",
>     "ngx-select-dropdown": "^0.8.1",
>     "rxjs": "^6.3.3",
>     "rxjs-compat": "^6.3.3",
>     "serverless": "^1.32.0",
>     "sw-toolbox": "3.6.0",
>     "typescript": "^3.1.6",
>     "zone.js": "0.8.26"
>   },
>   "devDependencies": {
>     "@ionic/app-scripts": "3.2.0"
>   },
>   "description": "An Ionic project",
>   "cordova": {
>     "plugins": {
>       "cordova-plugin-whitelist": {},
>       "cordova-plugin-statusbar": {},
>       "cordova-plugin-device": {},
>       "cordova-plugin-splashscreen": {},
>       "cordova-plugin-ionic-keyboard": {},
>       "cordova-plugin-android-permissions": {},
>       "cordova-plugin-geolocation": {
>         "GEOLOCATION_USAGE_DESCRIPTION": "To locate you"
>       },
>       "cordova.plugins.diagnostic": {},
>       "cordova-plugin-admob-free": {
>         "ADMOB_APP_ID": "ca-app-pub-9133570779260855~202133140"
>       },
>       "cordova-plugin-ionic-webview": {
>         "ANDROID_SUPPORT_ANNOTATIONS_VERSION": "27.+"
>       }
>     }
>   }
> }

ionic info

> 

> C:\indraraj\test-ionic\test>ionic info
> 
> Ionic:
> 
>    ionic (Ionic CLI)  : 4.4.0 (C:\Users\HP\AppData\Roaming\npm\node_modules\ionic)
>    Ionic Framework    : ionic-angular 3.9.2
>    @ionic/app-scripts : 3.2.0
> 
> Cordova:
> 
>    cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
>    Cordova Platforms     : android 7.1.2
>    Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.1, (and 7 other plugins)
> 
> System:
> 
>    Android SDK Tools : 26.1.1 (C:\Users\HP\AppData\Local\Android\Sdk)
>    NodeJS            : v8.14.0 (C:\Program Files\nodejs\node.exe)
>    npm               : 6.4.1
>    OS                : Windows 10


build gradle

>    //This replaces project.properties w.r.t. build settings
>     project.ext {
>       defaultBuildToolsVersion="27.0.1" //String
>       defaultMinSdkVersion=19 //Integer - Minimum requirement is Android 4.4
>       defaultTargetSdkVersion=27 //Integer - We ALWAYS target the latest by default
>       defaultCompileSdkVersion=27 //Integer - We ALWAYS compile with the latest by default
>     }
> > 

Thank you

**Comment by jcesarmobile** [comment]
Ionic WebView 2.x.x loads from `http://localhost:8080`

**Comment by indraraj26** [comment]
with that my other cordova plugin is not working it always say cordova plugin name is not installed

**Comment by jcesarmobile** [comment]
Which plugin?

**Comment by indraraj26** [comment]
I am testing my app in redmi 4A (android 7.1.2)
Copy this url and paste in your browser
#1
[https://i.ibb.co/VMKFvwY/test3.png](url)
#2 
[https://i.ibb.co/FKfgQY0/test4-Untitled.png](url)

Console log of chrome

```
 vendor.js:145201 Could not find Angular Material core theme. Most Material components may not work as expected. For more info refer to the theming guide: https://material.angular.io/guide/theming
MatCommonModule._checkThemeIsPresent @ vendor.js:145201
vendor.js:3571 Angular is running in the development mode. Call enableProdMode() to enable the production mode.
vendor.js:54520 Ionic Native: tried calling AdMobFree.config, but the AdMobFree plugin is not installed.
pluginWarn @ vendor.js:54520
vendor.js:54532 Install the AdMobFree plugin: 'ionic cordova plugin add cordova-plugin-admob-free'
pluginWarn @ vendor.js:54532
vendor.js:54520 Ionic Native: tried calling AdMobFree.prepare, but the AdMobFree plugin is not installed.
pluginWarn @ vendor.js:54520
vendor.js:54532 Install the AdMobFree plugin: 'ionic cordova plugin add cordova-plugin-admob-free'
pluginWarn @ vendor.js:54532
**vendor.js:2121 ERROR Error: Uncaught (in promise): plugin_not_installed**
    at c (polyfills.js:3)
    at c (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (vendor.js:4263)
    at t.invokeTask (polyfills.js:3)
    at r.runTask (polyfills.js:3)
    at o (polyfills.js:3)
defaultErrorLogger @ vendor.js:2121
cordova.js:1219 deviceready has not fired after 5 seconds.
cordova.js:1212 Channel not fired: onPluginsReady
cordova.js:1212 Channel not fired: onCordovaReady
cordova.js:1212 Channel not fired: onDOMContentLoaded
vendor.js:121712 Ionic Native: deviceready did not fire within 5000ms. This can happen when plugins are in an inconsistent state. Try removing plugins from plugins/ and reinstalling them.

```

And cordova admob free is already installed.
Thank you!

**Comment by uloco** [comment]
I have to use the new version of cordova-plugin-ionic-webview because of an security issue in the versions below 2.1.x. Ios works fine, but now android hangs on the splash screen. (Mentioned here https://ionic.zendesk.com/hc/en-us/articles/360015176994-2019-01-03-Security-Alert-for-cordova-plugin-ionic-webview)

Debug console says: `onic Native: deviceready did not fire within 5000ms. This can happen when plugins are in an inconsistent state. Try removing plugins from plugins/ and reinstalling them.`

I tried reinstalling all of them. Did not work ...

**Comment by uloco** [comment]
I have no clue, this was three years ago lol @ziweiVV

**Comment by ziweiVV** [comment]
so sad to hear that ~ @uloco
