### ISSUE TITLE
Programatically setting focus on an input field.

### ISSUE THREAD

**Issue by ThoorAdam** [ionic-team/cordova-plugin-ionic-webview#238]
I've previously used the following solution to programatically set focus on input fields;
```
@ViewChild('input') myInput;

focusInput(timeout) {
    setTimeout(() => {
        this.myInput.setFocus();
    }, timeout);
}
```

But since i've updated to iOS 12 this has stopped working, are there any workarounds to this issue?

**Note:** In my **config.xml** i've set `<preference name="KeyboardDisplayRequiresUserAction" value="false" />`.

**Comment by cptblues** [comment]
Same issue, I've an iOS 10 wich work fine, and on iOS 12, the focus is not working. Same for the config.xml...

I tried many solutions and it doesn't worked.

**Comment by jcesarmobile** [comment]
closing since there was no response, but should be fixed

**Comment by vinesh89** [comment]
Having same issue

**Comment by nicks258** [comment]
Facing the same issue.
