### ISSUE TITLE
WKWEBView Issue with ion-header 

### ISSUE THREAD

**Issue by gigocabrera** [ionic-team/cordova-plugin-ionic-webview#24]
After I added the WKWebView to my app I get the ion-header issue below.

I posted the issue in the forums [here](https://forum.ionicframework.com/t/wkwebview-issue-with-ion-header/108669) and I completed what a community member suggested:

I started a brand new empty project with latest ionic version, copied the “src/” files to the new project and reinstalled the cordova plugins but the issue persists. I even removed ALL custom css styling from global variables.scss file and from each individual page.

Any other ideas?

![wkwebview_issue_01](https://user-images.githubusercontent.com/6364855/31623316-0d1101be-b26d-11e7-9880-27ab5451507c.jpg)

**Comment by levesquejf** [comment]
Looks like https://github.com/ionic-team/ionic/issues/13144

**Comment by gigocabrera** [comment]
I opened [issue 24](https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/24) and it looks like it is happening on ALL projects (existing and new) after upgrading to WKWEBVIEW and iOS 11. Screenshots below are from an iPhone 7 plus

**Conference app**

![wkwebview_03](https://user-images.githubusercontent.com/6364855/31665717-ca33846a-b317-11e7-8241-69e68ccd0d3c.jpg)

<br>
<br>
<br>
Tabs starter app
<br>

![wkwebview_02](https://user-images.githubusercontent.com/6364855/31665716-c89d6c24-b317-11e7-86e2-13ac0fbffa46.jpg)

**Comment by mhartington** [comment]
Dont believe this is an actual issue with WKWebview plugin. 
Please keep the conversation on the framework side of things.
