### ISSUE TITLE
Open application from CDVViewController

### ISSUE THREAD

**Issue by videmort** [ionic-team/cordova-plugin-ionic-webview#241]
Hello, I have got one cordova plugin that open one custom application.

With version of plugin 1.X works fine but with version 2.X doesn't working on iOS

I attach one screen shoot explaining.
https://ibb.co/TPthswh

This is my iOS code working on version 1.X plugin

```
- (void)open: (CDVInvokedUrlCommand*)command
{
    CDVViewController* viewController = [CDVViewController new];
    viewController.startPage = @"index.html";
    viewController.modalPresentationStyle = UIModalPresentationFullScreen;
    [[self topViewController] presentViewController:viewController animated:YES completion:nil];
}
```
On version 2.X this is the error on Safari. (no error  on xCode console)
`<html><head><title>Error</title></head>   <div style='font-size:2em'>       <p><b>Error</b></p>       <p>Unable to load app.</p>   </div></html>`

If I do one location replace to index.html folder http://localhost:8080/mypluginapp/index.html works the open but to close the application from the plugin is not so simple since to make another location replace outside of this second application housed in the plugin causes the initial application to be reloaded.

**Comment by jcesarmobile** [comment]
The plugin prevents other apps from accessing it's content.
You can try with this preference `<preference name="WKInternalConnectionsOnly" value="false" />`.

But in next 3.x.x release the web server is going away, so it won't work even with that preference.

**Comment by videmort** [comment]
Thanks

**Comment by videmort** [comment]
This is not working 
<preference name="WKInternalConnectionsOnly" value="false" />

So this dynamic opening of html applications based on cordova plugin will never work?

I think it's not a very good decision to limit yourself in this way.
