### ISSUE TITLE
Open application from CDVViewController 

### ISSUE THREAD

**Issue by videmort** [ionic-team/cordova-plugin-ionic-webview#243]
See closed issue #241

**Comment by GusLAN** [comment]
+1

**Comment by jcesarmobile** [comment]
Either you are not explaining correctly what you want or I didn’t understand you. Can you provide a sample app with the problem you are describing?

**Comment by videmort** [comment]
Yes sure 
https://github.com/videmort/testapp.git

Just clone, npm install and build ios.
it's a blank app ionic v1 with one button who open the plugin.

If you remove cordova-plugin-ionic-webview you will se that works fine.

**Comment by jjimenezh** [comment]
+1

**Comment by jcesarmobile** [comment]
Please people, stop with the ups and +1

**Comment by ArturoBernalg** [comment]
+1

**Comment by jcesarmobile** [comment]
It works with `<preference name="UseScheme" value="true" />` 

Next version won't have a web server and it will just use the scheme, so it will work.
