### ISSUE TITLE
cordova-plugin-ionic-webview,tips:"Unable to load app"

### ISSUE THREAD

**Issue by Ssssk** [ionic-team/cordova-plugin-ionic-webview#245]
If there are multiple ios projects generated by ionic on the phone, when they start separately, they will appear Unable to start. I have tested cordova-plugin-ionic-webview plugin. I hope to fix the bug of this plugin. Thank you...

**Comment by Ssssk** [comment]
you can try it..

**Comment by Ssssk** [comment]
the plugin version my used is 2.2.3..

**Comment by jcesarmobile** [comment]
To avoid collision between apps you have to use a different port on every app with the `WKPort` preference like `<preference name="WKPort" value="8089" />`.

Or use `<preference name="UseScheme" value="true" />` which won't use the web server.

**Comment by Ssssk** [comment]
I added the above method in the config.xml file, but it did not take effect. Was the location I added wrong? ...

**Comment by Ssssk** [comment]
> To avoid collision between apps you have to use a different port on every app with the `WKPort` preference like `<preference name="WKPort" value="8089" />`.
> 
> Or use `<preference name="UseScheme" value="true" />` which won't use the web server.

I tried both of the above methods, but they didn't seem to work. I added and built the project in the config.xml file.

**Comment by Ssssk** [comment]
> <preference name="UseScheme" value="true" />

![image](https://user-images.githubusercontent.com/14329054/50040759-a24ab980-0084-11e9-81b4-f1bf4cbfd04a.png)
