### ISSUE TITLE
cordova-plugin-ionic-webview 

### ISSUE THREAD

**Issue by Ssssk** [ionic-team/cordova-plugin-ionic-webview#246]
![image](https://user-images.githubusercontent.com/14329054/50005789-927c9800-ffe6-11e8-93f7-da7357df75c3.png)

**Comment by jcesarmobile** [comment]
What's your Xcode version?

**Comment by Ssssk** [comment]
> What's your Xcode version?

8.2.1

**Comment by jcesarmobile** [comment]
Xcode 9 is mandatory since las August, Xcode 10 will be mandatory starting in March, so we don’t support Xcode 8 or older anymore

**Comment by Ssssk** [comment]
ok,i know. thanke you!
