### ISSUE TITLE
Android 5 and 6 do not support playing local music and video

### ISSUE THREAD

**Issue by lounai-chen** [ionic-team/cordova-plugin-ionic-webview#248]
Although convertFileSrc lets you access the local music file to http://localhost:8080, it won't play in android 5 or 6.Clicking the play button does not trigger the shouldInterceptRequest override function in the IonicWebViewEngine class. It is suspected that the returned header file is missing
` var  nativePath_convertFileSrc = _window.Ionic.WebView.convertFileSrc(url_music); `

**Comment by lounai-chen** [comment]
audio and  video

**Comment by jcesarmobile** [comment]
Can you try with this changes? https://github.com/ionic-team/cordova-plugin-ionic-webview/pull/295
