### ISSUE TITLE
Version 3.x

### ISSUE THREAD

**Issue by l3ender** [ionic-team/cordova-plugin-ionic-webview#253]
The [current readme for this repo](https://github.com/ionic-team/cordova-plugin-ionic-webview/blob/0dee0cf308a73eec202eac558912d3cb00f8ca1f/README.md) references `cordova-plugin-ionic-webview` version `3.x`, and even has steps on how to migrate to 3.x.

However the latest version I see [in npm](https://www.npmjs.com/package/cordova-plugin-ionic-webview) is `2.3.1`, and the documentation on npm is different (it has steps on migrating to 2.x).

Could someone please clarify if there is a 3.x version, and if so can it be published to npm with appropriate documentation?

**Comment by jcesarmobile** [comment]
Sorry about that, we use master as the development branch and we didn't want to release the major version during Christmas.
It's published now.
