### ISSUE TITLE
<base href="/" /> issue Ionic 4.

### ISSUE THREAD

**Issue by connorlurring** [ionic-team/cordova-plugin-ionic-webview#261]
Like #77, whenever the base is set to `/` in my application, all of the JavaScript resources fail to load: resulting in a white screen after the splash screen. This issue is only present on the iOS version of my application. The solution of setting base to `./` then breaks all of the app's static assets.

Ionic info:
```
Ionic:

   ionic (Ionic CLI)             : 4.6.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.0
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.0.0, (and 3 other plugins)

System:

   ios-deploy : 1.9.4
   NodeJS     : v10.10.0 (/Users/connorl/.nvm/versions/node/v10.10.0/bin/node)
   npm        : 6.4.1
   OS         : macOS Mojave
   Xcode      : Xcode 10.1 Build version 10B61
```

I am using the latest Ionic rc version as well as the latest `cordova-plugin-ionic-webview` version.

**Comment by jcesarmobile** [comment]
I can't reproduce.
Can you provide a sample project?
In which iOS version are you testing? real device or simulator?

**Comment by connorlurring** [comment]
@jcesarmobile I am unable to reproduce in a new project. Any recommendations for solving this issue in an existing project?

Already tried deleting the plugins/node_modules/platforms/www

**Comment by connorlurring** [comment]
The eventual fix for this issue was creating a completely new project, and copying the src directory of my existing project into the new one. This fixed the issue, which must've been caused by a part of the build process.
