### ISSUE TITLE
Failed to load resource: unsupported URL only on iOS

### ISSUE THREAD

**Issue by RameshkrishnanV** [ionic-team/cordova-plugin-ionic-webview#266]
Hi, i'm using this plugin version 2.3.1
and i getting this error
Failed to load resource: unsupported URL
unsafe:ionic-asset:///var/mobile/Containers/Data/Application/4554564-564554-5646545/tmp/cdv_photo_014.jpg

only on iOS platform. please help me to fix this
config.xml
 
"name="WKPort" value="8080""
name="UseScheme" value="true"
        allow-intent href="itms:*"
        allow-intent href="itms-apps:*"

**Comment by Bramzor** [comment]
Problem is the UseScheme. When it is set to false, you can just do: http://localhost:8080/_file_/var/mobile.... to load those files on both iOS 10 and 11. When set to true, the url I mentioned works on iOS 10 but not on iOS 11. I'm not sure how to access it on iOS 11 though. Where did you get the ionic-asset from?

**Comment by Bramzor** [comment]
Noticed that ionic-asset:// was missing but even when adding <allow-navigation href="ionic-asset://*" /> it didnt solve it yet.

**Comment by kohlia** [comment]
Did you find a solution to this

**Comment by kohlia** [comment]
Yea I didn't find any solution to this either so just waiting

**Comment by geshub** [comment]
I also got the problem when UseScheme is set to true ( cordova-plugin-ionic-webview v2.3.1) with a custom port. I've tried everything to whitelist but i always got this on IOS11:
Refused to load unsafe:ionic://app/img/def_picture2.png because it does not appear in the img-src directive of the Content Security Policy.
Does anyone managed to configure allow-navigation and Content-Security-Policy to allow those files ? I don't want to go back to UseScheme set to false because of the security issue.

**Comment by kohlia** [comment]
`<meta http-equiv="Content-Security-Policy" content="default-src 'self' ionic: data: gap: https://ssl.gstatic.com 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; media-src 'self'; img-src ionic: 'unsafe-inline'">
`

Worked for me

**Comment by RameshkrishnanV** [comment]
@Bramzor Actually u r right. UseScheme=true is not working for iOS.

Finally fixed the issue by setting preferences to the iOS
preference name="WKPort" value="8080" 
preference name="UseScheme" value="false" 

specifically set theses preference for iOS.

Thanks everyone!

**Comment by geshub** [comment]
@RameshkrishnanV why are you closing since Ionic explicitly told to use UseSheme = true and a different port for security ?

**Comment by RameshkrishnanV** [comment]
@geshub  Hey ionic web view by default it takes useScheme as false. so its ok to use it in preferences
see this
https://github.com/ionic-team/cordova-plugin-ionic-webview/blob/2.x/README.md

**Comment by geshub** [comment]
@RameshkrishnanV yes but did you see the security notice ? [https://ionic.zendesk.com/hc/en-us/articles/360015176994-2019-01-03-Security-Alert-for-cordova-plugin-ionic-webview?utm_campaign=Security%20Alert%20Native%20Plugins&utm_source=hs_email&utm_medium=email&utm_content=68797151&_hsenc=p2ANqtz-9hZwITdoeFJXj4o-QDV4CimsDo34Y6jKx2wI4KU5hA9ePaVhQtJINtsZ9rfdHrDy8biJvRRRCwVeRLluaP291KHMrwSA&_hsmi=68797151](2019-01-03 | Security Alert for cordova-plugin-ionic-webview)

**Comment by Bramzor** [comment]
UseScheme = false is indeed a BAD idea but its the only way to work around the issue today. But we need to keep this issue open to track as it still requires a fix. Usescheme = false is a security risk today.

**Comment by prescindivel** [comment]
```this.sanitize.bypassSecurityTrustResourceUrl(window.Ionic.WebView.convertFileSrc(path))```

this solved to me

**Comment by elewin** [comment]
> `this.sanitize.bypassSecurityTrustResourceUrl(window.Ionic.WebView.convertFileSrc(path))`
> 
> this solved to me

Where are you setting that?

**Comment by himalayaahuja** [comment]
> > `this.sanitize.bypassSecurityTrustResourceUrl(window.Ionic.WebView.convertFileSrc(path))`
> > this solved to me
> 
> Where are you setting that?

you need to set up a custom pipe for this importing dom sanitizer from angular platform browser

**Comment by DimitriGuitton** [comment]
I encountered the same error and I solved it with
```
import { DomSanitizer } from '@angular/platform-browser';
import { WebView } from '@ionic-native/ionic-webview/ngx';

constructor ( private webview: WebView, private sanitizer: DomSanitizer)

this.sanitizer.bypassSecurityTrustResourceUrl( this.webview.convertFileSrc( imgPath ) );
```

Thanks to @prescindivel 


> `this.sanitize.bypassSecurityTrustResourceUrl(window.Ionic.WebView.convertFileSrc(path))`
> 
> this solved to me

**Comment by kauawerle** [comment]
> Encontrei o mesmo erro e resolvi-o com
> 
> ```
> import { DomSanitizer } from '@angular/platform-browser';
> import { WebView } from '@ionic-native/ionic-webview/ngx';
> 
> constructor ( private webview: WebView, private sanitizer: DomSanitizer)
> 
> this.sanitizer.bypassSecurityTrustResourceUrl( this.webview.convertFileSrc( imgPath ) );
> ```
> 
> Graças a @prescindivel
> 
> > `this.sanitize.bypassSecurityTrustResourceUrl(window.Ionic.WebView.convertFileSrc(path))`
> > isso resolveu para mim

Can you show your html ?

**Comment by kauawerle** [comment]
> Encontrei o mesmo erro e resolvi-o com
> 
> ```
> import { DomSanitizer } from '@angular/platform-browser';
> import { WebView } from '@ionic-native/ionic-webview/ngx';
> 
> constructor ( private webview: WebView, private sanitizer: DomSanitizer)
> 
> this.sanitizer.bypassSecurityTrustResourceUrl( this.webview.convertFileSrc( imgPath ) );
> ```
> 
> Graças a @prescindivel
> 
> > `this.sanitize.bypassSecurityTrustResourceUrl(window.Ionic.WebView.convertFileSrc(path))`
> > isso resolveu para mim

can you show your HTML ?

**Comment by d-loki** [comment]
Here is my HTML code

```
<ion-content>
            <img class="picture" [src]="image.path">
            <p class="t-primary t-90 center" (click)="selectImage()">Ajouter une
                photo</p>
</ion-content>
```

And my code to take a picture

```
image: {
        name: string;
        path: string | SafeResourceUrl;
        filePath: string;
    };

constructor( 
                 private actionSheetController: ActionSheetController,
                 private camera: Camera,
                 private platform: Platform,
                 private filePath: FilePath,
                 private file: File,
                 private storage: Storage,
                 private webview: WebView,
                 private sanitizer: DomSanitizer, ) {
    }

pathForImage( img ) {
        if ( img === null ) {
            return '';
        } else {
            if ( this.platform.is( 'android' ) ) {
                return this.sanitizer.sanitize( SecurityContext.RESOURCE_URL,
                                                this.sanitizer.bypassSecurityTrustResourceUrl( this.webview.convertFileSrc( img ) ) );
            } else {
                return this.sanitizer.bypassSecurityTrustResourceUrl( this.webview.convertFileSrc( img ) );
            }
        }
    }

    async selectImage() {
        const actionSheet = await this.actionSheetController.create( {
                                                                         header: 'Select Image source',
                                                                         buttons: [
                                                                             {
                                                                                 text: 'Galerie ',
                                                                                 handler: () => {
                                                                                     this.takePicture( this.camera.PictureSourceType.PHOTOLIBRARY );
                                                                                 },
                                                                             },
                                                                             {
                                                                                 text: 'Appareil Photo',
                                                                                 handler: () => {
                                                                                     this.takePicture( this.camera.PictureSourceType.CAMERA );
                                                                                 },
                                                                             },
                                                                             {
                                                                                 text: 'Annuler',
                                                                                 role: 'cancel',
                                                                             },
                                                                         ],
                                                                     } );
        await actionSheet.present();
    }

    takePicture( sourceType: PictureSourceType ) {
        const options: CameraOptions = {
            quality: 40,
            sourceType,
            encodingType: this.camera.EncodingType.JPEG,
            saveToPhotoAlbum: false,
            correctOrientation: true,
            mediaType: this.camera.MediaType.PICTURE,
            targetHeight: 1000,
            targetWidth: 1000
        };

        this.camera.getPicture( options ).then( imagePath => {
            if ( this.platform.is( 'android' ) && sourceType === this.camera.PictureSourceType.PHOTOLIBRARY ) {
                this.filePath.resolveNativePath( imagePath )
                    .then( filePath => {
                        const correctPath = filePath.substr( 0, filePath.lastIndexOf( '/' ) + 1 );
                        const currentName = imagePath.substring( imagePath.lastIndexOf( '/' ) + 1, imagePath.lastIndexOf( '?' ) );
                        this.copyFileToLocalDir( correctPath, currentName, this.createFileName() );
                    } );
            } else {
                const correctPath = imagePath.substr( 0, imagePath.lastIndexOf( '/' ) + 1 );
                const currentName = imagePath.substr( imagePath.lastIndexOf( '/' ) + 1 );
                this.copyFileToLocalDir( correctPath, currentName, this.createFileName() );
            }
        } );

    }

    createFileName() {
        const d = new Date(),
            n = d.getTime();
        return n + '.jpg';
    }

    copyFileToLocalDir( namePath, currentName, newFileName ) {
        this.file.copyFile( namePath, currentName, this.file.dataDirectory, newFileName ).then( success => {
            this.updateStoredImages( newFileName );
        }, error => {
            this.commonService.toast( 'Erreur pendant le stockage de l\'image' );
        } );
    }

    updateStoredImages( name ) {
        const filePath = this.file.dataDirectory + name;
        const resPath = this.pathForImage( filePath );
        this.image = {
            name,
            path: resPath,
            filePath,
        };
    }
```

**Comment by kauawerle** [comment]
> path

Tanks :3

**Comment by kauawerle** [comment]
> Here is my HTML code
> 
> ```
> <ion-content>
>             <img class="picture" [src]="image.path">
>             <p class="t-primary t-90 center" (click)="selectImage()">Ajouter une
>                 photo</p>
> </ion-content>
> ```
> 
> And my code to take a picture
> 
> ```
> image: {
>         name: string;
>         path: string | SafeResourceUrl;
>         filePath: string;
>     };
> 
> constructor( 
>                  private actionSheetController: ActionSheetController,
>                  private camera: Camera,
>                  private platform: Platform,
>                  private filePath: FilePath,
>                  private file: File,
>                  private storage: Storage,
>                  private webview: WebView,
>                  private sanitizer: DomSanitizer, ) {
>     }
> 
> pathForImage( img ) {
>         if ( img === null ) {
>             return '';
>         } else {
>             if ( this.platform.is( 'android' ) ) {
>                 return this.sanitizer.sanitize( SecurityContext.RESOURCE_URL,
>                                                 this.sanitizer.bypassSecurityTrustResourceUrl( this.webview.convertFileSrc( img ) ) );
>             } else {
>                 return this.sanitizer.bypassSecurityTrustResourceUrl( this.webview.convertFileSrc( img ) );
>             }
>         }
>     }
> 
>     async selectImage() {
>         const actionSheet = await this.actionSheetController.create( {
>                                                                          header: 'Select Image source',
>                                                                          buttons: [
>                                                                              {
>                                                                                  text: 'Galerie ',
>                                                                                  handler: () => {
>                                                                                      this.takePicture( this.camera.PictureSourceType.PHOTOLIBRARY );
>                                                                                  },
>                                                                              },
>                                                                              {
>                                                                                  text: 'Appareil Photo',
>                                                                                  handler: () => {
>                                                                                      this.takePicture( this.camera.PictureSourceType.CAMERA );
>                                                                                  },
>                                                                              },
>                                                                              {
>                                                                                  text: 'Annuler',
>                                                                                  role: 'cancel',
>                                                                              },
>                                                                          ],
>                                                                      } );
>         await actionSheet.present();
>     }
> 
>     takePicture( sourceType: PictureSourceType ) {
>         const options: CameraOptions = {
>             quality: 40,
>             sourceType,
>             encodingType: this.camera.EncodingType.JPEG,
>             saveToPhotoAlbum: false,
>             correctOrientation: true,
>             mediaType: this.camera.MediaType.PICTURE,
>             targetHeight: 1000,
>             targetWidth: 1000
>         };
> 
>         this.camera.getPicture( options ).then( imagePath => {
>             if ( this.platform.is( 'android' ) && sourceType === this.camera.PictureSourceType.PHOTOLIBRARY ) {
>                 this.filePath.resolveNativePath( imagePath )
>                     .then( filePath => {
>                         const correctPath = filePath.substr( 0, filePath.lastIndexOf( '/' ) + 1 );
>                         const currentName = imagePath.substring( imagePath.lastIndexOf( '/' ) + 1, imagePath.lastIndexOf( '?' ) );
>                         this.copyFileToLocalDir( correctPath, currentName, this.createFileName() );
>                     } );
>             } else {
>                 const correctPath = imagePath.substr( 0, imagePath.lastIndexOf( '/' ) + 1 );
>                 const currentName = imagePath.substr( imagePath.lastIndexOf( '/' ) + 1 );
>                 this.copyFileToLocalDir( correctPath, currentName, this.createFileName() );
>             }
>         } );
> 
>     }
> 
>     createFileName() {
>         const d = new Date(),
>             n = d.getTime();
>         return n + '.jpg';
>     }
> 
>     copyFileToLocalDir( namePath, currentName, newFileName ) {
>         this.file.copyFile( namePath, currentName, this.file.dataDirectory, newFileName ).then( success => {
>             this.updateStoredImages( newFileName );
>         }, error => {
>             this.commonService.toast( 'Erreur pendant le stockage de l\'image' );
>         } );
>     }
> 
>     updateStoredImages( name ) {
>         const filePath = this.file.dataDirectory + name;
>         const resPath = this.pathForImage( filePath );
>         this.image = {
>             name,
>             path: resPath,
>             filePath,
>         };
>     }
> ```

I tried to do the same thing and it went wrong, I will send the code 

`this.imageCroppedUri = await this.webView.convertFileSrc(data);
          const image = await this.getImage(this.sanitizer.bypassSecurityTrustResourceUrl(this.imageCroppedUri) as string);`

**Comment by d-loki** [comment]
What is your error?

**Comment by kauawerle** [comment]
> What is your error?

he is don´t load image in ios ´-´

**Comment by d-loki** [comment]
> > What is your error?
> 
> he is don´t load image in ios ´-´


Can you send your HTML5 and TS code

**Comment by kauawerle** [comment]
> > > What is your error?
> > 
> > 
> > he is don´t load image in ios ´-´
> 
> Can you send your HTML5 and TS code

My html : 

`<div class="input-image cropped">
                <img [src]="imageCroppedUri" alt="" id="image-cropped">
                <a class="image-remove-button"
                  (click)="onRemoveImageButtonClicked()"><i class="fas
                    fa-times"></i></a>
              </div>`

my ts : 

`async onCameraButtonClick(type: string) {
    if (this.platform.is("cordova")) {
      this.log("onCameraButtonClick(" + type + ")");
      const options: CameraOptions = {
        quality: 90,
        destinationType: this.camera.DestinationType.FILE_URI,
        encodingType: this.camera.EncodingType.JPEG,
        mediaType: this.camera.MediaType.PICTURE,
        allowEdit: false,
        correctOrientation: true,
        sourceType: type === 'camera' ? this.camera.PictureSourceType.CAMERA : this.camera.PictureSourceType.PHOTOLIBRARY
      }

      this.camera.getPicture(options).then(async (imageData) => {

        //this.imageUri = normalizeURL(imageData);

        this.log(imageData);

        const data = await this.crop.crop(imageData, { quality: 75, targetWidth: -1, targetHeight: -1 });
        console.log(this.sanitizer.bypassSecurityTrustResourceUrl(this.webView.convertFileSrc(data)  as string));
        if (data) {
          this.log(data);
          this.imageCroppedUri = await this.webView.convertFileSrc(data);
          const image = await this.getImage(this.sanitizer.bypassSecurityTrustResourceUrl(this.imageCroppedUri) as string);
          this.updateImageWarning(image);

        } else {
          this.log("Data is null...");
        }


      }, (err) => {
        error => { console.error('Error getPicture', err); }
      });
    } else {
      this.imageCroppedUri = "/assets/imgs/background.png";
      const image = await this.getImage(this.imageCroppedUri);
      this.updateImageWarning(image);
    }
  }
`

**Comment by d-loki** [comment]
This is my code for getPicture

```
 this.camera.getPicture( options ).then( imagePath => {
            if ( this.platform.is( 'android' ) && sourceType === this.camera.PictureSourceType.PHOTOLIBRARY ) {
                this.filePath.resolveNativePath( imagePath )
                    .then( filePath => {
                        const correctPath = filePath.substr( 0, filePath.lastIndexOf( '/' ) + 1 );
                        const currentName = imagePath.substring( imagePath.lastIndexOf( '/' ) + 1, imagePath.lastIndexOf( '?' ) );
                        this.copyFileToLocalDir( correctPath, currentName, this.createFileName() );
                    } );
            } else {
                const correctPath = imagePath.substr( 0, imagePath.lastIndexOf( '/' ) + 1 );
                const currentName = imagePath.substr( imagePath.lastIndexOf( '/' ) + 1 );
                this.copyFileToLocalDir( correctPath, currentName, this.createFileName() );
            }
        } );
```
You can see that I am changing image path and after I use 
`this.sanitizer.bypassSecurityTrustResourceUrl( this.webview.convertFileSrc( img ) );` to display the image

**Comment by kauawerle** [comment]
> > > What is your error?
> > 
> > 
> > he is don´t load image in ios ´-´
> 
> Can you send your HTML5 and TS code
> 
> This is my code for getPicture
> 
> ```
>  this.camera.getPicture( options ).then( imagePath => {
>             if ( this.platform.is( 'android' ) && sourceType === this.camera.PictureSourceType.PHOTOLIBRARY ) {
>                 this.filePath.resolveNativePath( imagePath )
>                     .then( filePath => {
>                         const correctPath = filePath.substr( 0, filePath.lastIndexOf( '/' ) + 1 );
>                         const currentName = imagePath.substring( imagePath.lastIndexOf( '/' ) + 1, imagePath.lastIndexOf( '?' ) );
>                         this.copyFileToLocalDir( correctPath, currentName, this.createFileName() );
>                     } );
>             } else {
>                 const correctPath = imagePath.substr( 0, imagePath.lastIndexOf( '/' ) + 1 );
>                 const currentName = imagePath.substr( imagePath.lastIndexOf( '/' ) + 1 );
>                 this.copyFileToLocalDir( correctPath, currentName, this.createFileName() );
>             }
>         } );
> ```
> 
> You can see that I am changing image path and after I use
> `this.sanitizer.bypassSecurityTrustResourceUrl( this.webview.convertFileSrc( img ) );` to display the image

Tanks, you help me much

**Comment by jemys89** [comment]
hey this work for my!
```
if(this.platform.is('ios')){
              imgPath = this.domSanitizer.bypassSecurityTrustResourceUrl((<any>window).Ionic.WebView.convertFileSrc(mediaUri));
              imgPath = urlnorm.changingThisBreaksApplicationSecurity.replace("ionic://localhost", "");
            }else{
             imgPath = (<any>window).Ionic.WebView.convertFileSrc(mediaUri);
            }
```

**Comment by razam217** [comment]
If anyone from ionic 1 wants the solution to this issue, please use this stackoverflow post to fix it.
[https://stackoverflow.com/a/30034955](url)

**Comment by creativitycomkw** [comment]
100% working solution
ionic webview >= 4

`this.profileImgSrc = this.sanitizer.bypassSecurityTrustResourceUrl(this.webview.convertFileSrc(imagePath));`

**Comment by Lyfei** [comment]
> 100% working solution ionic webview >= 4
> 
> `this.profileImgSrc = this.sanitizer.bypassSecurityTrustResourceUrl(this.webview.convertFileSrc(imagePath));`

ionic 3, webview 4.2.1 , still error.
