### ISSUE TITLE
Google Maps Android. V3

### ISSUE THREAD

**Issue by videmort** [ionic-team/cordova-plugin-ionic-webview#269]
Application must be served from https instead http

![image](https://user-images.githubusercontent.com/11390548/51109538-d0dbc180-17f5-11e9-9708-aff6e1163d61.png)

**Comment by jcesarmobile** [comment]
Did you change the Hostname preference? if you don't change it, it will use localhost, which should work just fine

**Comment by videmort** [comment]
Yes, I change it because localhost is potentially risky using google maps api key and now is mandatory for google.

So changing the hostname http://myapp is not valid because is not a secure origin. So... I think that the solution is serve on https

**Comment by agm** [comment]
Same problem here. 

https://goo.gl/rStTGz

**Comment by videmort** [comment]
@jcesarmobile is possible to serve https instead http?

**Comment by jcesarmobile** [comment]
In 3.1.0 you can use the Scheme prefernce to use https instead of http `<preference name="Scheme" value="https" />`
