### ISSUE TITLE
Can I use this plugin for ionic 1 App?

### ISSUE THREAD

**Issue by dhavalsoni2001** [ionic-team/cordova-plugin-ionic-webview#27]
I would like to know if its possible to use this plugin in ionic 1. 
Currently I am using https://github.com/Telerik-Verified-Plugins/WKWebView so if we can use this plugin in ionic1 as well. so That would be great.

**Comment by kas84** [comment]
You can. But if you use localStorage, you probably will need to fork cordova-plugin-migrate-localstorage because apparently localStorage filename is different in each engine.

**Comment by jcesarmobile** [comment]
Closing, you can use it as kas84 explained
