### ISSUE TITLE
[v3] WKBind gone

### ISSUE THREAD

**Issue by wilk-polarny** [ionic-team/cordova-plugin-ionic-webview#271]
Hi,

The introduction of the WKBind property in version 2.x solved the problems related to #33 , by allowing to set a custom bind address for the server (`127.0.0.1` instead of `localhost`) - which is needed for some enterprise per-app VPN solutions.

The property seems to gone for good with version 3.x - did the interals change much? Can we still patch the plugin manually?

**Comment by jcesarmobile** [comment]
It's gone because there is no server and apps are served from `ionic://` scheme, so that problem should not be present as VPN should not try to mess with that scheme at all.

Anyway, there is a new similar preference, `Hostname` that can be set to `127.0.0.1` if you want.
