### ISSUE TITLE
Content-Length:2

### ISSUE THREAD

**Issue by mbossX** [ionic-team/cordova-plugin-ionic-webview#285]
my app use v2.0.0, embed a mp4 with video tag, mp4 is download and save with file plugin, I can get url success, like 'http://localhost:8080/_file_/xxxxx/xx/.file.mp4.
at android 5.1,  when video tag play it, the network response content-length is 2, and request range is 0-1, it fail to play.
 .......
but at android 6+, it fine, mp4 is play fine.

anyone help me?

**Comment by mbossX** [comment]
it seems android 5.1 http lib can not set response headers correctly!

**Comment by mbossX** [comment]
help!

**Comment by jcesarmobile** [comment]
Sorry, as you say, it's fixed in latest versions of system webview, most users have it up to date, if not, there is nothing we can do about it.
