### ISSUE TITLE
Remove `_alwaysRunsAtForegroundPriority` for wkwebview because it's a private API

### ISSUE THREAD

**Issue by Andrewpk** [ionic-team/cordova-plugin-ionic-webview#286]
Apps that use a private API in the app store might not always get rejected, but the latest version of Xcode does prompt with a warning during the uploading process that we're using a private API.

Use of private APIs is against the Apple developer agreement and should be removed or compiled out with a macro/flag at the very least (by default).

**Comment by Andrewpk** [comment]
<img width="382" alt="screen shot 2019-01-26 at 7 10 59 pm" src="https://user-images.githubusercontent.com/1033728/51794324-24f38800-219e-11e9-8888-5683333e376a.png">

**Comment by NielsLeenheer** [comment]
I'm seeing the same issue after uploading a binary to Apple. It still allows it to proceed and submit for review.

![image 31-01-2019 at 11 44](https://user-images.githubusercontent.com/233230/52049288-b3288f00-254d-11e9-878f-97aea9e6b404.jpg)

**Comment by LabDeve** [comment]
same here...
![schermata 2019-02-05 alle 08 44 48](https://user-images.githubusercontent.com/17450809/52259290-7c25f500-2922-11e9-90d3-67630dbfd30f.png)

**Comment by equinoxss** [comment]
This issue turns out to be the cause of our issue reported here: https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/293
