### ISSUE TITLE
Cross origin requests are only supported for HTTP

### ISSUE THREAD

**Issue by yanglongji** [ionic-team/cordova-plugin-ionic-webview#29]
i get this error when i use ioinc-webview with ngx-translate

here's my code (in app.component.ts):

plt.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      if(plt.is("cordova")){
        statusBar.styleLightContent();
        splashScreen.hide();
        translate.setDefaultLang('zh');
        translate.get('manup.mandatory.title').subscribe(
          value => {
            console.log(value + 'x');
          },err => {
            console.log(err + 'xxx');
          }
        )
      }
})
}

**Comment by yanglongji** [comment]
also with code-push #13

**Comment by polfernandez** [comment]
Same problem duplicated here [https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/31](https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/31)
+ whitescreen

**Comment by jcesarmobile** [comment]
closing as invalid, the issue doesn't show any request code

it's probably a CORS problem, see the Ionic CORS guide 
https://ionicframework.com/docs/troubleshooting/cors

**Comment by UnGaucho** [comment]
This isn't CORS related, it's because it's loading from local files without protocol. Please reopen.
