### ISSUE TITLE
WKWebView input[type="date"] localization

### ISSUE THREAD

**Issue by cfz42** [ionic-team/cordova-plugin-ionic-webview#291]
I am working on a multilanguage ionic v1 app but all the `input[type="date"]` are in English, completely ignoring the iPhone regional/language settings.

I expect the date selector to be in the same language as the iPhone.

**Steps to reproduce:**

  *  Create an ionic v1 app with a sample `input[type="date"]` in it
  *  Set your iPhone language and locale to French
  *  The date selector is still in English

Do you have any idea how to translate this input? I suspect this must be somewhere in WKWebView configuration but I don't know where to look for.

Please don't suggest using a jquery date picker plugin or something in the likes, what I want used to work properly on UIWebView.

Version used:

    Ionic version 1

I also opened an issue on the ionic v1 repo [here](https://github.com/ionic-team/ionic-v1/issues/395)

**Comment by jcesarmobile** [comment]
This is not a webview issue, but a Cordova "issue", Cordova projects only support English by default, you have to configure the `CFBundleLocalizations` that your app supports and then native dialogs will appear in the supported languages.
