### ISSUE TITLE
HTTP requests fail using custom hostname in cordova-plugin-ionic-webview

### ISSUE THREAD

**Issue by williamhilldevs** [ionic-team/cordova-plugin-ionic-webview#292]
Hi guys,
Thank you for the awesome work in this plugin. My app is much snappier!

Here is my problem:
I am using this plugin in my Cordova App and I set a custom value for the `hostname` as explained in the project documentation (https://github.com/ionic-team/cordova-plugin-ionic-webview#hostname):

`<preference name="Hostname" value="my-hostname" />`

I can see that local resources are correctly retrieved using the right prefix and hostname (eg. `ionic://my-hostname/plugins/cordova-plugin-dialogs/www/notification.js`) but all http requests silently fail. (they are not in the network tab at all or they return cached HTML)

I could simply stick to the default origins `ios://localhost` for iOS and `http://localhost` for Android (these work) but I'm having trouble with InfoSec to whitelist the localhost origin to allow CORS.

How can I solve this?

( stackoverflow: https://stackoverflow.com/questions/54454984/http-requests-fail-using-custom-hostname-in-cordova-plugin-ionic-webview )

**Comment by robcoekaerts** [comment]
In WebViewLocalServer.java, line 417, it seems that the domain argument is just completely ignored. Could this be causing this issue?
```
public void hostAssets(final String domain,
                                        final String assetPath) {
    this.isAsset = true;
    this.basePath = assetPath;

    createHostingDetails();
  }

  private void createHostingDetails() {
    final String assetPath = this.basePath;

    if (assetPath.indexOf('*') != -1) {
      throw new IllegalArgumentException("assetPath cannot contain the '*' character.");
    }

    PathHandler handler = new PathHandler() {
      @Override
      public InputStream handle(Uri url) {
        InputStream stream = null;
        String path = url.getPath();
        try {
          if (path.startsWith(contentStart)) {
            stream = protocolHandler.openContentUrl(url);
          } else if (path.startsWith(fileStart) || !isAsset) {
            if (!path.startsWith(fileStart)) {
              path = basePath + url.getPath();
            }
            stream = protocolHandler.openFile(path);
          } else {
            stream = protocolHandler.openAsset(assetPath + path);
          }
        } catch (IOException e) {
          Log.e(TAG, "Unable to open asset URL: " + url);
          return null;
        }

        return stream;
      }
    };
```

**Comment by jcesarmobile** [comment]
On the linked SO question you mentioned that you solved it by removing and re adding the platforms, so closing the issue.
