### ISSUE TITLE
iOS: using <video> doesn't respect playsinline and when first viewed only shows icon

### ISSUE THREAD

**Issue by d3vhound** [ionic-team/cordova-plugin-ionic-webview#294]
Started a brand new ionic project and added this plugin. 

added this video code.
`<video
          width="300"
          controls
          playsinline
          muted
          crossorigin="anonymous"
          type="video/mp4"
        >
          <source src="https://pageify.sfo2.digitaloceanspaces.com/019af8d8-91a7-494c-b0df-8035f04736dd">
        </video>`

Get this as a result. 
<img width="381" alt="screen shot 2019-01-31 at 2 47 04 pm" src="https://user-images.githubusercontent.com/17565159/52088348-3a3b2e80-2571-11e9-9db9-3aaf7458c14d.png">

Is this expected or what can we do to make it actually reflect what web browsers show us? (which is an embedded video respecting all attributes)

Also, clicking that play button automatically makes the video fullscreen, so the playsinline attribute is simply ignored.

Can't set a poster attribute either, only the icon shows still.

**Comment by tmk1991** [comment]
Add this to cordova.xml 

VVVV
[https://github.com/ionic-team/ionic/issues/17368#issuecomment-460076497](url)

**Comment by jcesarmobile** [comment]
Yeah, as @tmk1991 said, you have to enable it in config.xml with `<preference name="AllowInlineMediaPlayback" value="true" />`, default value is false https://cordova.apache.org/docs/en/latest/config_ref/index.html#preference

**Comment by ollydixon** [comment]
@tmk1991 our config.xml get's overwritten; any ideas?
