### ISSUE TITLE
why cant we use https:// both for iOS and Android?

### ISSUE THREAD

**Issue by studentIvan** [ionic-team/cordova-plugin-ionic-webview#301]
Some api adding scripts with urls something like <script src="//hostname and it fails on ionic:// protocol. Why can't we have the same http/https as on the Android?

**Comment by jcesarmobile** [comment]
Because you can only use https for serving local files if you have a web server.
There are no web servers for iOS that allow to use https.
Also, we don't want to use a local web server.
