### ISSUE TITLE
Ionic WebView v3.x cannot access video src from iOS Documents directory

### ISSUE THREAD

**Issue by JoeMeeks** [ionic-team/cordova-plugin-ionic-webview#302]
I have cordova-plugin-ionic-webview v3.1.2 installed and I am able to load image thumbnails from the iOS documents directory, but html5 video tag src attributes with ionic:// URLs do not work.

- `ionic://localhost/_app_file_/var/mobile/Containers/Data/Application/5427DD11-7B0A-44CA-875B-D8CB32829CE2/Documents/Sack/7601.jpg` is fine for background-image CSS
- `ionic://localhost/_app_file_/var/mobile/Containers/Data/Application/5427DD11-7B0A-44CA-875B-D8CB32829CE2/Documents/Sack/7601.mov` as the sanitized src for `<video [src]="sanitize(item.source)"></video>` does not work

**Comment by jcesarmobile** [comment]
Can you provide a sample app? I didn't have any problem using video tag for local videos

**Comment by jcesarmobile** [comment]
No sample app was provided and I can't reproduce on mine, so closing.

**Comment by Lyfei** [comment]
> I have cordova-plugin-ionic-webview v3.1.2 installed and I am able to load image thumbnails from the iOS documents directory, but html5 video tag src attributes with ionic:// URLs do not work.
> 
> * `ionic://localhost/_app_file_/var/mobile/Containers/Data/Application/5427DD11-7B0A-44CA-875B-D8CB32829CE2/Documents/Sack/7601.jpg` is fine for background-image CSS
> * `ionic://localhost/_app_file_/var/mobile/Containers/Data/Application/5427DD11-7B0A-44CA-875B-D8CB32829CE2/Documents/Sack/7601.mov` as the sanitized src for `<video [src]="sanitize(item.source)"></video>` does not work

Solved?
