### ISSUE TITLE
Is it possible to suspend the view manually?

### ISSUE THREAD

**Issue by bushev** [ionic-team/cordova-plugin-ionic-webview#306]
I'm using background mode (geolocation) to handle long-running TCP/IP connection while the application running in the background.

I have a case, the TCP/IP connection can be terminated by remote side and I want to suspend the app. I'm turning off geolocation tracking, but `WKSuspendInBackground=false` option prevents app to be suspended as I expect.

When the TCP/IP connection terminate I send Local Notification to the user about that. So, without `WKSuspendInBackground=false` it doesn't work. Because webview suspended immediately when application enters background mode. So, I can't notify a user (JS suspended).

The best solution for me is to suspend webview manually, after TCP/IP connection termination. Is it possible to do that?

**Comment by jcesarmobile** [comment]
No, it's not possible and WKSuspendInBackground is going away soon.
If it's the server what terminates the connection, what about sending a push notification?

**Comment by bushev** [comment]
Hi, it's 3rd party server, I have no access, unfortunately.
