### ISSUE TITLE
Upgraded webview for IOS 12.2 but now IOS 10 device(s) crash.. 

### ISSUE THREAD

**Issue by dickverweij** [ionic-team/cordova-plugin-ionic-webview#308]
I recently upgraded the wkwebview plugin for our app to get it to work on 12.2 
(the  _alwaysRunsAtForegroundPriority bug)

But I now get crashes on devices with IOS 10. I looked into it and you deployment target version is now 11 ? 
(<preference name="deployment-target" value="11.0"/>)

Is there a way to get both IOS versions supported again?

**Comment by jcesarmobile** [comment]
Not sure what _alwaysRunsAtForegroundPriority bug you mean, but 3.x only supports iOS 11+, if you want to support iOS 10 you have to use latest 2.x, we are back porting most of the fixes there

**Comment by dickverweij** [comment]
https://stackoverflow.com/questions/54474910/ionic-app-crashes-on-ios-12-2-because-of-alwaysrunsatforegroundpriority

**Comment by jcesarmobile** [comment]
That is not caused by this plugin
