### ISSUE TITLE
Check for 404 in Android causes our application to fail

### ISSUE THREAD

**Issue by robcoekaerts** [ionic-team/cordova-plugin-ionic-webview#313]
Hello,

As commented on commit https://github.com/ionic-team/cordova-plugin-ionic-webview/commit/f7a551e59013bb3ee50c7ed9f490368a639bf361: Due to the introduced check for issue https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/217, that uses InputStream.available(), our application stops working.

Is it possible to implement this functionality without using available()?

**Comment by jcesarmobile** [comment]
can you provide a sample app?

**Comment by jcesarmobile** [comment]
Closing as there was no answer after more than a month
