### ISSUE TITLE
App gets suspended when doing Apple Pay provisioning with iOS 12

### ISSUE THREAD

**Issue by buleglay** [ionic-team/cordova-plugin-ionic-webview#316]
cordova-plugin-ionic-webview version: 2.4.0

When we're trying to add a card to Apple Wallet, as soon as the native Apple view kicks in, the App goes into background mode which is expected.

And when clicking Next button in the Apple view, it meant to trigger the callback in the App to fire a XHR request, but somehow once the XHR call is made, the App gets suspended and all network assertions are released, means the App won't receive any response.

I tried downgrading to UIWebView and the issue is gone.

It's also working fine in iOS 11 with WKWebKit, seems to be an issue only introduced in iOS 12.

**Comment by ghenry22** [comment]
get the latest version of the webview plugin from github.  Set the wksuspendinbackground value to false in config.xml.  Otherwise javascript processing is immediately suspended when the app goes to background (such as in this case) and any calls back to javascript will just be lost.

**Comment by jcesarmobile** [comment]
closing as we added the wksuspendinbackground preference again.

Anyway, I think this is something the Apple Pay plugin should handle
