### ISSUE TITLE
Unable to show the images

### ISSUE THREAD

**Issue by sumannits** [ionic-team/cordova-plugin-ionic-webview#322]
Hi,
I am trying to use this plugin in IOS. But I am getting file path like this : -
"cdvphotolibrary://photo?photoId=ADB24867-0CCB-4207-923A-DC9D44233434%2FL0%2F001"

I have tried to put that on img src but it is not showing. Some of the files are returning the file url like this : -
filePath: "/var/mobile/Media/DCIM/100APPLE/IMG_0652.JPG"

I am able to show those but not able to show "cdvphotolibrary".
Can anybody tell me how can I show this.

**Comment by jcesarmobile** [comment]
cdvphotolibrary scheme is not supported at the moment, can you provide a sample app that uses that scheme?

**Comment by jcesarmobile** [comment]
closing as there was no response after more than a month

**Comment by vitorbarros** [comment]
Hello, I am facing the same issue

**Comment by jcesarmobile** [comment]
Can you create a new issue providing more information?
It was closed because there wasn't enough information, so your comment doesn't help neither.
