### ISSUE TITLE
add scrollEnable info to documentation

### ISSUE THREAD

**Issue by marecektn** [ionic-team/cordova-plugin-ionic-webview#325]
I was struggling a lot why my content is not scrollable when switched to WKWebview plugin, it turned out that it has to be set manually in `config.xml` file by adding `<preference name="ScrollEnabled" value="true" />`

I googled this for several hours, stumbled upon Mark's article about this issue:
https://markandruth.co.uk/2017/09/15/using-ionics-wkwebview-engine-with-standard-cordovaphonegap-projects#comment-6365

Please add scrolling info into GitHub installation or FAQ page, so it will save devs couple of hours.
Thanks 🥇

**Comment by BumbleeLin** [comment]
I have added this tag to the config.xml and I'm still not able to scroll. Any other reason you might have?

**Comment by marecektn** [comment]
For me the `<preference ...` solved the issue. 
I think the main point of Ionic is that you have viewport of screen size and every component is handling scrolling events by its own (kind of what native app development feels like)
Since I am not heavy user of this framework, I could not help you on this one.
