### ISSUE TITLE
[regression] cannot set scheme to 'http' instead of 'ionic'

### ISSUE THREAD

**Issue by martijnlutgens** [ionic-team/cordova-plugin-ionic-webview#328]
In the merge https://github.com/ionic-team/cordova-plugin-ionic-webview/pull/221 the issue was fixed to be able to set the scheme to 'http://' instead of 'ionic://'. In version 4.0.0 it now again seems to be impossible to set the scheme to 'http://'.

Why is it not possible anymore to use normal scheme's? This makes it impossible to communicate with Google Api's since http or https are the only scheme's allowed. For now I have gone back to V2.3.1, but I would like to stay up-to-date with the latest version.

Referring to the readme of V4.0.0:

```xml
<preference name="iosScheme" value="httpsionic" />
```

Default value is `ionic`

Configures the Scheme the app uses to load the content.

Values like `http`, `https` or `file` are not valid and will use default value instead.

**Comment by jcesarmobile** [comment]
It can't use http because there is no web server anymore. WKWebView allow to use custom schemes to serve local files, but some schemes like http, https or file are now allowed (by Apple, not us).
You can configure the scheme to not use ionic.
Using httpsionic works on google maps, not sure which google API service are you using 
https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/282

**Comment by martijnlutgens** [comment]
I am using the Google Drive API, but I am not able to add httpsionic:// to the allowed domain. And that is not specific for that API, but for the global Google oAuth2 settings of an App.

What do you mean with 'there is no webserver anymore'?

The examples that I have seen on SO are running fine on http://localhost with WKWebView. Actually in the previous versions of this plugin it worked fine in conjuction with WKWebView, so I don't understand why it suddenly cannot be done anymore.

**Comment by jcesarmobile** [comment]
We used to have a local web server running inside the app, but we removed it because it was causing problems

**Comment by martijnlutgens** [comment]
Ok. Is there any possibility that the option to use a local webserver will come back? Because this totally eliminates the usage of Google API's.

**Comment by jcesarmobile** [comment]
No, the web server is not coming back. 
You can still use 2.x version of the plugin, it has the web server and we backport the fixes there

**Comment by martijnlutgens** [comment]
Ok I will stick to V2 then. Thx for your replies and work.

**Comment by jcesarmobile** [comment]
Anyway, would be good if you could report this issue to Google, they have listened to users when httpsionic stoped working on Google maps API and fixed the problems there.

**Comment by vpnocsen** [comment]
Hi @martijnlutgens 
Could you please give me the exactly the version number that worked for your problem. 
I got the same issue :(.
Thanks

**Comment by jcesarmobile** [comment]
Any v2.x can still use the old web server which uses http instead of ionic scheme, so better use latest one.
