### ISSUE TITLE
ios 12.2 beta - focus on text element doesn't open keyboard

### ISSUE THREAD

**Issue by yosikal** [ionic-team/cordova-plugin-ionic-webview#330]
I tested my Ionic App on iOS 12.2 beta and found out that keyboard is not being opened when focusing on text element. It seems like that element isn't getting focused at all. This works perfectly on previous iOS versions and also works on 12.2 if I remove the cordova-plugin-ionic-webview.

**Comment by jcesarmobile** [comment]
To be clear, what you mean is that programmatically focusing a field doesn't work, right?

Like doing `document.getElementById("focusme").focus();` should focus the field and show the keyboard, but it doesn't?

**Comment by yosikal** [comment]
Correct.

**Comment by zarko-tg** [comment]
Experiencing something along the same lines on Android (iOS is fine), but I got no clear case to describe yet. We've been in process of upgrading Cordova (what a mess...), plugins etc, now more or less functional using cordova 9.0.0, cordova-ios 5.0.0, cordova-android 8.0.0, cordova-plugin-ionic-webview 2.4.0.
We have a few instances of using .setFocus on TextInput's (Ionic 3.9.4).

**Comment by gregavola** [comment]
@jceasarmobile is this deployed to npm for 2.x users?

**Comment by jcesarmobile** [comment]
It’s not published yet, will do it later today, I want to review some of the pull requests before

**Comment by jcesarmobile** [comment]
4.0.1 and 2.4.1 are released with the fix

**Comment by Dr-Bonsai** [comment]
It keeps not working for me. 
I am using:

![image](https://user-images.githubusercontent.com/7988329/55226332-08fb7980-5215-11e9-802a-ccbf6c334079.png)
Cordova 8
Npm 6.9.0

I am having problems on iOs not on Android

Also, when I am setting HideKeyboardFormAccessoryBar to false, the accessoryBar shows but not the keyboard/selector. This is weird.

**Comment by MattDHill** [comment]
I'm still seeing this issue. When calling focus(), the keyboard "tries" to focus on the input element and display the keyboard, but then quickly retreats. I'm on iOS 11.4.1 and cordova-plugin-ionic-webview 4.1.1.
