### ISSUE TITLE
cursor blinks on ios

### ISSUE THREAD

**Issue by dkd051** [ionic-team/cordova-plugin-ionic-webview#335]
![cursor blinks](https://i.imgur.com/eYwmn9I.gif)

[https://youtu.be/4mwK8Wyun6Q](https://youtu.be/4mwK8Wyun6Q)

**Cursor blinks when I typing on Input or Textarea
How to fix this issue?
When I uninstalled cordova-plugin-ionic-webview, everything is fine,
but I have to use cordova-plugin-ionic-webview because of some other ios issues.**

**I use cordova-plugin-ionic-webview 4.0.0. and platform version is ios@4.4.0**
How to fix this issue?
---------------
cli packages: (/Users/----/.nvm/versions/node/v8.11.1/lib/node_modules)

@ionic/cli-utils  : 1.19.2
ionic (Ionic CLI) : 3.20.0
global packages:

cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1) 
local packages:

@ionic/app-scripts : 3.2.2
Cordova Platforms  : android 6.3.0 ios 4.4.0
Ionic Framework    : ionic-angular 3.9.2
System:

Android SDK Tools : 26.1.1
ios-deploy        : 1.9.4 
Node              : v8.11.1
npm               : 5.6.0 
OS                : macOS
Xcode             : Xcode 10.1 Build version 10B61 
Environment Variables:

ANDROID_HOME : /Users/mingyu/Library/Android/sdk
Misc:

backend : pro

**Comment by jcesarmobile** [comment]
What's the problem with this? 
I've checked some native apps and the cursor always blinks, why do you want/need to prevent it?

**Comment by dkd051** [comment]
@jcesarmobile 
when I input text first letter, text blinks and shows placeholder even if text exists.
[see video](https://youtu.be/uhlscOaJMLc)

**Comment by jcesarmobile** [comment]
Ah, I understand it now, you mean the placeholder appearing and disappearing even when there are some characters.

Anyway, this is a problem on Safari itself, you should report it to Apple/Webkit, there is nothing we can do about it. If you report it to them, mention that you are using Korean keyboard, as it doesn't happen with other languages where a keystroke is a character, while in Korean keyboard the first character can be replaced by a second one depending on the next char you tap, and that's what causes the placeholder to appear while current character is being replaced.
