### ISSUE TITLE
[4.0.1] iOS - App directory XHR requests fail since migrating from 2.x

### ISSUE THREAD

**Issue by wilk-polarny** [ionic-team/cordova-plugin-ionic-webview#338]
Hi!

I noticed that JS XHR requests stopped to work for local app directory files since migrating from the 2.x webview (404 not found).
For example, we try to access the cordova config.xml using the path "../config.xml" - which worked before scheme based access. Now we have to access those files using the full absolute path like: ionic://localhost/FILEPREFIX/APPCONTAINER/config.xml.

Altough we fixed it on our side by setting another path, some third party plugins still have problems accessing their files (plugins/XYZ/....) when using XHR requests. We can't change the way those plugins work, thus I would like to know whether there is a way to work around this issue. Could overriding XMLHttpRequest.send or load be helpful here?

**Comment by jcesarmobile** [comment]
Anything inside www folder should be accessible with relative paths, can you provide more information about which plugins are having problems?

**Comment by wilk-polarny** [comment]
@jcesarmobile 

We access the files like this:

`var xhr = new XMLHttpRequest();
xhr.addEventListener("load", function () {
const parser = new DOMParser();
if (!xhr.responseText) {
console.error('config.xml file not found');
return;
}
});
xhr.addEventListener("error", function () {
console.error('error while reading config.xml');
return;
});

let url = "../config.xml";

xhr.open("get", url, true);
xhr.send();`

Plugins try to access URLs like: `../plugins/plugin-name/res/data.json` and also fail with `Failed to load resource: unsupported URL ionic://localhost/plugins/plugin-name/res/data.json`

**Comment by jcesarmobile** [comment]
config.xml is outside www folder, so you can’t access it with a relative path, shouldn’t work on 2.x neither, just in 1.x.

I’m asking for specific plugins that do that to take a look, plugins folder is inside www, so should be accessible

**Comment by wilk-polarny** [comment]
Ah I see, thank you! The plugin vendor seemed to fix that in the latest release.
