### ISSUE TITLE
Module cordova-plugin-ionic-webview.IonicWebView does not exist-iOS

### ISSUE THREAD

**Issue by shrijeetDeshmukh** [ionic-team/cordova-plugin-ionic-webview#339]
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (util.js, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (keyboard.js, line 0)
[Error] Error: Module cordova-plugin-ionic-webview.IonicWebView does not exist.
	runTask (polyfills.js:3:10916)
	invokeTask (polyfills.js:3:16802)
	p (polyfills.js:2:27655)
	v (polyfills.js:2:27895)
[Log] deviceready has not fired after 5 seconds. (cordova.js, line 1139)
[Log] Channel not fired: onPluginsReady (cordova.js, line 1132)
[Log] Channel not fired: onCordovaReady (cordova.js, line 1132)
[Warning] Ionic Native: deviceready did not fire within 5000ms. This can happen when plugins are in an inconsistent state. Try removing plugins from plugins/ and reinstalling them. (vendor.js, line 1)

Getting above error when Updating existing app in iOS. Not able to load the application and app is stuck on white screen, but when I install the app after deleting existing app then its working fine.

**Here is my ionic info**
Ionic:

   ionic (Ionic CLI)  : 4.6.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.3

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 1.2.0, (and 22 other plugins)

System:

   NodeJS : v10.15.0 (/usr/local/bin/node)
   npm    : 6.4.1
   OS     : macOS Mojave
   Xcode  : Xcode 10.2 Build version 10E125

**Comment by jcesarmobile** [comment]
You are using a very old version of the plugin, we no longer support that, only 4.x or 2.x, but not 1.x.

**Comment by shrijeetDeshmukh** [comment]
@jcesarmobile  Thanks It worked after updating the web view plugin :)
