### ISSUE TITLE
How do I know that I have started using it?

### ISSUE THREAD

**Issue by auron105** [ionic-team/cordova-plugin-ionic-webview#341]
Stupid question.. 
How do I know that I have started using it?

i used cordova and ionic 4 thx~!

**Comment by jcesarmobile** [comment]
You can check `window.location.href`, if it looks like `http://localhost` on Android and `ionic://localhost` on iOS then it's working.
Also on Xcode console you should see a "Using Ionic WKWebView" message. And in Logcat a "Ionic Web View Engine Starting" message
