### ISSUE TITLE
Cannot display photo/image in iOS

### ISSUE THREAD

**Issue by daikeung** [ionic-team/cordova-plugin-ionic-webview#344]
I installed cordova-plugin-ionic-migrate-localstorage and cordova-plugin-ionic-webview to keep local storage record during migration from UIWebView to WKWebView. However, image cannot be display and I am not okay to use window.Ioniic.WebView.convertFileSrc(path) as I am using ExtJS. below is the setting in config.xml:

```
 <preference name="iosScheme" value="httpsionic" />
    <allow-navigation href="httpsionic://*" />
    <allow-navigation href="file://*" />
    <allow-navigation href="file:///*" />
    <allow-navigation href="*" />
    <feature name="CDVWKWebViewEngine">
        <param name="ios-package" value="CDVWKWebViewEngine" />
    </feature>
   <preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />
```

Error:

> [discovery] errors encountered while discovering extensions: Error Domain=PlugInKit Code=13 "query cancelled" UserInfo={NSLocalizedDescription=query cancelled}

What should I do to show photo correctly?

**Comment by jcesarmobile** [comment]
You have to use `window.Ionic.WebView.convertFileSrc(path)`, that's regular javascript, should work with any framework or none at all.

**Comment by daikeung** [comment]
@jcesarmobile , I am using mentioned 2 plugins but faced below error: 
TypeError: undefined is not an object (evaluating 'window.Ionic.WebView.convertFileSrc') which I cannot handle path successfully. How can I fix it and why I have this problem? FYI, cordova-plugin-ionic-migrate-localstorage 0.0.2 "Migrate WebView Data" & cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"

**Comment by jcesarmobile** [comment]
The convertFileSrc function is available on 2.x and newer, if you are in 1.2.1, there was a similar function called normalizeURL or something like that. We don’t support 1.x.x of the plugin

**Comment by daikeung** [comment]
@jcesarmobile I tried to use "cordova plugin add cordova-plugin-ionic-webview@latest" to download latest version but it still 1.2.1. Why don't let me download 4.0.1 for latest one?

**Comment by jcesarmobile** [comment]
Did you remove it first? If not, Cordova won’t update it.
If you removed it first but still got the old one, make sure you are on cordova >=7.1.0, cordova-ios >=4.0.0, cordova-android >=6.4.0.

No idea about the migration, sorry

**Comment by daikeung** [comment]
I used cordova-plugin-ionic-migrate-localstorage v0.0.2 with cordova-plugin-ionic-webview v1.2.1. Then used normalizeURL() suggested by you then solve the problem. Thanks!
