### ISSUE TITLE
IOS 12.2/12.3: Text field in an iframe not focusing on tap

### ISSUE THREAD

**Issue by TarekSalahUddinMahmud** [ionic-team/cordova-plugin-ionic-webview#347]
I am facing an issue on focusing an input field under an iframe. It only focuses when I long press on an input field. Here is the [link of the video](https://youtu.be/SxjlstB6YWc)
[![IMAGE ALT TEXT HERE](http://img.youtube.com/vi/SxjlstB6YWc/0.jpg)](http://www.youtube.com/watch?v=SxjlstB6YWc)

The public repository link is [https://github.com/TarekSalahUddinMahmud/webviewTest](https://github.com/TarekSalahUddinMahmud/webviewTest). Hope you guys can reproduce this issue here.

I have updated my iPhone 7 plus from 11.3 to 12.2. After updating I am facing this problem. I have updated my cordova-plugin-ionic-webview version 3.1.2 to 4.0.1. But the problem persists. This problem also occurs on iPhone 6s v12.3. We are currently using cordova-plugin-ionic-keyboard v2.1.3. We upgraded it from ionic-plugin-keyboard v2.2.1.

Previously I faced the same issue when I updated my phone to 11.3. I was using ionic-plugin-webview at that time. Moving to cordova-plugin-ionic-webview version 3.1.2 solved the problem at that time.

Here is my Ionic info:
Ionic:

   ionic (Ionic CLI)  : 4.0.1
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.8

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : ios 4.5.5

System:

   Android SDK Tools : 26.1.1
   ios-deploy        : 1.9.2
   ios-sim           : 6.1.2
   NodeJS            : v10.15.3 (/usr/local/bin/node)
   npm               : 6.4.1
   OS                : macOS High Sierra
   Xcode             : Xcode 10.1 Build version 10B61

Environment:

   ANDROID_HOME : /Users/bs221/Library/Android/sdk

**Comment by jcesarmobile** [comment]
I can reproduce in your app, but I can't reproduce in this iframe that just shows a regular input text field. `<iframe width="100%" height="300" src="https://jsfiddle.net/drewnoakes/eqemx218/embedded/result/" allowfullscreen="allowfullscreen" allowpaymentrequest frameborder="0"></iframe>`

So might be something on the iframed app's logic preventing the focus.
I also was able to programmatically focus on the field by calling `.focus()` after inspecting it's id.

**Comment by jcesarmobile** [comment]
Ok, I've been able to reproduce by running ionic serve and opening in safari, so that leaves the webview plugin out of the problem too.
As you have also duplicated the issue on https://github.com/ionic-team/ionic-v3/issues/1012, let's continue there, but looks like an Apple bug or some problem on your forms.
