### ISSUE TITLE
CORS with v4.x, iOS Scheme = ionic:// on MS Azure

### ISSUE THREAD

**Issue by Jetro223** [ionic-team/cordova-plugin-ionic-webview#349]
It's impossible to set a CORS Header with the ionic:// scheme on MS Azure

![image](https://user-images.githubusercontent.com/3181108/56273683-81ab7280-60fd-11e9-83ca-58501084970a.png)

Is it possible to "fallback" to http|https?

**Comment by gabriele-sacchi** [comment]
Give a try to the "iosScheme" preference

**Comment by gabriele-sacchi** [comment]
I have the similar issue, I need to use the http or https prefix in order to use a plugin.

**Comment by jcesarmobile** [comment]
Sorry, the webview plugin requires a custom scheme to work that can't be http or https, you should contact Azure and let them know or use a proxy or a plugin that uses native connections so it's not affected by CORS

**Comment by mhartington** [comment]
@Jetro223. Could you email me about this issue. I’m talking with some people from the Azure team and would like to get some more details. 

mike at ionic dot io

**Comment by mohamedZea** [comment]
@mhartington @Jetro223  any news about it ? I am in the same situation ?

**Comment by dotNetkow** [comment]
For what it's worth, we're [actively building](https://github.com/ionic-team/capacitor/pull/2495) a native HTTP plugin for Capacitor to help avoid these types of CORS issues. Cap doesn't use this Cordova plugin (it uses webviews like WKWebView on iOS), so you might consider [migrating](https://capacitor.ionicframework.com/docs/cordova/migration-strategy).

**Comment by Jetro223** [comment]
@mohamedZea 
I changed my API to send the CORS headers I need (and leave the Azure settings)

**Comment by mohamedZea** [comment]
Thank you guys for all you answers.
@Jetro223 What do you mean, can you give me more informations please.

**Comment by Jetro223** [comment]
@mohamedZea Assuming you have a .NET Core API => https://code-maze.com/enabling-cors-in-asp-net-core/
