### ISSUE TITLE
use uiwebview in parallel

### ISSUE THREAD

**Issue by hongnk** [ionic-team/cordova-plugin-ionic-webview#35]
I use wkwebview with indexeddb for ios11. And wanted to use it also for ios9/10.

But Indexeddb in Ios9/ios10 doesn't work very well, therefore I use websql for these 2 ios versions.  But obviously websql can't work with wkwebview, so also need to switch to uiwebview for those.

Question is in what way can I use wkwebview for ios11, and use uiwebview for ios9/10 within a single build?

**Comment by ghenry22** [comment]
use sqlite storage engine, works across all those versions of OS and is shared between wk and ui webviews when people update their OS / devices.

**Comment by jcesarmobile** [comment]
No, it's not possible and it's not going to me implemented as `UIWebView` is now deprecated
