### ISSUE TITLE
iOS: Fullscreen API

### ISSUE THREAD

**Issue by Polm90** [ionic-team/cordova-plugin-ionic-webview#350]
On iOS the fullscreen API is not available.

If I try to access document.documentElement.requestFullscreen i get "undefined".

Is there any workaround, or am I missing something?

I am using cordova 9.0.0, cordova-ios 5.0.0 e the 4.0.1 version of this plugin.

Thank you

**Comment by jcesarmobile** [comment]
For iOS it requires the webkit prefix `document.documentElement.webkitRequestFullscreen`.

But it's not enabled/defined inside the WKWebView.

Anyway, Cordova apps are full screen already, you don't need that API and that's probably why it's not defined.

**Comment by Polm90** [comment]
You are right: a Cordova app can already be fullscreen... but what about an internal iFrame?
An example could be the use of an iFrame to use the PDF.JS viewer: it cannot go fullscreen because there is not the FullScreen API

**Comment by jcesarmobile** [comment]
I don’t know, you can ask Apple why they didn’t enable it for WKWebView, but there is nothing we can do.

**Comment by Polm90** [comment]
Ah ok.
Thank you for your answer!
