### ISSUE TITLE
Input Cursor not showing while typing

### ISSUE THREAD

**Issue by parvageshahariar** [ionic-team/cordova-plugin-ionic-webview#353]
After upgrading to 4.0.1 from 2.0.3 input cursor not showing up. 
I am using ionic-plugin-keyboard

**Comment by jcesarmobile** [comment]
`ionic-plugin-keyboard` is deprecated.
Does it also happen if you remove it?
can you also try with `cordova-plugin-ionic-keyboard` instead?

**Comment by noxiousmobile** [comment]
Does not work with cordova-plugin-ionic-keyboard neither. on latest io13

**Comment by jcesarmobile** [comment]
@noxiousmobile looks like that was an Apple bug and should be fixed on iOS 13.2 according to what some users commented on https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/449
