### ISSUE TITLE
issues using usabilla on ios because of ionic web view protocol(ionic://)

### ISSUE THREAD

**Issue by johnny-carmona** [ionic-team/cordova-plugin-ionic-webview#359]
I'm having an issue, where our feedback script (usabilla) grabs the window.location to submit it as the url value, and we have no control over this script.
issue is, the server returns an error message complaining about the url because the url starts with 'ionic://', could you point me to one of those plugins that would let me change the ionic webview protocol?
btw this happens only on ios

**Comment by jcesarmobile** [comment]
Closing as I already answered on https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/319
