### ISSUE TITLE
[Android] Move to AndroidX

### ISSUE THREAD

**Issue by RTK** [ionic-team/cordova-plugin-ionic-webview#361]
Currently I depend on another plugin, which makes use of the new androidx support libraries. Unfortunately these are not compatible with the old support library imports, thus I would like to see this plugin use the new androidx support library.

For Reference: https://androidx.de/index.html?androidx/annotation/RequiresApi.html

**Comment by jcesarmobile** [comment]
This is something Cordova should embrace first.
In the meantime, there is a plugin that can help you.
See last comment on https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/275

**Comment by RTK** [comment]
Ok, thank you very much for your help.
