### ISSUE TITLE
Referrer header not added to HTTP request due to the use of a custom scheme (ionic://)

### ISSUE THREAD

**Issue by gabriele-sacchi** [ionic-team/cordova-plugin-ionic-webview#365]
I am using Cordova to build an iOS App and I use this Ionic engine (meaning that the app is served from a webserver running on the device).

My `window.location.origin` is "ionic://my-app.com".

A third party API (that I need to use in order to fetch an address suggestion based on what the user types) rejects my HTTP requests because the referrer header is missing in the request.

It's not possible to programmatically add a referrer from the JS layer and these did not work:

- `<meta name="referrer" content="origin">`
- `<meta name="referrer" content="always">`

I suspect that the issue is that the API is using `https` and my iOS App is using the custom scheme (`ionic://` that cannot be changed to `https`). For this reason the referrer is not added by the WebView.

How can I resolve this? 😿 
Thx

( stackoverflow -> [here](https://stackoverflow.com/questions/56044902/how-to-add-missing-referrer-header-to-cordova-ios-app) )

**Comment by amritk** [comment]
Is there any way to just use https:// instead of ionic:// ?

**Comment by Yuripetusko** [comment]
@amritk Unfortunatly not :(, you can use http:// with older version of this plugin, but not https

**Comment by amritk** [comment]
@Yuripetusko yea thats causing issues with the old component router that we're still using. 
I tried poking around the source to fix it but had no luck. I will have to stick with version 2. Thanks

**Comment by amritk** [comment]
Actually, @Yuripetusko do you know if its possible to use HTTP**S** with the older version?

**Comment by Yuripetusko** [comment]
@amritk as far as I know ios local webserver doesn't allow https

**Comment by ciekawy** [comment]
shouldn't the `preference` `Scheme` solve this (as described in the `README.md`?
https://github.com/ionic-team/cordova-plugin-ionic-webview

**Comment by ciekawy** [comment]
unfortunately as mentioned above - no option to use standard `http` or `https` and `referrer` header is not being set.

**Comment by jcesarmobile** [comment]
The plugin doesn't really do anything to fetch/XHR, that's provided by the webview, so you should report it to Apple
