### ISSUE TITLE
ion-header is mixed with webView.

### ISSUE THREAD

**Issue by jsk548** [ionic-team/cordova-plugin-ionic-webview#367]
Hi,
I upgraded this plugin from 1.1.6 to latest. When the inAppBowser is launched, the box-shadow is missing below header which was there before upgrade. The issue is in iOS only. It looks good in Android. Can someone please help me in resolving this.

**Comment by jcesarmobile** [comment]
Can you provide a screenshot?
Also, you mean in the InAppBrowser screen?

**Comment by jsk548** [comment]
yes. InAppBrowser is launched in content area. Attaching screenshots here.
before plugin upgrade[](url)
![before upgrade](https://user-images.githubusercontent.com/22653281/57772995-97c84500-7734-11e9-908f-3b1520833f2b.PNG)
after plugin upgrade
![after upgrade](https://user-images.githubusercontent.com/22653281/57773006-9d258f80-7734-11e9-88e2-39577ec1cbe2.PNG)

**Comment by jcesarmobile** [comment]
Not really sure what do you mean by InAppBrowser is launched in content area. And screenshots don't look like InAppBrowser.
Can you provide a sample app?

**Comment by jcesarmobile** [comment]
No response and no sample app was provided and it's still unclear to me what the problem is, so closing.

Feel free to reopen if you can provide a sample app and provide more details, but I doubt this plugin can cause problems in cordova-plugin-inappbrowser.
