### ISSUE TITLE
assets folder not loading in ionic app when custom hostname is specified in android 9.0

### ISSUE THREAD

**Issue by mayur5478** [ionic-team/cordova-plugin-ionic-webview#368]
If I try to load a js file which is located in assets/js/[myfile].js in index.html in ionic src folder , it tries to load that file from the custom hostname specified http://[hostname]/assets/js/[myfile].js rather than loading it from the local asset . This happens only when I install the webview plugin and in android 9.0 . It works in previous android versions.

**Comment by jcesarmobile** [comment]
Can you provide an example?

**Comment by mayur5478** [comment]
problem with a different js . Sorry for the inconvenience.

**Comment by th3hamm0r** [comment]
@jcesarmobile I just stumbled across this issue, after changing the `Hostname` to fix the iOS cookie issue (https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/22).

If the hostname is set to "xyz.example.com" and the domain does not exist, everything works fine. If the domain is in use, the loading of all assets in android breaks, as for every asset the actual server is requested, not the local server. Note, it didn't help to change the scheme (default http) to something else, eg. "ionic".

My fix was to only configure the `Hostname` for the ios platform and leave the android defaults.
At the end there seems to be a bug on the android-side of the ionic plugin.
