### ISSUE TITLE
API calls blocked on IPhone XR only on Cellular network

### ISSUE THREAD

**Issue by rijink7** [ionic-team/cordova-plugin-ionic-webview#370]
There is no error with the build. it works fine in IPhone 6 & 7 which works on IOS 12.2 and unable to access API's from iPhone Xr when its on cellular network(Sprint LTE ) and the API's works when its connected through WIFI Network.

Version information
Ionic:

ionic (Ionic CLI) : 4.1.2 (/usr/local/lib/node_modules/ionic)
Ionic Framework : ionic-angular 3.9.5
@ionic/app-scripts : 3.1.8

Cordova:

cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
Cordova Platforms : ios 2 5.0.0, ios 5.0.0
Cordova Plugins : cordova-plugin-ionic-keyboard 2.0.5, cordova-plugin-ionic-webview 2.3.1, (and 20 other plugins)
cordova-plugin-ionic-webview  version :4.0.1
System:

Android SDK Tools : 26.0.2 (/Users/afscdev/Library/Android/sdk)
ios-deploy : 1.9.2
ios-sim : 7.0.0
NodeJS : v11.8.0 (/usr/local/bin/node)
npm : 6.5.0
OS : macOS
Xcode : Xcode 10.2.1 Build version 10E1001

**Comment by jcesarmobile** [comment]
Can you provide some information about the API? It wouldn’t be the first time the carrier blocks some API or is unable to access it because of some server setting

**Comment by rijink7** [comment]
@jcesarmobile sorry for the late replay. We are trying to access a GET request. Using IP Address instead of domain. the API's are Accessible over the same network from Iphone 7.both runs on IOS 12.2

**Comment by jcesarmobile** [comment]
is it a local IP address? if so, you can't access it through cellular network

**Comment by rijink7** [comment]
No its not an local IP address.

**Comment by jcesarmobile** [comment]
Sorry, I'm going to close, this is a connectivity problem in your cellular network. The plugin doesn't manage the connections in any way.
