### ISSUE TITLE
cordova : file tag not working in ios 12.2 onwards

### ISSUE THREAD

**Issue by NehaEnstrapp** [ionic-team/cordova-plugin-ionic-webview#371]
I want to open in app browser to select files from my device. I am using file tag. It is working fine in 12.1 but in 12.2 onwards when I tap on browse button, nothing happens.

Any kind of help is highly appreciated. Thanks in advance

**Comment by jcesarmobile** [comment]
Working fine on my iPhone with iOS 12.3.1. 

Also, in case this happens again, you should report it to Apple telling them it's broken on the WKWebView, that's an Apple component that this plugin uses and input file is managed by it, it's not something we can control or fix.
