### ISSUE TITLE
Canvas.toDataURL for external images are not working due to new scheme

### ISSUE THREAD

**Issue by thedeukalion** [ionic-team/cordova-plugin-ionic-webview#373]
Loading an image from external URL to convert to image to Canvas Data does no longer work with new "scheme".

Example code:
```
var img = document.createElement('img');
img.onload = function(e) {
    ctx.drawImage(img, 0, 0, canvas.width, canvas.height);
    var url = canvas.toDataURL(); // Read succeeds, canvas won't be dirty.
};
img.crossOrigin = '';
img.src = 'http://other-domain.com/image.jpg';
```
[https://coderwall.com/p/pa-2uw/using-external-images-with-canvas-getimagedata-and-todataurl](https://coderwall.com/p/pa-2uw/using-external-images-with-canvas-getimagedata-and-todataurl
)

Loading the image is fine, but then calling canvas.toDataURL() does not work due to custom scheme like "myapp://" not being allowed by CORS. Cannot change this on the server side either since the scheme is invalid.

img.onload is called successfully so the image is loaded but once converting to Data URI ("image/png", "image/jpg") there is an error thrown.

**Comment by jcesarmobile** [comment]
I can reproduce if CORS is not enabled on the server, but works fine if CORS is enabled.
As you say you can't configure CORS in your server, you should contact your provider to let you add ionic or myapp as valid origins, or use a proxy.

This is a known limitation of WKWebView and the only solution is to enable CORS.

**Comment by thedeukalion** [comment]
CORS is enabled and I can change it. The problem is that the scheme "myapp://" is no allowed to be added to CORS.

**Comment by jcesarmobile** [comment]
Is not allowed by who? I can add it to my sever without any problem.

**Comment by thedeukalion** [comment]
Like they said:
https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/349

Enforcing this change makes no sense. But that's the point I guess?

**Comment by jcesarmobile** [comment]
The custom scheme is the only way of serving the local assets without using file protocol, which causes some issues.
If that makes no sense to you, you can use cordova-plugin-wkwebview-engine, which uses file protocol
