### ISSUE TITLE
Real content position differs from what is actually visible on iOS

### ISSUE THREAD

**Issue by pavrda** [ionic-team/cordova-plugin-ionic-webview#375]
In Ionic mobile app we display external content in iframe. It happens sometimes that real content position differs from what is actually seen. It is impossible to click the button as it is not at the location where it is seen. If user clicks couple of pixels down, it works. The problem is on iOS only, Android is ok.

I can reveal actual button position by long touch when button label became selected.

Any idea why this happens and how to solve it?

![button](https://user-images.githubusercontent.com/3653568/59343795-f15c6900-8d0c-11e9-8cf0-351c2558b6db.jpg)

**Comment by jcesarmobile** [comment]
not sure if it's still relevant, but looks like an apple bug to me
