### ISSUE TITLE
Input focus not working ***

### ISSUE THREAD

**Issue by realweb** [ionic-team/cordova-plugin-ionic-webview#377]
Hi,

After iOS 12.2 update when I tap into any input field, the cursor (focus) dont appear on the input. No matter I tap into it, I cant  start typing.

If I press the down arrow on the acessory bar, it changes between the input elements and focus occurs. 

If I remove cordova-plugin-webview from the project, things work normally, without any problem. 

Problem seens to be this one: https://github.com/apache/cordova-plugin-wkwebview-engine/issues/71

I tried to install cordova-plugin-wkwebview-inputfocusfix and also added <preference name="KeyboardDisplayRequiredUserAction" value="false" />  but did not work. 

Any clue?

thanks

**Comment by jcesarmobile** [comment]
What's your plugin version? the problem you link was fixed long ago, so not sure if it's the same problem.
Can you provide a sample app?

**Comment by realweb** [comment]
@jcesarmobile 

Thanks for your reply. 
Here is my plugin version list and also ionic info result:

CORDOVA PLUGIN LIST
============
com.unarin.cordova.beacon 3.8.1 "Proximity Beacon Plugin"
cordova-plugin-advanced-http 2.0.11 "Advanced HTTP plugin"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
**cordova-plugin-ionic-webview 4.1.0 "cordova-plugin-ionic-webview"**
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 3.2.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
cordova.plugins.diagnostic 4.0.12 "Diagnostic"

IONIC INFO
============
Ionic:
   Ionic CLI         : 5.0.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework   : ionic1 1.3.4
   @ionic/v1-toolkit : 1.0.22

Cordova:
   Cordova CLI       : 8.0.0
   Cordova Platforms : ios 4.5.5
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.0, (and 10 other plugins)

Utility:
   cordova-res : not installed
   native-run  : 0.2.5

System:
   ios-deploy : 1.9.2
   NodeJS     : v10.16.0 (/usr/local/bin/node)
   npm        : 6.9.0
   OS         : macOS High Sierra
   Xcode      : Xcode 10.1 Build version 10B61


If I remove cordova-plugin-ionic-webview it just works. The problem is that when I tap into any input field, cursor dont stay there. So I cant start typing. The only way to keep the cursor on the input if to use acessory bar up and down arrow. 

Any clue?

**Comment by realweb** [comment]
> @jcesarmobile
> 
> Thanks for your reply.
> Here is my plugin version list and also ionic info result:
> 
> # CORDOVA PLUGIN LIST
> com.unarin.cordova.beacon 3.8.1 "Proximity Beacon Plugin"
> cordova-plugin-advanced-http 2.0.11 "Advanced HTTP plugin"
> cordova-plugin-device 2.0.2 "Device"
> cordova-plugin-file 6.0.1 "File"
> cordova-plugin-geolocation 4.0.1 "Geolocation"
> cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
> cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
> **cordova-plugin-ionic-webview 4.1.0 "cordova-plugin-ionic-webview"**
> cordova-plugin-network-information 2.0.1 "Network Information"
> cordova-plugin-splashscreen 5.0.2 "Splashscreen"
> cordova-plugin-statusbar 2.4.2 "StatusBar"
> cordova-plugin-whitelist 1.3.3 "Whitelist"
> cordova-sqlite-storage 3.2.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
> cordova.plugins.diagnostic 4.0.12 "Diagnostic"
> 
> # IONIC INFO
> Ionic:
> Ionic CLI : 5.0.2 (/usr/local/lib/node_modules/ionic)
> Ionic Framework : ionic1 1.3.4
> @ionic/v1-toolkit : 1.0.22
> 
> Cordova:
> Cordova CLI : 8.0.0
> Cordova Platforms : ios 4.5.5
> Cordova Plugins : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.0, (and 10 other plugins)
> 
> Utility:
> cordova-res : not installed
> native-run : 0.2.5
> 
> System:
> ios-deploy : 1.9.2
> NodeJS : v10.16.0 (/usr/local/bin/node)
> npm : 6.9.0
> OS : macOS High Sierra
> Xcode : Xcode 10.1 Build version 10B61
> 
> If I remove cordova-plugin-ionic-webview it just works. The problem is that when I tap into any input field, cursor dont stay there. So I cant start typing. The only way to keep the cursor on the input if to use acessory bar up and down arrow.
> 
> Any clue?

I think I found the problem. 
The culprit was Angular Material JS version.

I was using version 1.1.4. After I upgraded to 1.1.19 version, problem was solved. 

Thanks for your time to help me. 

regards

**Comment by jcesarmobile** [comment]
Thanks for letting me know
