### ISSUE TITLE
Add typing support

### ISSUE THREAD

**Issue by HarelM** [ionic-team/cordova-plugin-ionic-webview#379]
It would be great if you could add a small typescript file to support for typings when using this plugin with typescript.
Mainly the `utils.js` 's `WebView` methods.
Currently my code looks as follows: 
```ts
(window as any).Ionic.WebView.convertFileSrc(...)
```
Using typings I should be able to remove the any and get intellisence for the WebView variable.

**Comment by jcesarmobile** [comment]
We recommend using `@ionic-native/ionic-webview` https://ionicframework.com/docs/native/ionic-webview

**Comment by HarelM** [comment]
I only wanted to install `cordova-plugin-ionic-webview`.
If I install `@ionic-native/ionic-webview` I get all kinds of warnings when running npm install as I don't have the relevant dependencies such as ionic core etc.
Is there a way around it?
