### ISSUE TITLE
Can not display local image on iOS

### ISSUE THREAD

**Issue by APalau82** [ionic-team/cordova-plugin-ionic-webview#385]
> I have the same issue.
> 
> When I use the following it works fine:
> 
> ```
> private win: any = window;
> this.win.Ionic.WebView.convertFileSrc();
> ```

Does not work from my side with webview v4.1.0... 
Still have issue while trying to display a local stored image...

Here is my code

```
private win: any = window;
this.img = this.win.Ionic.WebView.convertFileSrc(LocalString);
```

and on my html file
`<img [src] = "img" />`

Original local url is 
`file:///var/mobile/Containers/Data/Application/BDC18876-12A6-4DB7-A347-9DEF68C502A2/Library/NoCloud/130/130.jpg`

Converted url became 
`ionic://localhost/_app_file_/var/mobile/Containers/Data/Application/BDC18876-12A6-4DB7-A347-9DEF68C502A2/Library/NoCloud/130/130.jpg`

But image is still empty on my device. It does not render...

Anything to see with Content-Security-Policy maybe ?
Mine is
`<meta http-equiv="Content-Security-Policy" content="default-src * data: blob:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval' blob: localhost:*>`

Any help ?

_Originally posted by @APalau82 in https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/193#issuecomment-505864141_

**Comment by jcesarmobile** [comment]
If using angular you have to tell it to trust ionic scheme with dom sanitizer, there is an example in the comments On the other issue you commented

**Comment by ramgrg** [comment]
Isn't it possible through base64?

**Comment by niravtrivedi-youngsoft** [comment]
I have same issue , even I used  dom sanitizer,

original file 

"file:///var/mobile/Containers/Data/Application/7DAAC398-A7CD-40B6-A5EA-824BBE134D8C/Library/NoCloud/1598542461557_cdv_photo_001.jpg"

Converted url

"ionic://localhost/_app_file_/var/mobile/Containers/Data/Application/7DAAC398-A7CD-40B6-A5EA-824BBE134D8C/Library/NoCloud/1598542461557_cdv_photo_001.jpg"

Used dom sanitizer
this.sanitizer.bypassSecurityTrustResourceUrl(this.win.Ionic.WebView.convertFileSrc(path));

(https://user-images.githubusercontent.com/69796718/91467222-efe57500-e8ad-11ea-9ac2-300c5e59b3e7.jpeg)
