### ISSUE TITLE
How use Cordova in Cordova Webview ?

### ISSUE THREAD

**Issue by Seikida** [ionic-team/cordova-plugin-ionic-webview#386]
Hello,

I need your help for my project.

I installed the plugin: Ionic Webview https://ionicframework.com/docs/native/ionic-webview
Documentation is here: https://github.com/ionic-team/cordova-plugin-ionic-webview

Dynamically, I created an HTML page in this directory: this.file.dataDirectory

I try to load this page on the webview like this:

**IMPORT**

`import {WebView} from '@ionic-native/ionic-webview/ngx';`

**CONSTRUCTOR**

`constructor(public webview: WebView) {}`

**MY CODE**

`window.location.href = this.webview.convertFileSrc( this.file.dataDirectory + 'jojo/index.html' );
`

Everything is ok and there aren’t problems. My page jojo/index.html can load.
Now I want to use cordova functions (if possible, I want to use ionic functions)
How can I do that ?

==> Example: when the user click on the #toto button, I want to use the mobile vibration. How can I do that ? (It’s a example of cordova functions)

**Comment by jcesarmobile** [comment]
as long as your index.html has cordova.js properly linked you can use cordova normally.
