### ISSUE TITLE
ERROR: Unhandled Promise rejection: user canceled

### ISSUE THREAD

**Issue by tareqdayya** [ionic-team/cordova-plugin-ionic-webview#387]
Hi, I'm using the safari view controller lately, and it seems that when the user hits 'done' to exit the safari view and get back to the app, the following error is thrown:
`unhandled promise rejection. [Error] Unhandled Promise rejection: – "user canceled" – "; Zone:" – "<root>" – "; Task:" – "Promise.then" – "; Value:" (2) Error: user canceled — index.js:105 "handleClose@http://192.168.1.109:8100/vendor.js:88221:38 http://192.168.1.109:8100/vendor.js:88227:22 http://192.168.1.109:8100/vendor.js:87968:13 callbackFromNative@http://192.168.1.109:8100/cordova.js:288:63 http://192.168.1.109:8100/plugins/cordova-plugin-ionic-webview/src/www/ios/ios-wkwebview-exec.js:129:35 run@http://192.168.1.109:8100/polyfills.js:3029:49 http://192.168.1.109:8100/polyfills.js:3789:37 runTask@http://192.168.1.109:8100/polyfills.js:3074:57 drainMicroTaskQueue@http://192.168.1.109:8100/polyfills.js:3480:42 promiseReactionJob@[native code]" (anonymous function) (consolelogs.js:50)  (anonymous function) (cordova.js:1509)  onUnhandledError (polyfills.js:3582)  handleUnhandledRejection (polyfills.js:3609)  _loop_1 (polyfills.js:3599)  microtaskDrainDone (polyfills.js:3603)  drainMicroTaskQueue (polyfills.js:3487)  promiseReactionJob`

The problem does not arise when the safari view returns to the app on its own; without the user explicitly clicking 'done.' 

Anyway, I did go to the 'ios-wkwebview-exec.js' file and it turns out there is no catch statement chained to the promise on line 129. However, i tried adding it myself, but i still get the error.

I have also tried removing and adding the ios platform but to no avail. 
I Have not tried it on android.

Here's my info:

`Ionic:

   Ionic CLI                     : 5.2.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.5.0
   @angular-devkit/build-angular : 0.800.4
   @angular-devkit/schematics    : 8.0.4
   @angular/cli                  : 8.0.4
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 12 other plugins)

Utility:

   cordova-res : 0.5.1 
   native-run  : 0.2.7 

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.1
   NodeJS     : v10.15.3 (/usr/local/bin/node)
   npm        : 6.9.0
   OS         : macOS Mojave
   Xcode      : Xcode 10.2.1 Build version 10E1001
`

**Comment by jcesarmobile** [comment]
that looks like the safari view controller plugin is sending the canceled error, so you should catch it in your code.

**Comment by evginiy-trusevich** [comment]
Any update ?
