### ISSUE TITLE
_setAlwaysRunsAtForegroundPriority in WkWebview got me a rejected app..

### ISSUE THREAD

**Issue by dickverweij** [ionic-team/cordova-plugin-ionic-webview#389]
I got a rejection from apple.. 

ITMS-90338: Non-public API usage - The app references non-public selectors in XXXXXX:  _setAlwaysRunsAtForegroundPriority:. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. If you think this message was sent in error and that you have only used Apple-published APIs in accordance with the guidelines, send the app's Apple ID, along with detailed information about why you believe the above APIs were incorrectly flagged, to appreview@apple.com.

**Comment by dickverweij** [comment]
possible a duplicate ..

**Comment by dickverweij** [comment]
Is there also a fix for the v2 version of wkwebview?

We are currently at 2.5.1

**Comment by roxteddy** [comment]
Same for me after updating to 4.1.1

**Comment by schnouz** [comment]
same here with latest version of ionic

**Comment by roxteddy** [comment]
I can confirm that downgrading to 4.1.0 made me able to release. Please fix it ;)

**Comment by albalooshi** [comment]
Got this issue on 3.1.2, Fixed after upgrading to 4.1.0.

**Comment by hmudassir** [comment]
I have upgraded to 4.1.0 but still app is rejecting. I am running command on Mac: 
ionic cordova prepare ios --prod

Is there any other command to update / install plugin in ios?

**Comment by sertal70** [comment]
I'm experiencing this too using v2.5.1, it is a very big issue for us because we can't upgrade to v4.1.0 due to iOS compatibility requirement (we need to support iOS 10.3 but 4.1.0 plugin requires 11+).

Any hint/workaround?

**Comment by dickverweij** [comment]
Can we help in a way? We also need the 2.5.1 upgrade ..

**Comment by albalooshi** [comment]
@hmudassir try removing the iOS platform and adding it again using the cli.

**Comment by sertal70** [comment]
Actually the v2.5.1 version of plugin does not reference `_setAlwaysRunsAtForegroundPriority` anymore, so I made a double check on my project and discovered that due to an error the plugin has not been updated to that version. So I removed it and then added the v2.5.1 and now all is working fine, I uploaded the app on the store without any problem.

**Comment by dickverweij** [comment]
Yep I see it also the new source of the plugin was not correctly copied to the platform code.

Mine is working also now.
