### ISSUE TITLE
WkWebView does not allow PUT method in iOS devices using ionic3

### ISSUE THREAD

**Issue by Nikhil-Daffodil** [ionic-team/cordova-plugin-ionic-webview#391]
Earlier I was using UIWebViewEngine in my ionic 3 projects but this was resulting in slow scrolling of list in iOS devices. After going through http://jayantpaliwal.com/2017/07/tips-for-ionic-app-to-perform-better-in-ios/ I changed UIWebViewEngine to WkWebViewEngine, my scrolling issue got fixed, but now a new issue has raised. When performing a PUT request from an iOS device my server is giving "Method PUT is not allowed by access-control-allow-methods" but this is working fine in android device.

When I roll back to UIWebViewEngine, it is working fine but scrolling issue raised again.

Please suggest your solutions. Do we have do configuration in backed OR frontend

**Comment by jcesarmobile** [comment]
WKWebView requires you to properly configure CORS in your server. See https://ionicframework.com/docs/faq/cors
