### ISSUE TITLE
following the steps get an error on iOS 9.3.5 Device

### ISSUE THREAD

**Issue by aycron-dev** [ionic-team/cordova-plugin-ionic-webview#4]
I followed the listed steps but I got an error running the project in a IOS 9.3.5 ipad, but works on IOS 11 emulator.

When I remove the plugin, the app works.

**Comment by manucorporat** [comment]
Hi! @aycron-dev this plugin works for us and a lot of people, please open a new issue providing more information about what is not working and a detailed error message. Thanks. Closed as invalid issue.

**Comment by aycron-dev** [comment]
Ok, I will try to get more info. I opened this quickly because I needed urgently. Sorry for that.
