### ISSUE TITLE
KeyboardDisplayRequiresUserAction is not respected

### ISSUE THREAD

**Issue by heidji** [ionic-team/cordova-plugin-ionic-webview#400]
There seems to have been some discussions and fixes over this problem in the previous deprecated and archived plugin [cordova-plugin-wkwebview-engine ](https://github.com/ionic-team/cordova-plugin-wkwebview-engine) using pull requests that originated from this other deprecated and archived plugin [cordova-plugin-wkwebview-inputfocusfix](https://github.com/onderceylan/cordova-plugin-wkwebview-inputfocusfix), but right here on this new and improved and merged plugin cordova-plugin-ionic-webview this issue seems to live on.

Anyone aware of the fact that input.focus() doesn't work anymore on iOS?

see also #238

**Comment by jcesarmobile** [comment]
On which iOS version? Apple has changed the selector a few times and I think we cover all of them, but one might be missing.

**Comment by heidji** [comment]
i will check later, but i can tell you installing the old inputfocusfix plugin seems to have fixed it for me. problem is it is deprecated so I don't know if it will work next version.

**Comment by heidji** [comment]
[this one ](https://stackoverflow.com/questions/32449870/programmatically-focus-on-a-form-in-a-webview-wkwebview/48623286#48623286)has a fresh update for iOS 13

**Comment by jcesarmobile** [comment]
Yeah, but as iOS 13 is still beta it can change before releasing, so it’s not a priority to fix it at the moment. Let me know if you face the issue on iOS 11 or 12 devices with the exact version

**Comment by heidji** [comment]
ok i'll close it and observe changes later

**Comment by NatiSP** [comment]
This error is happening now in iPadOS 13.4 with cordova-plugin-ionic-webview 4.1.3. 

Not sure what is happening or if a workaround could be possible for this, but it doesn't happens if I use [cordova-plugin-wkwebview-engine](https://github.com/apache/cordova-plugin-wkwebview-engine)

**Comment by heidji** [comment]
I'm using my own plugin because for some reason this plugin doesn't do it for me. if you want to try my package here it is:
`"cordova-plugin-wkwebview-inputfocusfixx": "0.0.3"`
