### ISSUE TITLE
Toolbar and cursor incorrect behaviour

### ISSUE THREAD

**Issue by vg0x01** [ionic-team/cordova-plugin-ionic-webview#404]
currently using cordova plugins:
```
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.1 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
```

I am using ionic webview for xhr and ionic keyboard for a non-ionic app.

i've attached a video below showing the cursor still being available on scroll and the toolbar being shown above the keyboard.

Is there any way to fix this? Ideally i want the toolbar to not be shown when the keyboard is visible, the cursor to hide on scroll, and the keyboard to hide when scrolling, like native ios behaviour.

[video](https://www.youtube.com/watch?v=SDUJePKALIU)

**Comment by jcesarmobile** [comment]
You can listen for the keyboard events and show/hide whatever you need.
This is a bug in the webview and only Apple can fix it. Some frameworks can provide workarounds, I think Ionic 4 hides the cursor when the app is scrolling to not show this kind of problems, but as you are not using Ionic you'll have to handle it yourself.
