### ISSUE TITLE
Apple Connect Upload: Non-public API Usage Error

### ISSUE THREAD

**Issue by MeterMoDev** [ionic-team/cordova-plugin-ionic-webview#407]
When trying to upload a new iOS build of our app, I am getting the following error email, which is preventing the app from being uploaded successfully:

> We identified one or more issues with a recent delivery for your app, "(Appname)" 2.0.20 (2.0.20). Please correct the following issues, then upload again.
> 
> ITMS-90338: Non-public API usage - The app references non-public selectors in (Appname): _setAlwaysRunsAtForegroundPriority:, databasePool:didAddDatabase:, databasePool:shouldAddDatabaseToPool:, ddSetLogLevel:. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. If you think this message was sent in error and that you have only used Apple-published APIs in accordance with the guidelines, send the app's Apple ID, along with detailed information about why you believe the above APIs were incorrectly flagged, to appreview@apple.com. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/

And the only references to them, is in FMDB.

I don't want to remove the lines referencing it because I have no idea what it would affect.

Thanks in advance.

**Comment by jcesarmobile** [comment]
Not sure what FMDB, but if the references are there why do you report it here?

**Comment by MeterMoDev** [comment]
> Not sure what FMDB is, but if the references are there why do you report it here?

Apologies, had many tabs open. Not sure how to delete this.

**Comment by jcesarmobile** [comment]
No problem, I can close it.
