### ISSUE TITLE
version 4.x and recaptcha on iOS

### ISSUE THREAD

**Issue by captaincaius** [ionic-team/cordova-plugin-ionic-webview#408]
Hi.

It seems that version 4 doesn't work well with recaptcha anymore on iOS - An error comes back saying "Cannot contact reCAPTCHA. Check your connection and try again.".  I'm not positive exactly when it happened, but android seems to still work fine.

Recaptcha flavor: invisible v2

I'm suspicious of the ionic:// thing but that's just cause I never saw any kind of explanation of where that came from or why.

**Comment by jcesarmobile** [comment]
It came from removing the local web server as it was insecure, so the only way of loading local resources was to use file:// scheme as the cordova-plugin-webview-engine does or use a custom scheme as we did:
https://ionic.zendesk.com/hc/en-us/articles/360015176994-2019-01-03-Security-Alert-for-cordova-plugin-ionic-webview

Hard to know what's going on without a sample app, but it's probably some CORS issue, not sure if that's something you can configure on reCAPTCHA.

**Comment by captaincaius** [comment]
well recaptcha only provides a "domains" setting, and localhost is already there (hence android already working).

Trying to forcefully put ionic://localhost says this:

The following domains are invalid: ionic://localhost. A valid domain requires a host and must not include any protocol, path, port, query or fragment.

So it would seem it's not possible.  I read somewhere else about the httpsionic:// hack - has anyone confirmed that this works for recaptcha?

**Comment by captaincaius** [comment]
so good news for anyone trying to get recaptcha working in the future - I'm not positive exactly how much of this is needed, but I can confirm that I finally got it working with the following things:

1. iosScheme set to httpsionic along with having "localhost" in the recaptcha domains setting
2. <access origin="http://*.google.com" allows-arbitrary-loads-in-media='true' allows-arbitrary-loads-in-web-content='true' allows-local-networking='true' /> - you may want to limit this further.
3. <allow-intent href="https://*.google.com/*"/>
4. NSAppTransportSecurity - you'll have to look up exactly how to do this depending on your setup.

Note that none of these seemed to be necessary for android with this plugin, so don't let android working give you a false sense of security ;).

Closing this.

**Comment by dodomui** [comment]
I'm still having the same cors issue for recaptcha IOS.
@captaincaius May I know how to do with point 4?
I applied point 1 to point 3, but still unable to make recaptcha work under IOS

**Comment by RohitBattepati** [comment]
@captaincaius  
I did apply points 1 -3 but couldn't get recaptcha working under iOS. Do you have any changes to your post? 

@dodomui did you get captcha working under iOS?
