### ISSUE TITLE
CodePush live updates get silently uninstalled the next time the app is launched

### ISSUE THREAD

**Issue by gabriele-sacchi** [ionic-team/cordova-plugin-ionic-webview#409]
It looks like using this plugin in a Cordova project causes loss of CodePush live updates.

The CodePush update gets correctly installed but all updates are gone when the app is hard closed and re-launched.

This issue occurs only on iOS.

Issue on CodePush github: https://stackoverflow.com/questions/57318219/cordova-plugin-codepush-updates-lost-after-relaunching-the-ios-app

PS. The Issue seems to be **CORS** related. This would be solved if this plugin **allowed to use the `https` scheme for iOS too** (it currently works only for Android).

**Comment by jcesarmobile** [comment]
Closing as on the linked SO question you comment that you solved it by using a fork of the code push plugin, so it was a problem in their end.

**Comment by hooliy** [comment]
try add <script src="cordova.js"></script> in index.html file
