### ISSUE TITLE
Service worker (workbox) with android webview error

### ISSUE THREAD

**Issue by JohnRSim** [ionic-team/cordova-plugin-ionic-webview#410]
Not sure if this is the same -
https://bugs.chromium.org/p/chromium/issues/detail?id=977784

I get the following error in the browser console - 

```
An unknown error occurred when fetching the script.
(index):1 Uncaught (in promise) TypeError: Failed to register a ServiceWorker: An unknown error occurred when fetching the script.
```

This works fine from the browser using localhost

config.xml
```xml
        <preference name="Hostname" value="test" />
        <preference name="Scheme" value="https" />
```

index.html
```html
<script>
if (('serviceWorker' in navigator) && (window.location.href.indexOf('file://') <= 0)) {
	  // Use the window load event to keep the page load performant
	  window.addEventListener('load', () => {
		navigator.serviceWorker.register('sw2.js');
	  });
}
</script>
```

sw2.js
```javascript
importScripts("workbox-v4.3.1/workbox-sw.js");
workbox.setConfig({modulePathPrefix: "workbox-v4.3.1"});

workbox.core.setCacheNameDetails({prefix: "smartr-cache"});

workbox.core.skipWaiting();

workbox.core.clientsClaim();

/**
 * The workboxSW.precacheAndRoute() method efficiently caches and responds to
 * requests for URLs in the manifest.
 * See https://goo.gl/S9QRab
 */
self.__precacheManifest = [
  {
    "url": "js/appConfig.js",
    "revision": "0aa8bda62dc6167427c992a9dc82bb53"
  },
  {
    "url": "js/appConfigExternal.json",
    "revision": "8f2d9e22d885f3af63b4c56e1abb6717"
  },
  {
    "url": "js/appController.js",
    "revision": "8d25c1032f1b9d0f0c16148ab74381a3"
  },
  {
    "url": "js/cordovaMocks.js",
    "revision": "28660184e9244efec9986d56fdb26b31"
  },
  {
    "url": "js/jet.js",
    "revision": "448bda08ee98cbbac4592dd974f96936"
  }
].concat(self.__precacheManifest || []);
workbox.precaching.precacheAndRoute(self.__precacheManifest, {});

workbox.precaching.cleanupOutdatedCaches();

workbox.routing.registerRoute(/^https:\/\/mydomain.com/, new workbox.strategies.StaleWhileRevalidate({ "cacheName":"mytest-images-uat", plugins: [new workbox.cacheableResponse.Plugin({ statuses: [ 0, 200 ] })] }), 'GET');
```

If you want I can create a basic example and source of clean cordova / ionic project.

Thanks

**Comment by JohnRSim** [comment]
Service worker appears not to have access to the ionic webview webserver and domains setup in config.xml

```
navigator.serviceWorker.register('sw2.js');
```
tries to access https://test/sw2.js externally.
if I update config.xml to 

```xml
        <preference name="Hostname" value="mydomain.com" />
        <preference name="Scheme" value="https" />
```

and upload sw2.js to mydomain.com the service worker initialises now however it can only access and see content on mydomain.com on the webserver and not https://mydomain.com setup within the ionic webview. And so does not precache the assets required.

However it can now use service workers in the cordova app and use runtime caching and cache the assets requested from mydomain.com (server) or another external domain.

**Comment by JohnRSim** [comment]
I've also tried swapping to the latest chrome canary webview encase it was an issue specific to the version of chrome running as a webview - But I think this issue needs to be handled by ionic to somehow let the service worker interact with the webserver setup within the app.

![Screenshot_20190802-155725_Settings](https://user-images.githubusercontent.com/364208/62382409-64cc6b00-b545-11e9-9da4-fb892837f174.jpg)

**Comment by JohnRSim** [comment]
So maybe something like this to intercept the request of the service worker? 

```java
ServiceWorkerController controller = null;
        if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.N) {
            controller = ServiceWorkerController.getInstance();
            controller.setServiceWorkerClient(new ServiceWorkerClient(){
                @Nullable
                @Override
                public WebResourceResponse shouldInterceptRequest(WebResourceRequest request) {
                    return super.shouldInterceptRequest(request);
                }
            });
        }
```

**Comment by WebeWizard** [comment]
For those of us that just arrived from a search engine...
This functionality must be turned on in config.xml
```<preference name="ResolveServiceWorkerRequests" value="true" />```
