### ISSUE TITLE
Web view doesn't works for the first time in Ionic app and gives CORS error for service calls.

### ISSUE THREAD

**Issue by akrkar26** [ionic-team/cordova-plugin-ionic-webview#412]
Hi,
I am using Ionic3.
After Chrome 76 update, first time calls  to servers are giving CORS error and it works perfectly after closing app and reopening it.

Something from Chrome 76 update has broken webview first time launch.
If anyone knows the solution then plz help

**Comment by jh-gh** [comment]
Looks like Google has done a fix for this ...
https://bugs.chromium.org/p/chromium/issues/detail?id=991107

**Comment by jcesarmobile** [comment]
Are you using 2.x of the plugin or newer?

Starting on 2.x, this plugin uses `http://` instead of `file://`, so I don't think that bug should affect apps using this plugin.

**Comment by akrkar26** [comment]
Now it works with google chrome update. So closing the issue.
