### ISSUE TITLE
Add support for inspecting on iOS 12.3+ devices via IWDP

### ISSUE THREAD

**Issue by ruslan-bikkinin** [ionic-team/cordova-plugin-ionic-webview#417]
Currently, Ionic Web View doesn't support inspecting on iOS 12.3+ devices via [IWDP](https://github.com/google/ios-webkit-debug-proxy) though latest Cordova web view do support it. It breaks Ionic apps debugging on those devices on [Cordova Tools](https://github.com/Microsoft/vscode-cordova) extension for VS Code.
Additional information can be found in the related Issue in ionic repo: https://github.com/ionic-team/ionic/issues/18733

**Comment by jcesarmobile** [comment]
We don't do anything to prevent it, so not sure how this is an issue on our side.
What would be required to make it work?

**Comment by iamkarlson** [comment]
Guys, it's real pain in the ass. What do you need to move things forward?
