### ISSUE TITLE
Support IOS 10

### ISSUE THREAD

**Issue by dodomui** [ionic-team/cordova-plugin-ionic-webview#418]
cordova-plugin-ionic-webview 4 come default with ionic 4 project

But due to cordova-plugin-ionic-webview 4 can support minimum IOS 11 only and it make ionic 4 project seem cannot support Ionic 10 and below.

1. May I know is it possible to build Ionic 4 without this plugin?
2. What's the possible issue if skip this plugin?
3. Can I use cordova-plugin-ionic-webview version 2 plugin instead with Ionic 4?
So Ionic 4 can work down to IOS 8? Or minimum is IOS 10?

Thanks a lot for any expert advise.

**Comment by dylanvdmerwe** [comment]
Use version [2.x](https://github.com/ionic-team/cordova-plugin-ionic-webview/blob/2.x/README.md) of this plugin.

**Comment by dodomui** [comment]
Yes, I did tried downgrade to version 2.5.1
Version 2.x required iOS 10 and above?

**Comment by jcesarmobile** [comment]
4.x supports iOS 11 and newer
2.x supports iOS 10 and newer.

At this point, according to [Apple stats](https://developer.apple.com/support/app-store/), "earlier" (meaning iOS 10 and earlier) are only 5% of the market.
Even cordova-ios doesn't support iOS 9 and older anymore.
