### ISSUE TITLE
Should I use this together with crosswalk for KitKat support?

### ISSUE THREAD

**Issue by dmastag** [ionic-team/cordova-plugin-ionic-webview#420]
KitKat support has been added in version 2.2.0 but I cannot find any documentation if I still need crosswalk on KitKat.

In my current CI my setup is like this:
- crosswalk + cordova-plugin-ionic-webview build for API 19
- cordova-plugin-ionic-webview build for API 21+

**Comment by jcesarmobile** [comment]
If you use crosswalk I don't think this plugin will work, as you can only have one engine, the crosswalk one or this one, but not both nor use crosswalk for Android 4.4 and this one for the rest.

But if you have managed to use crosswalk on kit kat, then not sure what your concern is.

This plugin uses the system webview, so on Android 4.4 devices is old, but as crosswalk is deprecated is not up to date neither.

**Comment by dmastag** [comment]
Thanks @jcesarmobile for the explanation.
So I will remove crosswalk and use this only.
