### ISSUE TITLE
webrtc: getUserMedia not working

### ISSUE THREAD

**Issue by GlausLivio** [ionic-team/cordova-plugin-ionic-webview#424]
I tried to implement video call using webrtc, it is working well on Android, iOS browsers. (ios Safari, too).
but It is not working on iOS wkwebview.
Do you have any plan to support webrtc?
I am now using iosrtc plugin, but it is too old. I dont want to use it in the future.
Hope to get your opinion. 
thanks.

**Comment by jcesarmobile** [comment]
WKWebView doesn't have it implemented, there is nothing we can do about it.
