### ISSUE TITLE
[Android] Viewport Not Properly Resized When <ion-content> contains a fixed element

### ISSUE THREAD

**Issue by bryplano** [ionic-team/cordova-plugin-ionic-webview#425]
## Description

When an `<ion-content>` element contains an element that has `position: fixed` (and some additional CSS to specify location) in an Ionic app, the viewport does not properly resize on Android when the keyboard is brought up. 

This can lead to situations where elements are available on iOS but not on Android.

## Current Behavior

The viewport does not resize appropriately on Android, making it impossible to access certain elements on the screen beneath the keyboard.

### Sample Repo

https://github.com/bryplano/viewportAndroidProblem

### Repro Steps
**Best to run the application on a physical device**

Devices & OS versions for testing:
- Pixel 2 / Android 9 (issue occurs)
- Nexus 6P / Android 8 (issue occurs)
- iPhone XS Max / iOS 13 Beta 7 (issue does not occur)

1. Download the sample application, unzip and nav to root directory
2. Install deps (`npm i`) and run on device using `ionic cordova run <platform> --device`

**Android - Reproducing the issue**
1. Scroll down to the bottom (in my video, I have placed a simple `<p>bottom</p>` to visually denote where the bottom of the screen lies)
2. Notice you can scroll all the way to the bottom and reach the last element
3. Now tap on any of the inputs on the screen
4. With the keyboard up, attempt to scroll up or down
5. Notice that the viewport does not resize appropriately, preventing the user from scrolling to the bottom of the screen and preventing them from accessing any elements underneath the keyboard
6. *Important Note*: Also try moving the screen into landscape mode while the keyboard is up. The keyboard will dismiss, but the viewport will still not resize appropriately, preventing proper scrolling and access to other elements that should be available (this is why we believe the issue may lie with the webview (viewport) and not the keyboard)

See attached ZIP (apologies for the poor quality) to see the issue: [android_recording.mov.zip](https://github.com/ionic-team/cordova-plugin-ionic-webview/files/3546465/android_recording.mov.zip)

## Expected Behavior

The viewport should resize and allow the user to scroll all the way up and down on Android.

**iOS - Appropriate Behavior**
1. Follow the same instructions as Android (above) until Step 5
2. Notice (as of Step 5) that the viewport resizes, allowing the user to scroll down to at least the bottom element (landscape also works, not shown in the recording)

[ios_recording.mov.zip](https://github.com/ionic-team/cordova-plugin-ionic-webview/files/3546470/ios_recording.mov.zip)

## Environment

**ionic info**

```
Ionic:

   Ionic CLI                     : 5.2.6 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.7.4
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.3 (cordova-lib@9.0.2)
   Cordova Platforms : android 8.0.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 4 other plugins)

Utility:

   cordova-res : 0.6.0 
   native-run  : 0.2.8 

System:

   Android SDK Tools : 26.1.1
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.1
   NodeJS            : v10.16.1 (/usr/local/bin/node)
   npm               : 6.9.0
   OS                : macOS Catalina
   Xcode             : Xcode 10.3 Build version 10G8
```

**Comment by jcesarmobile** [comment]
This is a chrome 76 bug, it's been reported already on their tracker https://bugs.chromium.org/p/chromium/issues/detail?id=994807

This workaround seems to work
https://github.com/ionic-team/ionic/issues/19065#issuecomment-523423118
