### ISSUE TITLE
Android, 4.4.1 using custom scheme prepends hostname twice

### ISSUE THREAD

**Issue by Yuripetusko** [ionic-team/cordova-plugin-ionic-webview#426]
Using custom Scheme on android adds hostname 2 times

Given following settings
```
<preference name="Scheme" value="ionic" />
<preference name="Hostname" value="app" />
```

My app would start with following URL: `ionic://app/app/`

**Comment by jcesarmobile** [comment]
I can't reproduce on my 4.4.4 device or on any newer device.
Can you provide sample app? I don't think this is a bug on the plugin.

**Comment by Yuripetusko** [comment]
Closing because I switched to 2.5.1 version as I had separate set of problems on ios when accessing some web services
