### ISSUE TITLE
iOS Deprecated API Usage Warning

### ISSUE THREAD

**Issue by slymeng** [ionic-team/cordova-plugin-ionic-webview#428]
Just submitted my app to TestFlight and got an email with the error:

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

I  got this error, when use ionic( 4.12.0), while I am not using UIWebview in my application at all. 

Here are some main configuration information
package.json
"cordova-plugin-ionic-webview": "^4.0.1",

config.xml
<preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />

**Comment by eun-choi** [comment]
Same as version 4.1.1

**Comment by jcesarmobile** [comment]
First of all, that's a warning, not an error.

This is a problem on cordova-ios as even if you use WKWebView as this plugin does, the cordova code is also sent for review and that confuses Apple.

It's already reported in cordova-ios repo.
https://github.com/apache/cordova-ios/issues/661

**Comment by BrutussMaximus** [comment]
Same thing happening to me here since today.
i have removed all the things that could have the webview involved (inappbrowser, themeablebrowser, ....) and i´ve upgraded the cordova-webview to the latest version and i still get the error from apple.

**Comment by jcesarmobile** [comment]
I repeat, it’s a warning, not an error. And it’s in cordova-ios

**Comment by BrutussMaximus** [comment]
Like @nielsjakob said:

> UIWebView has been deprecated for well over a year though, so I fear the "long time" is coming to an end very soon. So I'd second that this is a rather urgent issue.
> 
> Here's a Twitter thread from one Apple dev on the topic:
> https://twitter.com/NiklasMaerz/status/1167031874738434048
