### ISSUE TITLE
ITMS-90809: Deprecated API Usage

### ISSUE THREAD

**Issue by desmeit** [ionic-team/cordova-plugin-ionic-webview#431]
I get this warning:

`ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs`

In another thread you told that it is just a warning. does the app then have Webview or UIWebView? Can I ignore this warning? Or am I gonna be rejected by Apple?

**Comment by jcesarmobile** [comment]
You can ignore it for now.
It has to be fixed in cordova-ios, there are a few PRs already with possible fixes, it's being discussed here https://github.com/apache/cordova-discuss/pull/110
