### ISSUE TITLE
Trying to inject <script> tag in header is not working

### ISSUE THREAD

**Issue by Perh0rd** [ionic-team/cordova-plugin-ionic-webview#434]
Hi,

We are trying to use this plugin to migrate UIWebView.

However, just doing a simple thing like that : 
 $("head").prepend('<script src="https://externalscript.com"></script>');

It's just not working.

If We put the tag in the index.html, it is working ...

Any idea?

Thank you.

**Comment by UniBrowse** [comment]
Hey @Perh0rd, Did you ever get feedback on this?
