### ISSUE TITLE
Focus doesn't open keyboard on iOS 13

### ISSUE THREAD

**Issue by yosikal** [ionic-team/cordova-plugin-ionic-webview#435]
Calling element.focus() on text element doesn't open keyboard on iOS 13. This is working fine on iOS versions < 13

**Comment by gregavola** [comment]
The solution is here: https://stackoverflow.com/questions/32449870/programmatically-focus-on-a-form-in-a-webview-wkwebview/48623286#48623286

**Comment by kevinswartz** [comment]
Any chance this is getting merged in?  I'm seeing this as well on cordova-plugin-ionic-webview@4.1.1
Thanks!
