### ISSUE TITLE
Web Sql isn't working on iOs 13

### ISSUE THREAD

**Issue by mlazic** [ionic-team/cordova-plugin-ionic-webview#443]
Hi,

Does anyone know what could be reason why I am getting white screen on iOs 13 devices after installation of this plugin ?

I know Web Sql (sqllite) is deprecated in iOs 13 but does anyone of you using db on your apps ?

Regards,
Marko Lazic

**Comment by i3i2ain** [comment]
I am using WebSql in an old Ionic V1 app and I can confirm that my app stopped working after installing ios 13 i.e. safari 13. I could made the "browser version" work in mobile safari (v. 13) after switching off in ios settings -> advanced --> experimental feature --> "disable web sql"
But sadly this did not help with the "native" App which crashes with 

`Error: Web SQL is deprecated
openDatabase@[native code]`
