### ISSUE TITLE
Deprecated API Usage : UIWebView

### ISSUE THREAD

**Issue by praveen5exceptions** [ionic-team/cordova-plugin-ionic-webview#445]
I have updated plugin to latest version but still getting this warning from apple on submission.

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

Versions:
Ionic : 4+
cordova-plugin-ionic-webview : 4.1.2

**Comment by ezimmert** [comment]
Same here...

**Comment by jcesarmobile** [comment]
See #431

But, it's a warning, so you shouldn't worry for now.
The only final solution for now is moving your app to Capacitor
If you want to continue using Cordova, there are two cordova-ios forks with two different approaches that you can use instead of the original.
