### ISSUE TITLE
Native plugins failing when I use custom hostname preference for cordova-plugin-ionic-webview

### ISSUE THREAD

**Issue by shivarajnaidu** [ionic-team/cordova-plugin-ionic-webview#446]
I am using `ionic cli` version  `5.4.1` and  **`"cordova-plugin-ionic-webview": "^4.1.2"`** 

**Problem :** When i set custom hostname for webview my native plugins not working. Tested with barcode scanner plugin (Attached the code).

**Steps To Reproduce:** 
[1] Create new cli project and add barcodescanner plugin and test it (It will work as expected)
[2] Then install webview plugin and change the preference value in **_config.xml_** file
like so  **`<preference name="Hostname" value="yuvaraj-app" />`**
[3] Now test the barcode scanner (It will not work - you will see the scan in progress message but no camera will apear)

**Please check the attached source code to test the above scenario* - -Thank You !*

![Selection_005](https://user-images.githubusercontent.com/12374494/65872272-da19b800-e39d-11e9-8e19-a3462d2498b7.png)

[myApp.zip](https://github.com/ionic-team/cordova-plugin-ionic-webview/files/3670499/myApp.zip)

**Comment by jcesarmobile** [comment]
See the [Hostname docs](https://github.com/ionic-team/cordova-plugin-ionic-webview#hostname):

> If you change it, you'll need to add a new allow-navigation entry in the config.xml for the configured url (i.e <allow-navigation href="http://app/*"/> if Hostname is set to app). This is only needed for the Android url when using http://, https:// or a custom scheme. All ionic:// urls are whitelisted by the plugin.

Your app is missing the allow-navigation entry for your hostname in config.xml, just add it 
`<allow-navigation href="http://yuvaraj-app/"/>`

**Comment by shivarajnaidu** [comment]
It works,
Thank You For Your Quick Response  @jcesarmobile :)
