### ISSUE TITLE
The input tag cursor is not displayed on iOS 13

### ISSUE THREAD

**Issue by nrikiji** [ionic-team/cordova-plugin-ionic-webview#449]
The input tag cursor（blue color caret） is not displayed on iOS 13.
It seems to work correctly if you remove the plugin.

plugin version is 4.1.2
try iPhoneSE Simulator（iOS13.0）.
iOS 12 now behaves as expected.

no use plugin
![not_use_plugin](https://user-images.githubusercontent.com/4780752/66016536-00f8fb00-e512-11e9-88be-0c5f7d56a65c.gif)

use plugin
![use_plugin](https://user-images.githubusercontent.com/4780752/66016541-05bdaf00-e512-11e9-8a18-565e8670d233.gif)

Is this a bug?

**Comment by stepankouba** [comment]
+1, the same problem. Any ideas?

**Comment by daniellyqueiroz** [comment]
+1, does anyone have any solution?

**Comment by kennethwwu** [comment]
same issue here, the cursor disappeared when a input need to be push up bu the keyboard

**Comment by mittermayr** [comment]
I have remove all the styles, anything at all from the very root of the body all the way up to the input to make sure it's not a framework or CSS thing interfering. I am running a ReactJS app inside Cordova, and the input field behaves exactly like shown above in the second video. Cursor is invisible. I had (have?) a suspicious this may relate to controlled elements in ReactJS, but if other people have the same problem without React, then it'll probably something else.

**Comment by chriswep** [comment]
i reported the same issue (afaik) on the main ionic repo: https://github.com/ionic-team/ionic/issues/19556

it's either a bug in iOS 13 or in the ionic webview implementation. however i'm using capacitor and not this plugin, so i rather suspect an issue with iOS 13. ionic might have some shared code though thats used both in capacitor and this plugin.

**Comment by daniellyqueiroz** [comment]
Include "position: fixed" no functional element for me.

**Comment by stepankouba** [comment]
I'm investigating the issue. It happens to me, when using ion-slides. If there is just one ion-slide within the parent, the cursor is visible. Once I put another ion-slide before, it disappears.

**Comment by estacks** [comment]
This happens on any kind of text input that gets moved. ion-slides, the input getting pushed up by the keyboard, etc. You can focus an input and then drag the page around, the cursor and highlighted text won't move at all.

I was able to triage this problem by creating a directive that makes a text input modal pop up whenever focus is given to the problem fields. Modals don't actually appear to have any of these problems.

**Comment by stepankouba** [comment]
In my case adding `position: fixed !important;` for all the input tags (input and textarea) fixes the caret problem. It seems easier for me to slightly modify the css of the ion-slides to handle fixed position properly, than to find a different solution.

**Comment by chriswep** [comment]
> In my case adding `position: fixed !important;` for all the input tags (input and textarea) fixes the caret problem. It seems easier for me to slightly modify the css of the ion-slides to handle fixed position properly, than to find a different solution.

that's what i did as well. At least for me, to make this work properly i had to 
- add a fixed width to the `input` element
- add a height to the surrounding `ion-input` element
- define all that via `global.scss` (or a file that is imported by it), not on component level

**Comment by sjoerdvanhal** [comment]
> > In my case adding `position: fixed !important;` for all the input tags (input and textarea) fixes the caret problem. It seems easier for me to slightly modify the css of the ion-slides to handle fixed position properly, than to find a different solution.
> 
> that's what i did as well. At least for me, to make this work properly i had to
> 
> * add a fixed width to the `input` element
> * add a height to the surrounding `ion-input` element
> * define all that via `global.scss` (or a file that is imported by it), not on component level

I also use this fix. Because it is only for iOs I place the styling inside the following code:

@supports (-webkit-overflow-scrolling: touch) {
}

I have also added a custom class to the ion-item: "ios-textarea". My code:
`<ion-item class="ios-textarea">
            <ion-textarea rows="7" placeholder="X" formControlName="body">
            </ion-textarea>
        </ion-item>`

`@supports (-webkit-overflow-scrolling: touch) {
    .ios-textarea {
        height: 240px !important;

        .item-native {
            height: 240px !important;
        }
    }

    ion-slide {
        textarea {
            position: fixed !important;
            width: 80% !important;
            height: 230px;
        }
    }
}
`

**Comment by lufengd3** [comment]
check your input style, remove `user-select: none`

**Comment by ayjee** [comment]
I experienced a similar issue recently with a custom slideout component (not using ionic) after updating to iOS13.  I was positioning the slideout component offscreen initially with `left: 100%`.  Once I changed the left value to `0` and used `transform: translateX(...)` the cursor began to show up again.

**Comment by nrikiji** [comment]
It may have been fixed after updating to iOS13.2...

**Comment by Adza93** [comment]
> It may have been fixed after updating to iOS13.2...
> Can I fix it?

I confirm the problem had been fixed with iOS 13.2, checked just now :)

**Comment by noxiousmobile** [comment]
Yes it's fixed in iOS 13.2, so looks like it was apple thing.

**Comment by nrikiji** [comment]
However, xcode11.2 is not published in the appstore ...

**Comment by noxiousmobile** [comment]
> However, xcode11.2 is not published in the appstore ...

You can still download 11.2 beta from http://developer.apple.com. I just did.

**Comment by nrikiji** [comment]
I want to put the regular version.
However, because there is no space in the PC capacity, you can not put two xcode...

**Comment by meetdoshi1** [comment]
It's happening in ios 13.2.3

**Comment by nrikiji** [comment]
It doesn't seem to reproduce in my developed app.

**Comment by Adza93** [comment]
I also confirm this bug is not happening anymore (tested on iOS 13.2.2).
@meetdoshi1  are you sure you are testing on right iOS version?

**Comment by tinn2015** [comment]
Same Problem (IOS 13.1.3)

**Comment by Adza93** [comment]
Damn Apple.......

**Comment by meetdoshi1** [comment]
It's not happening in this repository.
I am using webview editor (richEdtorview), It's happening in my code.
if you know why it's happening, can you help me please?

**Comment by lentyaishe** [comment]
Well guys, you would never believe the workaround I used to make this weird behavior disappear.
Unfortunately the proposed `position: fixed;` on `<input>` itself or its parent did not solve the case for me.
The idea came from [this post](https://forum.ionicframework.com/t/wrong-position-of-cursor-after-scroll-with-opened-keyboard/3424/14) so the solution would be (in my case in Angular/Typescript):
```
const scrollBy: number = this.$ionicScrollDelegate.getScrollPosition().top === 0 ? 1 : -1;
const focusedElement: HTMLInputElement = <HTMLInputElement>this.$window.document.activeElement;
this.$ionicScrollDelegate.scrollBy(0, scrollBy, false);
this.$ionicScrollDelegate.scrollBy(0, (-1 * scrollBy), false);
focusedElement.disabled = true;
this.$timeout(() => {
       focusedElement.disabled = false;
}, 300);
```
What actually this thing does is making the ionic scroll the page by 1 pixel up or down and then back and using the linked solution for re-positioning the caret.
Hope it helps anyone.

**Comment by jcaron23** [comment]
I'm still facing a similar issue on 13.2.3 with a texture. The trick above did not work for me, but:

    document.activeElement.selectionStart = document.activeElement.selectionStart

after a 400 ms timeout did. Hope that helps.

**Comment by Shneeball** [comment]
Seems to be happening for me on iOS 13.3 are we sure this was an Apple issue?
