### ISSUE TITLE
How to set to True the "setWebContentsDebuggingEnabled" property on the android.webkit.WebView element

### ISSUE THREAD

**Issue by Devapal** [ionic-team/cordova-plugin-ionic-webview#458]
How do I enable WebView for a Cordova Mobile App (Hybrid). Is there a setting in project files that enables the WebView ? Please advise.

I am trying to get context handles for this Hybrid Mobile App ( Cordova ) and I see only native. I need to be able to get WebView to interact with the mobile elements for UI testing using Appium.

From the documentation, I can see that the method setWebContentsDebuggingEnabled is accountable for debugging web contents and is default set to false. How do I set this to true for a Cordova Mobile App (hybrid) project ?

Further More: In my case, It is necessary to set to true the setWebContentsDebuggingEnabled property on the android.webkit.WebView element. How can I set this ?

Source: appium.io/docs/en/writing-running-appium/web/hybrid

**Comment by jcesarmobile** [comment]
It's set to true by cordova-android as long as the app is debugable (i.e. run from Android Studio or Cordova CLI)
https://github.com/apache/cordova-android/blob/master/framework/src/org/apache/cordova/engine/SystemWebViewEngine.java#L226
