### ISSUE TITLE
retrieving static files for certain paths fails with os x 10.15 with xcode 11 

### ISSUE THREAD

**Issue by daniellizik** [ionic-team/cordova-plugin-ionic-webview#460]
**environment:**

- os x 10.15
- xcode 11
- cordova 8.0.0
- cordova-plugin-ionic-webview 2.3.2

**behavior:**

Building/bundling the app works, but at runtime any static files that are located in
```
AppData/Library/files/data/assets
```
cannot be found and a 404 is returned.

However, files located in
```
AppData/Library/files/data/scripts
```
can be loaded just fine.

**Example**

bundled folder structure
```
AppData/
  Library/
    files/
      data/
        assets/
          vendor.js
          bundle.js
        scripts/
          index.js
```
html
```html
<!-- works fine -->
<script src="index.js" />

<!-- returns 404 -->
<script src="/../assets/vendor.js" />

<!-- returns 404 -->
<script src="localhost:8080/var/mobile/Containers/Data/Application/<id>/Library/files/data/assets/vendor.js" />
```
The exact same file structure works fine when I was building with the following:

- os x 10.13
- xcode 10
- cordova 8.0.0
- cordova-plugin-ionic-webview 2.3.2

I'm having difficulty tracking down which library this problem is originating from. Any help is appreciated.

**Comment by jcesarmobile** [comment]
can you provide a sample project where it can be reproduced?

**Comment by daniellizik** [comment]
no sorry, fixed the issue though. I just needed to use `window.Ionic.WebView.convertFileSrc` after cordova appended the correct build id to the url
