### ISSUE TITLE
WKSuspendInBackground=false breaks IndexedDB

### ISSUE THREAD

**Issue by kolbasa** [ionic-team/cordova-plugin-ionic-webview#461]
Environment:
* iPhone 7, iOS 13.1.2
* cordova: 9.0.0
* cordova-ios: 5.0.1

I updated ionic-webview from 4.0.1 to 4.1.2. 
If I suspend the app for 30 seconds (or more) with this version and the `WKSuspendInBackground`-flag set to `false`, the database will not work anymore.
It just disappears. This can be reproduced at any time.

Reloading the WebView does not help. The whole app has to be restarted.

---

Screenshot of Safaris Device Inspector before suspend:
(Indizierte Datenbanken := IndexedDB)
![before](https://user-images.githubusercontent.com/3901582/67683340-85b02b00-f991-11e9-86df-d1c1939fa447.png)

After suspend:
![after](https://user-images.githubusercontent.com/3901582/67683358-8b0d7580-f991-11e9-8efe-cc2566f5001a.png)

**Comment by samunit** [comment]
Hey, we are experiencing the same issue as well in one of our applications. Removed the property in config.xml and the app is now working as it used to.

**Comment by ghenry22** [comment]
I have come across this before, there is actually a bug open against webkit for this behaviour, it's not specific to this plugin.  I would suggest that you try prefering localstorage if you running as a PWA or using the sqlite storage engine if you are running as mobile app instead.  These both behave consistently even after the app has been backgrounded or suspended.

**Comment by kolbasa** [comment]
Thanks for the suggestion. That is consistent with my experience.
I have migrated the data of my users to SQLite.
This has proven to be very stable.
The only downside was that the app size grew by about 3 megabytes just to integrate the plugin.
If someone reads this: avoid using IndexedDB.
I'm closing this issue.
