### ISSUE TITLE
Can someone pls help better explain Migration to 4?

### ISSUE THREAD

**Issue by tryhardest** [ionic-team/cordova-plugin-ionic-webview#462]
Sorry we are finding these docs a bit technical and hard to navigate. We are migrating from 2.x to 4.1.1 and not understand the process. We do not use Ionic so not wanting;

Apps are now served from ionic:// scheme on iOS by default.

Is this only if we are using a custom scheme and hostname?
----
The default origin for requests from the iOS WebView is ionic://localhost. If Hostname and iosScheme preferences are set, then origin will be iosSchemeValue://HostnameValue.

The WebView is not able to display images, videos or other files from file or content protocols or if it doesn't have protocol at all. For those cases use window.Ionic.WebView.convertFileSrc() to get the proper url.

iosScheme
<preference name="iosScheme" value="httpsionic" />
Default value is ionic

Configures the Scheme the app uses to load the content.

Values like http, https or file are not valid and will use default value instead.

If you change it, you'll need to add a new allow-navigation entry in the config.xml for the configured scheme (i.e <allow-navigation href="httpsionic://*"/> if iosScheme is set to httpsionic).

**Comment by CodeWithOz** [comment]
@tryhardest yes the docs are a bit challenging for us too. Have you tried upgrading at all? We tried upgrading and the app is stuck on the splashscreen.
