### ISSUE TITLE
getting issue while using accessing google drive listing in ios. working fine in android

### ISSUE THREAD

**Issue by manishbhavnani** [ionic-team/cordova-plugin-ionic-webview#468]
Hii firstly, thnx for the plugin.  I tried the setting you recommeded in the docs 
<preference name="iosScheme" value="httpsionic" />
<allow-navigation href="httpsionic://*" />

but still i am getting the preflight error. can anyone please help.. any setting need to be done any thing.. would be really helpful

thank you in advance

**Comment by alextkd** [comment]
The call for loading the google client 
![image](https://user-images.githubusercontent.com/373321/77422196-bfb51a00-6dd5-11ea-9a3c-7bf1e5f633b5.png)

![image](https://user-images.githubusercontent.com/373321/77422227-ca6faf00-6dd5-11ea-9518-5c9582be3e79.png)

Might be related, not sure what are the supported schemas on google, with file:// used to work just fine, but that is not an option using this plugin

**Comment by jcesarmobile** [comment]
if they don't accept ionic scheme, there is nothing we can do about it, sorry
