### ISSUE TITLE
Cannot change content src startup html

### ISSUE THREAD

**Issue by joehui** [ionic-team/cordova-plugin-ionic-webview#469]
It seems like no matter what I put in the <content src=""> line, my cordova app always starts at the www/index.html page.  

If the src is not in the format of "http://localhost:[port]/<filename>", I would get this error:

WARNING: CordovaLocalWebServer: <content> tag src is not http://localhost[:port] (is index2.html).

But even if I put it in the expected format, it still only goes to index.html even though I specified index2.html.

I am testing this on iOS.

Joseph

**Comment by 04cfb1ed** [comment]
I have the same problem, @joehui could you solve the problem? 

The steps for replicate the problem in a new project are:
```
cordova create testContent
cd testContent/
cordova platform add ios
cordova plugin add cordova-plugin-ionic-webview@latest
```

change the name of file index.html to index-app.html
change the config.xml preference to <content src="index-app.html" />

Build and execute the app, you will get a blank page
cordova build ios && xed platforms/ios

If I remove the plugin everything works as expected
cordova plugin rm cordova-plugin-ionic-webview@latest

I have the problem only in IOS.
