### ISSUE TITLE
[cors] http to https api end point **EDITED**

### ISSUE THREAD

**Issue by indraraj26** [ionic-team/cordova-plugin-ionic-webview#470]
Is there any plan to resolve cors error? my Api point has ssl certificate which start with https and webview on http://localhost with that i am getting cors error. Browser is not allowing me to communicate http to https.

for Android it will work 
```
<preference name="Scheme" value="https" />
```

for iOS
```
<preference name="iosScheme" value="ionic" />
```
 so that it will open ionic://localhost as we know https, http and file is invalid so we will always get cors error for iOS even if we are modified the iosScheme

**Comment by jcesarmobile** [comment]
You have to configure your server to allow CORS or use a proxy or plugin that uses native connections
