### ISSUE TITLE
IOS  loading HTML page flash back!

### ISSUE THREAD

**Issue by Ssssk** [ionic-team/cordova-plugin-ionic-webview#472]
I used themebrowser plug-in to load external links. When there were more pages in my project and then loaded external links, there was a flash back. This problem occurred on ios, but android did not encounter any problems.
The themebrowser plug-in version I use is 0.2.17, and the cordova-plugin-ionic plug-in version I use is 2.2.3.
please  help  me  , thanke you!!!

**Comment by Ssssk** [comment]
cordova-plugin-ionic-webview plugin vision i use  is 2.2.3

**Comment by Ssssk** [comment]
@jcesarmobile

**Comment by VilasBoas1407** [comment]
@Ssssk  Have you already solve this error ? I have the same issue

**Comment by Ssssk** [comment]
> @Ssssk Have you already solve this error ? I have the same issue

no,I haven't found an effective way to solve it.
If you find it, could you please reply to me.
thanke you!

**Comment by Ssssk** [comment]
@VilasBoas1407  My firend, have you found a solution to the problem?

**Comment by VilasBoas1407** [comment]
No hahahaha, i'm focus on another thing, this week maybe i search a solution.
If i found, i reply with you
