### ISSUE TITLE
Ion-input will be blocked by the pop-up keyboard

### ISSUE THREAD

**Issue by Ssssk** [ionic-team/cordova-plugin-ionic-webview#474]
With the cordova-plugin-ionic-webivew@4.1.2 plug-in version, the ion-input input box in the ion-content cannot be ready to be positioned above the keyboard and will be blocked by the keyboard，please save the child!!

**Comment by Ssssk** [comment]
@mlynch @mccraigmccraig @shazron @purplecabbage

**Comment by Ssssk** [comment]
@jcesarmobile

**Comment by MahmoudAbuHadr** [comment]
Exactly the same happen here with  cordova-plugin-ionic-webivew@4.1.2

**Comment by Ssssk** [comment]
@jcesarmobile    Can you help me with this problem

**Comment by Ssssk** [comment]
@Brandy Carney  @Ben Sperry @jcesarmobile @Liam DeBeasi @Nicholas Hyatt  please help me!

**Comment by Ssssk** [comment]
@brandyscarney @bensperry @jcesarmobile @liamdebeasi    please help me!

**Comment by jcesarmobile** [comment]
Can you stop pinging people and instead provide a sample app where it can be reproduced?

**Comment by Ssssk** [comment]
@jcesarmobile   i am sorry.  
My problem is simply to use the 4.1.2 version of the webview plugin, and then when the input box is at the bottom of the page, the focus is captured and the mouse cursor is blocked instead of being positioned over the keyboard.
