### ISSUE TITLE
Losing local storage data when updating the ionic-webview plugin version from 1.2.1 to 4.1.3

### ISSUE THREAD

**Issue by rajashekaranugu** [ionic-team/cordova-plugin-ionic-webview#476]
Hello All,

Currently am using ionic-webview plugin version 1.2.1, ionic3, cordova 8.1.2, cordova-ios 4.5.5 and codova-android 7.1.2. 
And am updating my App with ionic-webview plugin version 4.1.3, ionic4, cordova 9.0.0, cordova-ios 5.0.1 and codova-android 8.x.x. 

So while updating my app am loosing the data stored in local storage. Many has suggested to go with a bridge release (2 releases. First one with all old versions AND with sq lite/ionic storage to store local data and next release with all these updates).

I don't have this bridge release option because of some other reasons. 
Can anyone suggest me a solution or any other **plugin** to solve this issue with one go (single release)
 
I really appreciate if anyone can suggest me a solution for this issue.

**Comment by kassamina** [comment]
I've been stuck on the same issue, migrating from ionic-webview plugin version 1.2.1 to  4.1.3

I do not think any of the plugins work currently for this, however I was able to get it to work for ios eventually by editing one of the  plugins. 

I still have to clean up the plugin and test it further, but I update this post when that is completed. 

As for android, I got that to work through the inAppBrowser, as that has access to data from localStorage, so when a specific flag was not set, I would look for the old data, and if found overwrite the current localStorage. This is in the javascript instead of the plugin, as I had not gotten that to work yet. My code was based on https://gist.github.com/OJ7/b748328b7eb1be9e76de47cb88dc8e3d tweaked for my use case.

**Comment by rajashekaranugu** [comment]
Hi Thank you for the replay, I have tried https://github.com/benjamineberle/cordova-plugin-migrate-localstorage plugin but no luck. 

And these are the below list of sites am closely following on this issue
https://github.com/pointmanhq/cordova-plugin-ionic-migrate-storage/issues/10
https://stackoverflow.com/questions/58863984/losing-local-storage-data-when-updating-the-ionic-webview-plugin-version-from-1
https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/476
https://github.com/jairemix/cordova-plugin-migrate-localstorage
https://forum.ionicframework.com/t/ionic-webview-update-causes-storage-loss/152594/7. 
https://github.com/benjamineberle/cordova-plugin-migrate-localstorage.   
https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/48. 
https://stackoverflow.com/questions/58863984/losing-local-storage-data-when-updating-the-ionic-webview-plugin-version-from-1.
https://stackoverflow.com/questions/54104921/ionic-webview-update-causes-storage-loss.

Let me know if anything works for you

**Comment by rajashekaranugu** [comment]
> I've been stuck on the same issue, migrating from ionic-webview plugin version 1.2.1 to 4.1.3
> 
> I do not think any of the plugins work currently for this, however I was able to get it to work for ios eventually by editing one of the plugins.
> 
> I still have to clean up the plugin and test it further, but I update this post when that is completed.
> 
> As for android, I got that to work through the inAppBrowser, as that has access to data from localStorage, so when a specific flag was not set, I would look for the old data, and if found overwrite the current localStorage. This is in the javascript instead of the plugin, as I had not gotten that to work yet. My code was based on https://gist.github.com/OJ7/b748328b7eb1be9e76de47cb88dc8e3d tweaked for my use case.

how did you test the migration of local storage??

**Comment by kassamina** [comment]
I have a ios / android test device I am working with, and I start by deleting any existing copy of the app.

I have the deployment of our app off of default script, it uses ionic-webview plugin version 1.2.1, and deletes the plugins folder / removes all platforms / removes all nodule_modules and then deploys the app to a test device.  This step is entirely automated

I log in to our app, which stores a token in localStorage

I have a similar script, that adds in ionic-webview plugin version 4.1.3 and the plugin I have been working on, but I have to manually edit the config.xml file first which is the only Manuel step. 

If the migration works, I should be logged in when the app opens. 

The android version is able to migrating consistently, the ios side has been tricky, with me thinking I have solved it several times only to run into issues =/

**Comment by kassamina** [comment]
As an update, it looks like the data for localStorage is stored in  a SQLlite, with Write Ahead Logging.

I can see the data in the -wall file, but that file is only quasi-permanent and should be deleted when closing the connection to the DB. However a backup or working copy of the data IS inside that file, even if it hasn't been synced up with the main file yet. 

This makes sense if I assume the DB connection wasn't closed properly when I just overwrote the app, leaving it in a tad bit of a mess. However a DB should be able to be recover from being force quit, so I suspect there is a way to fix this.

**Comment by rajashekaranugu** [comment]
> As an update, it looks like the data for localStorage is stored in a SQLlite, with Write Ahead Logging.
> 
> I can see the data in the -wall file, but that file is only quasi-permanent and should be deleted when closing the connection to the DB. However a backup or working copy of the data IS inside that file, even if it hasn't been synced up with the main file yet.
> 
> This makes sense if I assume the DB connection wasn't closed properly when I just overwrote the app, leaving it in a tad bit of a mess. However a DB should be able to be recover from being force quit, so I suspect there is a way to fix this.

Hi @kassamina Thanks a lot. You have provided lot of useful info. Today I will test with my App and will let you know how it goes.

Thanks again
Raj

**Comment by rajashekaranugu** [comment]
@kassamina hi you have deleted your plugin that you have developed? you mean to say, its not working?

**Comment by kassamina** [comment]
It did not open the SQLite DB and empty out the wal file, so I was seeing some syncing issues. I believe I have it working now, and I will update the plugin / repost it when it is working.

However I did not leave it up while I was unsatisfied with it.

**Comment by rajashekaranugu** [comment]
@kassamina I really appreciate your help. 
Will wait for your updated plugin. Please let me know when ever you publish this plugin. so that I can also give a shot. Am counting on you.

Thank you...

**Comment by kassamina** [comment]
@rajashekaranugu I believe I have it working right now, the installation is a bit troublesome without it being in npm, however my data is being migrated.

**Comment by rajashekaranugu** [comment]
Thanks for the update. Can you please share the repo URL.

Can you also please help me to understand the <allow-navigation href="http://xx.x.xx" />.

In our ionic-webView 1.2.1/IONIC 3 App we have this preference set. But in the updating app (ionic-webView 4.1.3/IONIC4). we did not declare it in our config.xml. 

Also can you please let me know if you are also using this preference?

In official document "https://github.com/ionic-team/cordova-plugin-ionic-webview" they mentioned about migrating to 4.x.x version

**Comment by rajashekaranugu** [comment]
@kassamina, I want to test the plugin that you have created. "https://github.com/kassamina/cordova-plugin-ionic-migrate-storage"

**My use case here is,**
- our current production app has "ionic-webView-1.2.1" and we were saving user data to local storage.
- currently I want to build the app using "ionic-webView-4.1.3" PLUS  your migrate-storage plugin.

**Build steps:**
- For this I have added your plugin "ionic cordova plugin add https://github.com/kassamina/cordova-plugin-ionic-migrate-storage --save" 
- then ionic cordova prepare ios, build the app and push to test flight.

**My expectations here are:**
- when I update the app using test flight, I should be able to get the local storage data saved on current production app (webview 1.2.1) and migrate that data to new app (webview 4.1.3).

**My Questions:**
- Is this achievable with your plugin?
- Can you please let me know if am following right/enough steps to use your plugin?
Any other suggestions from your side

Really appreciate your help on this
Thanks
Raj

**Comment by kassamina** [comment]
In my testing I am doing the same version jump, 1.21 -> 4.1.3 and yes I am able to find / migrate my existing localstorage data.

Are you setting the variables in config.xml?

`<preference name="MIGRATE_STORAGE_ORIGINAL_SCHEME" value="http" />
  <preference name="MIGRATE_STORAGE_ORIGINAL_HOSTNAME" value="localhost" />
  <preference name="MIGRATE_STORAGE_ORIGINAL_PORT_NUMBER" value="8684" />
  <preference name="iosScheme" value="ionic" />`

The default port I believe was 8080, but is now stored under port 0 regardless of wkport if using the ionic scheme.

If you had wkport set, try deleting it as well.

If you want to see what is going on, you can check where the old data is by browsing your app's files

https://stackoverflow.com/questions/6121613/browse-the-files-created-on-a-device-by-the-ios-application-im-developing-on-w/28161494

The data should be in /Library/WebKit/WebsiteData/LocalStorage/... when using 4.1.3

**Comment by rajashekaranugu** [comment]
@kassamina thanks for the quick replay and Info.

without adding any variables in config.xml, my use case is working for iOS, I will give it a shot with Android as well and share the observations. 

I have been struggling on this issue since 2 months. I owe you a treat

**Comment by kassamina** [comment]
I'm in Ottawa =) but I am glad it worked, I was struggling with this and just decided to roll my own solution. However as I mentioned before I got it working with the in app browser method for android, so i never attempted to get the plugin working for android, so I do not expect it to do anything on that side.

**Comment by rajashekaranugu** [comment]
Yup I remember that you have mentioned for Android, If you don't mind  can you please provide me some details that you have made it work for android. i will also try to follow similar path.

Thanks
Raj

**Comment by kassamina** [comment]
Sure, This is what I did, and some of the services are internal, but you should be able to get the idea from it.

https://gist.github.com/kassamina/88574c1c82bb9d3ab115052429015d3d

**Comment by rajashekaranugu** [comment]
you are awesome. thank you so much

**Comment by paamrutk** [comment]
@kassamina : We tried the code from the link https://gist.github.com/kassamina/88574c1c82bb9d3ab115052429015d3d to use it in our ionic 4 application with Angular 8.
But the code is in the angular.js(v1.0). We tried using the code in index.html and even when the platform gets ready but no luck.

Can you please tell us how you used this code in your application.

**Comment by rajashekaranugu** [comment]
@kassamina, are you planning to extend this plugin to Android also anytime soon ?.

Because we could not follow the solution that you suggested for Android. Can you please help us regarding this.

Thank you
Raj

**Comment by kassamina** [comment]
I am not planning to, I got the android side working quickly by adapting the code in this gist
https://gist.github.com/OJ7/b748328b7eb1be9e76de47cb88dc8e3d before I got the ios side working. 

The plugin I forked from does something similar for android, with an in app browser. I removed it as I did not intend to support it, but I suspect that solution could be made to work, as it is similar in concept to what worked for me.

**Comment by rajashekaranugu** [comment]
Hi @kassamina, thanks for the response. 

1. Can you please let us know where you are inserting you code, to make it work for android. Is it in INDEX.HTML ? 
2. Can you also please share us some knowledge or thoughts regarding where you are using this Android code in the app Lifecycle? 
3. Are you making a call to the new service before the app launch?

Thanks for the time and help
Best
Raj

**Comment by rajashekaranugu** [comment]
@kassamina, so you followed the same method as mentioned here "https://gist.github.com/OJ7/b748328b7eb1be9e76de47cb88dc8e3d" 

Can you please let me know if I understood it right...

-> local-storage-migration.html into src/assets folder and
-> Call local storage service, before each and every time when trying to access local Storage?

**Comment by kassamina** [comment]
That does not seem necessary, as you can grab the entire localStorage from the IAP and export it back, the reset method lets me overwrite the existing localStorage with the exported data. So this migration only has to be run once.

**Comment by rajashekaranugu** [comment]
ok and where are you adding local-storage-migration.html file?

**Comment by rajashekaranugu** [comment]
> That does not seem necessary, as you can grab the entire localStorage from the IAB and export it back, the $localStorage.$reset method lets me overwrite the existing localStorage with the exported data. So this migration only has to be run once.

@kassamina when are you planning to submit the iOS plugin for approval?

**Comment by rajashekaranugu** [comment]
Failed to restore plugin "cordova-plugin-ionic-migrate-storage" from config.xml. You might need to try adding it again. Error: Error: npm: Command failed with exit code 1 Error output:
npm ERR! code E404
npm ERR! 404 Unpublished by venna138 on 2019-12-03T22:28:54.311Z
npm ERR! 404 
npm ERR! 404  **'cordova-plugin-ionic-migrate-storage' is not in the npm registry.**
npm ERR! 404 **You should bug the author to publish it (or use the name yourself!)**
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/.npm/_logs/2019-12-06T18_54_50_042Z-debug.log

**Comment by rajashekaranugu** [comment]
@kassamina can you please publish this???

**Comment by rajashekaranugu** [comment]
@kassamina this plugin in working on iphone 8/10 times, the rest two times, I think it needs  to be added something similar to settimeout for all the plugins to be loaded or migrated data to be fetched.

**Comment by kassamina** [comment]
> @kassamina this plugin is working on iphone 8/10 times, the rest two times, I think it needs to be added something similar to settimeout for all the plugins to be loaded or migrated data to be fetched.

In the 1/5 times that it does fail, do you know if it is because the data is not copied over? or because the app inits before the migration is finished?

If you restart the app, does load properly? Is the data still in the -wal file? If you've toggled debug mode, did you see any errors?

**Comment by rajashekaranugu** [comment]
The data is getting copied, but the app inits before the migration process is completed. 
And that's the reason on login page I could not see the copied data. 

**steps to reproduce:**
This issue can be reproduced on iphone 5S as it happens almost 90% of the times.
Just kill the app and relaunch app on iphone 5S.


If you restart the app, does load properly? - No
Is the data still in the -wal file? - I think so
If you've toggled debug mode, did you see any errors? - will let you know.

Thanks
Raj

**Comment by rajashekaranugu** [comment]
> Failed to restore plugin "cordova-plugin-ionic-migrate-storage" from config.xml. You might need to try adding it again. Error: Error: npm: Command failed with exit code 1 Error output:
> npm ERR! code E404
> npm ERR! 404 Unpublished by venna138 on 2019-12-03T22:28:54.311Z
> npm ERR! 404
> npm ERR! 404 **'cordova-plugin-ionic-migrate-storage' is not in the npm registry.**
> npm ERR! 404 **You should bug the author to publish it (or use the name yourself!)**
> npm ERR! 404
> npm ERR! 404 Note that you can also install from a
> npm ERR! 404 tarball, folder, http url, or git url.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! /Users/.npm/_logs/2019-12-06T18_54_50_042Z-debug.log

@kassamina is there any plan to create a PR and publish this?? @mccraigmccraig @mlynch

**Comment by kassamina** [comment]
I can replicate the issue, my hesitation is that my intent was to fork someone else's plugin for my own purpose. So I did not want to take the unscoped namespace, but I will go ahead and make a new namespace instead of using my own scoped copy.

**Comment by rajashekaranugu** [comment]
Thank you @kassamina, you are awesome. Will wait for your update

**Comment by kassamina** [comment]
It now has it's own unscoped namespace, so I wouldn't expect you to see that error anyone if you remove the old version completely and then use

`cordova plugin add --save cordova-plugin-ionic-migrate-ios-storage@0.3.6`

The oldest device I have to test with is an iphone 6s, and I have not seen the 1/5 failure chance you described, do you have idea or update about what is going on there?

**Comment by rajashekaranugu** [comment]
@kassamina thanks a lot, am still debugging on the iOS 1/5 failure issue. Will keep you posted.

thanks again for your help and time

**Comment by rajashekaranugu** [comment]
Hello @kassamina, the plugin you created is using UIWebView class which is deprecated by apple.. And Apple will stop accepting apps which use this class.

Can you please create a new version which only uses WKWebview in the plugin. Thanks a lot
