### ISSUE TITLE
Upgrading webview preserving local storage (from cordova-plugin-wkwebview-engine to cordova-plugin-ionic-webview)

### ISSUE THREAD

**Issue by eleva** [ionic-team/cordova-plugin-ionic-webview#48]
As for the title, preserving data in local storage is not working when upgrading from official cordova-pluginwkwebview-engine to this plugin. I'm not moving from UIwebView (this case is covered by https://github.com/MaKleSoft/cordova-plugin-migrate-localstorage), but from official Apache WkWebView to this one.

Moving data from localstorage to sqllite and then back to localstorage, with a "middle-release", is not an option (as is not a fix, but just a workaround not suitable for all users).

Is there a way to pass data saved in local storage from the previous official plugin to this one?
Thank you for your help!

**Comment by kas84** [comment]
I made a fork:

https://github.com/kas84/cordova-plugin-migrate-localstorage

**Comment by eleva** [comment]
Hi Kas, this plugin seems to move data in localstorage from **UiWebView to Ionic WkWebView**.
Am I right?

Also, as said in your plugin documentation. using your plugin, I need a "middle-release" to be sure all user data in production will be put in UiWebView localstorage, then the "final-relase" will be able to get data from there and put them in IonicWkWebView localstorage.
This is not suitable, as I cannot be sure all my users will download the middle-release.
I've tried it anyway, and I'm still losing all localstorage data.

This is not what I'm looking for, **I'm looking for a fix or a plugin to move directly data from Officical WkWebView to Ionic WkWebView, which not require more than a new release to substitue official WkWebView with Ionic one**

**Comment by eleva** [comment]
To anyone having this issue: this could happen if you have previously changed your GCDWebServer from 8080 to a custom one (1730 in my case). I've solved the issue changing 8080 to 1730 in CDVWKWebViewEngine.m file and allowing navigation in my config.xml with this tag
`<allow-navigation href="http://localhost:1730/*"/>`

It would be great if we can set the port when installing the plugin, for example with a new option
`cordova plugin add cordova-plugin-ionic-webview **-p 1730** --save`

**Comment by kas84** [comment]
@eleva my plugin does not move data from WKWebView to  Ionic webview, but UIWebview to ionic Webview which is what I was trying to achieve.
If you did not achieved it already, I suggest you take a look at the docs to see how to name the files properly then for the plugin.

Merry Christmas!

**Comment by jcesarmobile** [comment]
There are plugin for migrating the data, some mentioned here.
It's out of the scope of the plugin, closing.
