### ISSUE TITLE
Manipulate IOS media controls

### ISSUE THREAD

**Issue by paulovargatt** [ionic-team/cordova-plugin-ionic-webview#480]
I'm having trouble trying to manipulate media controls on IOS running video or audio, I tried using the cordova-music-controls plugin but it doesn't work and it looks like the web view itself creates those controls, so the question is how to manipulate it in Ionic. Media Session API in my tests does not work!
Thanks for any help!
![Image of Yaktocat](https://i.imgur.com/C5xbhRb.jpg)

**Comment by ghenry22** [comment]
If you use the cordova media plugin for playback then the music controls plugin works.

If you are using HTML5 audio / video tags then they override the controls set by the plugin and I haven't yet found a way to stop them from doing so.
