### ISSUE TITLE
Any way to get window.WkWebView ?

### ISSUE THREAD

**Issue by Yuripetusko** [ionic-team/cordova-plugin-ionic-webview#481]
for example to do `window.WkWebView.allowsBackForwardNavigationGestures(false)` I cannot find it anywhere in the global scope it seems

**Comment by chinieer** [comment]
I do think the feature is useful

**Comment by tryhardest** [comment]
+1

**Comment by jcesarmobile** [comment]
that's from this plugin https://github.com/apache/cordova-plugin-wkwebview-engine
