### ISSUE TITLE
ionic:// URL and localStorage

### ISSUE THREAD

**Issue by joehui** [ionic-team/cordova-plugin-ionic-webview#485]
On iOS, is it normal that my root page has URL starting with ionic://localhost?  I was expecting http://localhost?

I am having some issues with migrating localStorage from UIWebView.  I suspect the ionic:// part is causing the data to not appear.  I think localStorage is specific to protocol, host, and port.

Any help would be greatly appreciated.

**Comment by joehui** [comment]
Oh, I am using this plugin with cordova, not Ionic.

**Comment by jcesarmobile** [comment]
yes, it's normal, and yes, webview storage is tied to the scheme, origin, port, etc.

For migrating data, there are a few plugins that claim to do it, but didn't test any of them.
