### ISSUE TITLE
window.open not handled by WKWebview

### ISSUE THREAD

**Issue by meisterlampe** [ionic-team/cordova-plugin-ionic-webview#487]
Hi,

in my app I am loading the actual app from a device via bluetooth. After that I want to open this Ionic app (similar to the good old ```Ionic View```-App :-) )

```window.open("url to ionic www folder")``` is working on android but not on iOS. On iOS just nothing happens. I don't want to use the InAppBrowser as I need cordova plugins in the downloaded app.
On Android all this is working fine.

Isn't there any option for me to just point my WKWebview to another index.html in my apps data storage? How did you guys implement this in ```Ionic View```-App?

Thanks in advance :)

**Comment by jcesarmobile** [comment]
looks like window.open doesn't work without user interaction, you can use `window.location = 'url to ionic';` instead

**Comment by meisterlampe** [comment]
`window.location` is not working for me on android and on ios (but it does work on android using `window.open`). I try to open a index.html from `File.dataDirectory`.
The complete url is (`File` from `@ionic-native/file/ngx`: 
```
const uiFilePath = this.file.resolveLocalFilesystemUrl(this.file.dataDirectory + `app-versions/1.0.0/${platformName}`);
const url = (window as any).Ionic.WebView
          .convertFileSrc(`${uiFilePath.toURL()}
```
Maybe this is not correct?

Maybe because it is not within the original ionic folder but in data dir? Unfortunately the appfolder is read-only and I have to download to some other location.
