### ISSUE TITLE
How to run IOS using http://localhost?

### ISSUE THREAD

**Issue by vadimklimchuk** [ionic-team/cordova-plugin-ionic-webview#488]
I work with ionic version 4.
I use firebase passwordless sms authentication. For android it works fine(http://localhost).
But when i run it on android i gets message: "recaptchaVeryfier is supported only browser http and https environments"(for IOS using ionic://localhost). How can i redefine environment for IOS?

I will be very grateful for your help.

**Comment by jcesarmobile** [comment]
you can use v2 of the plugin, but on v4 you can't use https or http to serve the files
