### ISSUE TITLE
Cannot build android.support.annotation does not exist

### ISSUE THREAD

**Issue by florianmonfort** [ionic-team/cordova-plugin-ionic-webview#489]
Hi,

I have a project that was running without AndroidX before so it could be compiled, but now to target higher API levels we need to use androidx. So to solve this issue we have installed the following plugins:

cordova-plugin-androidx
cordova-plugin-androidx-adapter

However during build time we still get the following error, including from camera cordova plugin:

`
> Task :app:processDebugResources

> Task :app:compileDebugJavaWithJavac FAILED
/Users/dev/Developer/diningcity-assistant/platforms/android/app/src/main/java/org/apache/cordova/camera/CameraLauncher.java:64: error: package android.support.v4.content does not exist
import android.support.v4.content.FileProvider;
                                 ^
/Users/dev/Developer/diningcity-assistant/platforms/android/app/src/main/java/org/apache/cordova/camera/CordovaUri.java:25: error: package android.support.v4.content does not exist
import android.support.v4.content.FileProvider;
                                 ^
/Users/dev/Developer/diningcity-assistant/platforms/android/app/src/main/java/org/apache/cordova/camera/FileProvider.java:21: error: package android.support.v4.content does not exist
public class FileProvider extends android.support.v4.content.FileProvider {}
                                                            ^
/Users/dev/Developer/diningcity-assistant/platforms/android/app/src/main/java/com/ionicframework/cordova/webview/IonicWebViewEngine.java:11: error: package android.support.annotation does not exist
import android.support.annotation.RequiresApi;
                                 ^
/Users/dev/Developer/diningcity-assistant/platforms/android/app/src/main/java/com/ionicframework/cordova/webview/IonicWebViewEngine.java:114: error: cannot find symbol
    @RequiresApi(Build.VERSION_CODES.LOLLIPOP)
     ^
  symbol:   class RequiresApi
  location: class IonicWebViewEngine.ServerClient
/Users/dev/Developer/diningcity-assistant/platforms/android/app/src/main/java/org/apache/cordova/camera/CameraLauncher.java:297: error: cannot find symbol
        this.imageUri = new CordovaUri(FileProvider.getUriForFile(cordova.getActivity(),
                                                   ^
  symbol:   method getUriForFile(Activity,String,File)
  location: class FileProvider
/Users/dev/Developer/diningcity-assistant/platforms/android/app/src/main/java/org/apache/cordova/camera/CameraLauncher.java:803: error: cannot find symbol
                        Uri tmpFile = FileProvider.getUriForFile(cordova.getActivity(),
                                                  ^
  symbol:   method getUriForFile(Activity,String,File)
  location: class FileProvider
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
7 errors
FAILURE: Build failed with an exception.
`

So it seems both this plugin cordova-plugin-ionic-webview and camera are involved.

Here is some more information about which environment we are using:

`
ionic info

Ionic:

   Ionic CLI                     : 5.4.12 (/Users/dev/.nvm/versions/node/v12.1.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.4.0-dev.201904251558.2457a23
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.2.3
   @angular/cli                  : 7.2.3
   @ionic/angular-toolkit        : 1.2.3

Capacitor:

   Capacitor CLI   : 1.0.0-beta.22
   @capacitor/core : 1.0.0-beta.19

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.3, (and 18 other plugins)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.1
   NodeJS     : v12.1.0 (/Users/dev/.nvm/versions/node/v12.1.0/bin/node)
   npm        : 6.9.0
   OS         : macOS Catalina
   Xcode      : Xcode 11.2.1 Build version 11B500
`

**Comment by jcesarmobile** [comment]
android.support.annotation is the non Android X dependency, so looks like your Android X plugins are not correctly mapping the new dependencies. But it's for them to fix.
This plugin doesn't support Android X yet because cordova-android doesn't support Android X yet.
We will remove the annotation dependency on next release, you can track the Android X issue here
https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/275

**Comment by emma009** [comment]
the best solution is to go into this file path platforms/android/app/src/main/java/com/ionicframework/cordova/webview/IonicWebViewEngine.java

then comment and replace with this lines like this..then rerun your project..fixed it for me

//import android.support.annotation.RequiresApi;
import androidx.annotation.RequiresApi;
