### ISSUE TITLE
Ionic Native: deviceready did not fire within 5000ms

### ISSUE THREAD

**Issue by sergiol29** [ionic-team/cordova-plugin-ionic-webview#493]
The plugin show me the error `Ionic Native: deviceready did not fire within 5000ms.` and the function `this.platform.ready()` in `app.component.ts` it doesn't execute.

If I delete the plugin `cordova-plugin-ionic-webview`, I fix the issue and `this.platform.ready()` it execute but web view utilities it doesn't work.

Someone has have the same error?

Thanks.

**Comment by fernandomeridamatilla** [comment]
+1

**Comment by tryhardest** [comment]
@sergiol29 Can you put that to proof in a MVB (minimum viable build) to have causal blame on this plugin? Yes removing to prevents, but other things could be contributing otherwise we would all have this error.

**Comment by ptorrent** [comment]
Same here.. did you find a solution ?

**Comment by Et3rnal** [comment]
I'm having the same issue with the android build (run works fine).
I have tried removing and adding platforms and all plugins without luck, there seems to be many with this issue but no proper solution!

Can we trigger it manually to see where it is failing ?
