### ISSUE TITLE
Need to load page on https://hostname instead of ionic://hostname 

### ISSUE THREAD

**Issue by Git-Santhosh** [ionic-team/cordova-plugin-ionic-webview#494]
We are using the Ionic4 with angular router. For IOS Need to load page on wkwebview url like https://hostname instead of ionic://hostname. because we need to call the okta server for two way authentication. okta not accept the "**ionic**" as trusted orgin. okta allowed only **_"https or http"._**

**Comment by ponrajasekar** [comment]
@mlynch is there any possibility to change the scheme for IOS.

**Comment by wnabil** [comment]
https://github.com/ionic-team/cordova-plugin-ionic-webview#scheme

**Comment by bbialas** [comment]
> https://github.com/ionic-team/cordova-plugin-ionic-webview#scheme

@wnabil this preference is for Android, and it works on that platform.

+1 for this possibility on iOS, I also need it for external service which checks app protocol... 
Would be great to allow https for iOS as well!

Is there any reason why it's not allowed?

**Comment by tryhardest** [comment]
To have https as trusted origin for iOS is huge. Hopefully in the next release?

**Comment by jcesarmobile** [comment]
you can use v2 of the plugin, but on v4 you can't use https or http to serve the files
