### ISSUE TITLE
Scroll in iOS 12.2/12.4 cant's slide

### ISSUE THREAD

**Issue by 50l3r** [ionic-team/cordova-plugin-ionic-webview#495]
I have a problem with scroll in iOS 12.2 & 12.4

Scroll works but doesnt slide. It looks static. On iOS 13 works fine:

Expected behaviour:
[![Image from Gyazo](https://i.gyazo.com/2631afcbd95a66ce72e92977919bd1d6.gif)

Problem:
[![Image from Gyazo](https://i.gyazo.com/d61587f311cc898d529ec56292cf66f1.gif)](https://gyazo.com/d61587f311cc898d529ec56292cf66f1)

i try this: https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/326 and this https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/326#issuecomment-483732402 without results:

I dont use ionic tags in my app. Only alerts and dropdowns. I try to put pointer-events: auto in my scroll container but it doesnt work.

This is my container css:

    .flex-content {
	    flex: 1;
	    display: flex;
	    flex-direction: column;
	    overflow-y: scroll;
	    overflow-x: hidden;
	    height: 100%;
	    transition-duration: 500ms;
	    pointer-events: auto;
    }

**Comment by 50l3r** [comment]
Any idea?

**Comment by vicmaneitor** [comment]
I have the same problem on iOS 12.2 & 12.4, any solution? 

I tried some solutions like:
`ion-app.platform-ios12 ion-content { pointer-events: auto; /*fix scroll lock on ios12.2*/ }`
But not working. 

Also the links <a href"XXX"> into my app have stopped working.
On IOS 13.x everything is OK.

**Comment by 50l3r** [comment]
Any idea?

**Comment by rajashekaranugu** [comment]
ion-app.platform-ios12 ion-content { 
  pointer-events: auto; /*fix scroll lock on ios12.2*/ 
}

add this in variables.scss. it worked for me

**Comment by 50l3r** [comment]
I don't use ion-app and ion-content tags on my project

**Comment by Aex12** [comment]
Add this line to your scroll container in css:

-webkit-overflow-scrolling: touch;

**Comment by 50l3r** [comment]
Testeado y funcionando :)

**Comment by carlosromanmena** [comment]
Add this line to your config.xml file:

`<preference name="ScrollEnabled" value="true" />`
