### ISSUE TITLE
Cookies failing on iOS simulator

### ISSUE THREAD

**Issue by Lucaszw** [ionic-team/cordova-plugin-ionic-webview#498]
This is likely related to #475 

When attempting to run our application through the iOS simulator cookies do not seem to be set or persist. However everything works fine when running from an actual iPhone.

Ionic:

   Ionic CLI         : 5.4.4 (/Users/zeer/Documents/KitchenMate/kitchenmate/node_modules/ionic)
   Ionic Framework   : unknown
   @ionic/v1-toolkit : 1.0.22

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic 5.4.6, cordova-plugin-ionic-webview 4.1.3, (and 12 other plugins)

Utility:

   cordova-res : 0.8.1 
   native-run  : 0.2.9 (update available: 0.3.0)

System:

   Android SDK Tools : 26.1.1 (/Users/zeer/Library/Android/sdk)
   ios-deploy        : 1.10.0
   ios-sim           : 8.0.2
   NodeJS            : v10.15.3 (/Users/zeer/.nvm/versions/node/v10.15.3/bin/node)
   npm               : 6.4.1
   OS                : macOS Mojave
   Xcode             : Xcode 11.3 Build version 11C29

cordova-plugin-advanced-http 2.3.1 "Advanced HTTP plugin"
cordova-plugin-android-permissions 1.0.2 "Permissions"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic 5.4.6 "cordova-plugin-ionic"
cordova-plugin-ionic-webview 4.1.3 "cordova-plugin-ionic-webview"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-plugin-wkwebview-inject-cookie 1.0.2 "WKWebViewInjectCookie"
cordova-plugin-wkwebview-sync-cookies 1.0.0 "WKWebViewCookieSync"
cordova-plugin-wkwebviewxhrfix 0.1.0 "WKWebView XHR Fix"
ionic-plugin-deeplinks 1.0.20 "Ionic Deeplink Plugin"
onesignal-cordova-plugin 2.7.0 "OneSignal Push Notifications"

Attempted updating all packages but issue still persists.

![Screen Shot 2020-01-10 at 1 08 09 PM](https://user-images.githubusercontent.com/2607311/72175495-47c87d80-33aa-11ea-80af-9ce76a54eb29.png)

![Screen Shot 2020-01-10 at 1 08 41 PM](https://user-images.githubusercontent.com/2607311/72175524-59118a00-33aa-11ea-9bcb-e9201594e7e8.png)

**Comment by jcesarmobile** [comment]
there are a lot of cookie bugs on Apple devices, sadly only Apple can fix them

**Comment by rsgone** [comment]
@Lucaszw Add following line inside `<platform name="ios"></platform>` of config.xml file

`<preference name="Hostname" value="api-gateway.soccerlab.com" />`
