### ISSUE TITLE
Add option to allow GCDWebserver to run in background

### ISSUE THREAD

**Issue by ghenry22** [ionic-team/cordova-plugin-ionic-webview#5]
I have an app that plays audio and fetches data when in the background, using the allowed background audio and background fetch processes.

I need to be able to access images and cover art for albums when playing music in the background so that they can be displayed on the lock screen and control center.

If GCDWebserver is stopped as soon as the app goes to the background then I cannot access these files which results in broken app behaviour.

There is an option available in GCDWebserver config to enable background operation, it just needs to be enabled, this could possibly be passed to the plugin on startup as an option runInBackground=true/false and be defaulted to false.

**Comment by matejkramny** [comment]
seems to already be present: https://github.com/ionic-team/cordova-plugin-ionic-webview/blob/master/src/ios/CDVWKWebViewEngine.m#L174

**Comment by ghenry22** [comment]
Yeh I’m the one who made the changes :)
