### ISSUE TITLE
html table/ion-list scroll very slow

### ISSUE THREAD

**Issue by sannaroby** [ionic-team/cordova-plugin-ionic-webview#50]
We’ve an html table in a page created using a ngFor. The scroll of this table it’s very slow in ipad mini 2/4 (no problems with android and iphone 6/7/7 plus) also with only 50 rows. Also the selection of the rows is very slow (we’ve a checkbox for each row, with or without click event).

More details [here](https://stackoverflow.com/questions/47412564/ionic-3-html-table-ion-list-scroll-very-slow).

**Comment by ghenry22** [comment]
I don't think this is a wkwebview specific issue.  There is a very similar issue logged against ionic itself:

https://github.com/ionic-team/ionic/issues/12733

**Comment by sannaroby** [comment]
Thanks for your reply. 

We've solved removing this from the main.css, as indicated in your link:

:focus,
:active {
  outline: none;
}
