### ISSUE TITLE
WKWebView doesn't support HTTP/2 headers

### ISSUE THREAD

**Issue by SergTomcat** [ionic-team/cordova-plugin-ionic-webview#502]
HTTP/2 protocol uses lowercase headers.
Every CORS request fail to get access with status 0, as every header is in lowercase:

**access-control-allow-credentials**: true
**access-control-allow-headers**: Authorization, Content-Type, Depth, User-Agent, X-File-Size, X-Requested-With, If-Modified-Since, X-File-Name, Cache-Control, Cookie, Connection, Host
**access-control-allow-methods**: GET, OPTIONS
**access-control-allow-origin**: *

HTTP/1.1 with case sensitive headers works fine.

Suggestion: support lowercase headers or give option to disable CORS check.

**Comment by tryhardest** [comment]
Is anyone at Ionic looking at this stuff anymore?

**Comment by rvenkatsaravanan** [comment]
Unable to set a cookie after update from UIWebView to WKWebView in IONIC - ios. Any update on this issue?

**Comment by jcesarmobile** [comment]
The plugin doesn't handle the cookies nor the headers, that's internally handled by the webviews, so report the issues to Apple or Google (depending on the platform you are facing the issues)
And neither of them provides a way of disabling CORS, so the only alternative is to use a http plugin.

**Comment by rvenkatsaravanan** [comment]
Thanks for your reply, this issue happening only with ionic-webview above
version 4

**Comment by jcesarmobile** [comment]
You were using UIWebView, the issue is on the WKWebView that the plugin uses, but only Apple can fix WKWebView issues, so report it to them.
Also, this issue is not related to cookies, please, don't comment on unrelated topics.

**Comment by rvenkatsaravanan** [comment]
Thanks for your detailed reply.
