### ISSUE TITLE
UiWebView reference appearing in this plugin

### ISSUE THREAD

**Issue by lizqjue** [ionic-team/cordova-plugin-ionic-webview#503]
Looking for UiWebView references in my project in order to prepare our apps for using only WkWebView I found the following reference at the file CDVWKWebViewEngine.m  which uses a variable from UiWebView.h header file:

UIWebViewNavigationTypeOther

Could you please confirm that this is safe and we won't have problems with this reference when trying to upload an app to the AppStore after the WkwebView deadline? (April 2020 for new apps, December 2020 for updates)

Thank you very much,

Versions:
Ionic : non ionic project (Angular 7)
cordova-plugin-ionic-webview : 4.1.3

**Comment by dotNetkow** [comment]
Yes, it should be fine. [See here](https://ionicframework.com/blog/understanding-itms-90809-uiwebview-api-deprecation/) for details.

**Comment by wilk-polarny** [comment]
@lizqjue, You need to update the cordova ios platform to at least `5.1.0` and add the preference 

```xml
<preference name="WKWebViewOnly" value="true" />
```

to your config.xml. 

When changing the platform version you will need to re-add the platform either through platform remove or by deleting the appropriate directory.

**Comment by ragcsalo** [comment]
How can I search for UIWebView references in my iOS Cordova project? I did everything they recommended, but it seems some plugins still have UIWebView related codes...

**Comment by wilk-polarny** [comment]
@ragcsalo have you tried doing a text or code search through the native project or the plugin projects yet? Should be easy to find if you have the sources for all of the parts of the project. If you use proprietary plugins with prebuilt frameworks, you are going to have a bad time though.

**Comment by ulver2812** [comment]
Hi, I must use the 1.2.1 version of this plugin in order to run the app on ios 9 with WKWebView enabled, if I use the latest version I can't run the app on ios 9. The version 1.2.1 contains references about UiWebView ?
