### ISSUE TITLE
Clobbers support

### ISSUE THREAD

**Issue by stuk88** [ionic-team/cordova-plugin-ionic-webview#504]
I have cordova-plugin-splashscreen (3.0.1) installed.
It worked fine. 
After adding cordova-plugin-ionic-webview the splash was not any more inside the variable it should have been inside:
`navigator.splashscreen`

Why the clobbers stopped working?

**Comment by jcesarmobile** [comment]
try removing the ios platform and adding it again, but this is not a bug in this plugin
