### ISSUE TITLE
What is the purpose of this plugin on android?

### ISSUE THREAD

**Issue by Amaury-T** [ionic-team/cordova-plugin-ionic-webview#506]
Hello again,

Was wondering what is the advantage of using this plugin on android (with cordova)?
For IOS it is obvious as it permit to use the wkwebview, but for android, what did it bring compared to cordova without it?

Thanks ! :)

**Comment by ghenry22** [comment]
serves content from local web server versus from file://
gives a consistent way to access locally stored files and content across both platforms.

**Comment by Amaury-T** [comment]
Thanks for the clarification @ghenry22 , i'll close the issue.
