### ISSUE TITLE
Shouldn't scroll to Top after keyboard dismissal 

### ISSUE THREAD

**Issue by Amaury-T** [ionic-team/cordova-plugin-ionic-webview#509]
Hello,
I have a problem when using this plugin. After each keaybord dismissal, screen is scroll to the top of the app. It is a real problem because the user experience is really bad like that.

How can I fix that?

Thanks a lot in advance!
BR

**Comment by Amaury-T** [comment]
Well, I have finally managed to make it work, I have made the body of my app non-scrollable and have added a div just below wich is scrollable.

`<body>
  <div class="main">
    ...
  </div>
</body>`

`body {
  overflow: hidden;
  height: 100vh;
}

.main {
  overflow: scroll;
  height: 100%;
}`

**Comment by sajallimbu** [comment]
I ran into the same problem. Did you find any solution?

**Comment by sajallimbu** [comment]
I fixed the problem with this change 
https://github.com/ionic-team/cordova-plugin-ionic-webview/pull/342#issuecomment-585644871

**Comment by sajallimbu** [comment]
I tested the fix in an old ipad and it seems the scroll action that takes place after keyboardwillhidehide causes the viewport to flicker since the device is not fast enough. It works perfectly for iphone SE and above devices.

**Comment by Lindsay-Needs-Sleep** [comment]
Duplicate issue of #399

**Comment by jcesarmobile** [comment]
fixed in https://github.com/ionic-team/cordova-plugin-ionic-webview/pull/533
