### ISSUE TITLE
Next release date

### ISSUE THREAD

**Issue by tryhardest** [ionic-team/cordova-plugin-ionic-webview#510]
Hi, sorry to be presumptuous in asking, but is there a date for the next release?

There are quite a few unmerged PR's and we just spend a solid 2 weeks on a confounding bug related to this plugin (after having upgraded and cause imgCache related issues) that one of the PR's actually addresses. 

Looks like last release was 3.5 months ago. Tnx

**Comment by tryhardest** [comment]
Maybe @dwieeb ?

**Comment by tryhardest** [comment]
This looks really bad Ionic. Is Capacitor the same response rate?

**Comment by webteambel** [comment]
Please Can anybody tell us when it will be the next release, thanks ^_^

**Comment by mlynch** [comment]
In your opinion, what are the most important PRs you would like to see merged?

**Comment by webteambel** [comment]
@mlynch I think most people want this feature : add http(s) proxy/scheme for iOS
https://github.com/ionic-team/cordova-plugin-ionic-webview/pull/448

we still have a cors problem while using salesfore ( salesforce only accept  http/https)
Link: https://help.salesforce.com/articleView?id=snapins_chat_cors_whitelist.htm&type=5

And others like Azure:
https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/349

**Comment by tryhardest** [comment]
I would agree @webteambel def 448. Also #376, #452 and #486. There are only 7 total and they all passed with no conflicts so I maybe a full merge is ok @mlynch ?

**Comment by webteambel** [comment]
any news ? We are waiting for the new version so we can fix our problem and publish our new version of app using ionic 5.

**Comment by tryhardest** [comment]
@webteambel This is such an easy release. All tests past. Almost no information except @mlynch asking 2 weeks ago. Can I maintain this plugin if Ionic won't?

**Comment by webteambel** [comment]
@tryhardest I have no idea, sorry :/

**Comment by dwieeb** [comment]
To shed a little light on this, we recently audited the PRs in this repo and either closed them, asked for more information, or begun the merging process. We're going to make a release as soon as https://github.com/ionic-team/cordova-plugin-ionic-webview/pull/452 is merged, which should address some of the original concerns. 

This repo doesn't actually have any automated tests (it's tremendous work setting up automated testing for Cordova plugins), so it's not as simple as just merging if there are no conflicts. We have to thoroughly hand test submitted code as well as inspect it for potential security issues.  

As a heads up, part of the delay here is that we're starting to focus more on Capacitor after seeing the vast benefits: cohesive, focused platform; productivity gains; faster shipping; etc. That's not to say Cordova won't be supported for the foreseeable future, but we have a limited number of resources to dedicate. We're a small team and frankly the amount of open source code we have is overwhelming sometimes, so thank you for your patience! 💙

**Comment by jcesarmobile** [comment]
4.2.0 was released last Tuesday
