### ISSUE TITLE
[iOS] app stuck on splashscreen after migrating from 2.5.x to 4.1.3

### ISSUE THREAD

**Issue by CodeWithOz** [ionic-team/cordova-plugin-ionic-webview#511]
Our iOS app gets stuck on the splash screen after migrating from v2.5.x of this plugin to v4.1.3. It appears that this is related to the [GCDWebServer removal](https://github.com/ionic-team/cordova-plugin-ionic-webview/commit/0dee0cf) because:
- when I update the plugin without removing and re-adding the platform, the splashscreen doesn't hang and the app works normally. I noticed that the `.xcodeproject` file for my app contains leftover references to the GCDWebServer files even after updating the plugin (which removes the files from the plugins folder).
- when I remove the platform, update the plugin, and re-add the platform, the app hangs on the splashscreen. In this case, the `.xcodeproject` file for my app does not contain the leftover references to the GCDWebServer files.

Env:
- Cordova CLI 8.1.2
- Cordova iOS 5.0.1
- Xcode 10.1

Tested on iPhone 6 and 7.

Thank you!

**Comment by tmishutin** [comment]
Same problem here on iPhone 8

**Comment by tryhardest** [comment]
Same again.

**Comment by jcesarmobile** [comment]
If you get a white screen, it's probably a javascript error, you'll have to check the safari remote inspector and see what's going on.

**Comment by tmishutin** [comment]
It's not stuck on white screen, but on splash screen. And it's not javascript error, because javascript is not initiated at the time of crash.

**Comment by jcesarmobile** [comment]
there is no information to reproduce, so there is nothing to check

**Comment by tmishutin** [comment]
This problem is pretty hard to reproduce. It doesn't mean issue doesn't exist. It's not one report here, but several.

**Comment by CodeWithOz** [comment]
@jcesarmobile thanks for your hard work. I mentioned that the problem doesn’t happen if I upgrade the plugin without removing the platform, and it happens if I upgrade the plugin after removing the platform. Is that not enough to try to reproduce?
