### ISSUE TITLE
[IOS] salesforce only accepts http(s):// urls and webview doesn't allow to change iosScheme

### ISSUE THREAD

**Issue by webteambel** [ionic-team/cordova-plugin-ionic-webview#514]
Hello,

I was using ionic 3 and I was able to add cors (http://localhost:8080) to salesforce but now that we changed the application to ionic 5 i get always the cors error and the salesforce team can't add the url
ionic://

 ==> This thread shows how to add cors in salesforce and what format is accepted
https://help.salesforce.com/articleView?id=snapins_chat_cors_whitelist.htm&type=5

In addition iosScheme can't be changed :( 

Default value is ionic (ios
Values like http, https or file are not valid and will use default value instead.

I need to fix this issue ASAP, any help please

**cordova-plugin-ionic-webview: 4.1.3**
**ionic-native/ionic-webview": 5.20.0**
**angular/core: 8.2.7**
**ionic-native/core: 5.0.0**
**iOS: 13.3.1**

**Comment by goelectricstations** [comment]
same issue

**Comment by webteambel** [comment]
Please any solution :/  we really need it for the ios version. is there any update coming ?

**Comment by t3developer** [comment]
@GroupeBEL did you find any solution for this?
