### ISSUE TITLE
text indicator/caret moves along the screen while scrolling

### ISSUE THREAD

**Issue by sajallimbu** [ionic-team/cordova-plugin-ionic-webview#515]
When a text field is focused and scrolled. The indicator or caret of the text field moves along with the scroll over the navbar and not under it.
![92395ab8-130b-4660-a8be-713ea7199bb6](https://user-images.githubusercontent.com/40119982/74653015-698a0100-51af-11ea-8cf5-28aac890f8c0.gif)

**Comment by tmishutin** [comment]
Same problem here

**Comment by tryhardest** [comment]
Where you in debugger mode? We have seen and do see on device when using Chrome dev tools, but gone after disconnect.

**Comment by sajallimbu** [comment]
I was on debugger mode using Safari but the problem persists even when the device is disconnected.

**Comment by jcesarmobile** [comment]
this is an apple bug, nothing we can do about it
