### ISSUE TITLE
how to use / add this plugin to cordova?

### ISSUE THREAD

**Issue by matrixreal** [ionic-team/cordova-plugin-ionic-webview#516]
Hello,
i did add this plugin to my cordova game (not ionic) using this command 
**cordova plugin add cordova-plugin-ionic-webview**
build ok but i don't see any difference in performance

i use cordova android@8.1.0
android-minSdkVersion 19
android-targetSdkVersion 28

Any suggestion?

**Comment by sajallimbu** [comment]
#506

**Comment by matrixreal** [comment]
A Web View plugin for Cordova, focused on providing the highest performance experience for Ionic apps (but can be used with any Cordova app) ???

performance on what ?

**Comment by sajallimbu** [comment]
All the performance features provided by the latest evergreen webview on Android.

**Comment by matrixreal** [comment]
i did add this plugin and build ok
my game still get slow
if i use crosswalk plugin my game works better (but i don't want to use crosswalk because of the apk size etc...)
that why i want to use this one

**Comment by matrixreal** [comment]
> evergreen webview

do you think that this plugin will enhance performance of my html5 game using cordova android on mobile?
thanks

**Comment by tryhardest** [comment]
@matrixreal yes, and don't use Crosswalk. It's old, depreciated and not required anymore.

**Comment by matrixreal** [comment]
> @matrixreal yes, and don't use Crosswalk. It's old, depreciated and not required anymore.
ok thanks but how can i add this plugin?
just do cordova plugin add cordova-plugin-ionic-webview?
nothing else?

**Comment by sajallimbu** [comment]
yes just do cordova plugin add cordova-plugin-ionic-webview
after you uninstall your old webview

**Comment by forumics** [comment]
use xcode to build your project
view the xcode logs, you should see something like this
2020-03-14 11:58:50.257727+0800 FreeVoyeurCams[5171:81983] Apache Cordova native platform version 5.1.1 is starting.
2020-03-14 11:58:50.257958+0800 FreeVoyeurCams[5171:81983] Multi-tasking -> Device: YES, App: YES
2020-03-14 11:58:50.277967+0800 FreeVoyeurCams[5171:81983] **CDVWKWebViewEngine:** trying to inject XHR polyfill
2020-03-14 11:58:50.819458+0800 FreeVoyeurCams[5171:81983] **CDVWKWebViewEngine** will reload WKWebView if required on resume

**Comment by jcesarmobile** [comment]
The performance improvement is mainly on iOS because of the WKWebView, on Android you shouldn't notice any performance improvement. The webview is still the same, just make sure the system webview/chrome is up to date to benefit from latest chromium improvements.

**Comment by matrixreal** [comment]
> The performance improvement is mainly on iOS because of the WKWebView, on Android you shouldn't notice any performance improvement. The webview is still the same, just make sure the system webview/chrome is up to date to benefit from latest chromium improvements.
thanks for your reply
how to get the system webview/chrome is up to date to?

**Comment by jcesarmobile** [comment]
that's something the users should do, not the developer, just go to the Play store and update the system webview (android 5-6-10) or Chrome (android 7-8-9)

**Comment by matrixreal** [comment]
ok thanks for the clarification
