### ISSUE TITLE
Error with Canvas on iOS

### ISSUE THREAD

**Issue by vykimo** [ionic-team/cordova-plugin-ionic-webview#524]
I don't have a correct behavior for Canvas in Cordova with the cordova-plugin-ionic-webview.

With Cordova Ionic webview plugin (look at characters in cases):
https://nsa40.casimages.com/img/2020/03/09/200309090549841736.png

With Safari (correct behavior):
https://nsa40.casimages.com/img/2020/03/09/200309090549522257.png

I'm testing on iOS (iPhone 8+).

Could you help me?
Regards,

**Comment by jcesarmobile** [comment]
can you provide a sample app to reproduce it?

**Comment by vykimo** [comment]
Hmm, it's gonna be hard because my code is complex...
But did someone experienced weird behaviors in Cordova with canvas?... Maybe it could give me a path to follow

**Comment by jcesarmobile** [comment]
it doesn't need to be your code, a simpler app will work to
but I don't plan to look at your code anyway, just run the app to see the problem and see if I can make it look good by editing the plugin code, not your app code

**Comment by jcesarmobile** [comment]
closing since there was no response, feel free to reopen or create a new issue if you can provide a sample app where it can be reproduced
