### ISSUE TITLE
How to delete the file route in localhost?

### ISSUE THREAD

**Issue by vladimirmian** [ionic-team/cordova-plugin-ionic-webview#53]
when I build my ios app,it doesn't work,always tell that Failed to load resource: the server responded with a status of 404 (Not Found)
I check the console,this plugin add the device route back to the localhost,like this:
http://localhost:8080/Users/frontend/Library/Developer/CoreSimulator/Devices/2A8048D2-3545-4C52-842D-8920D46AABA3/data/Containers/Bundle/Application/5B2B8379-6F86-4D23-8CA5-F4FABE05A51A/xxxx.app/www/test/api/app/index/login?t=1512186355174,so I can't request any API of my APP.
So,can you tell me how to solve it?

**Comment by jcesarmobile** [comment]
Update to latest version, it now sets the www as the base folder, so you won't have all that `/Users/frontend/.../` part anymore
