### ISSUE TITLE
Deprecated API Usage - Apple will stop accepting submissions of new apps that use UIWebView APIs starting from April 2020

### ISSUE THREAD

**Issue by parvageshahariar** [ionic-team/cordova-plugin-ionic-webview#536]
I have just uploaded a build and apple send me the following email:

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of new apps that use UIWebView APIs starting from April 2020. See https://developer.apple.com/documentation/uikit/uiwebview for more information.

**Comment by dotNetkow** [comment]
We covered this deprecation in a blog post. [Complete details here](https://ionicframework.com/blog/understanding-itms-90809-uiwebview-api-deprecation/).

**Comment by ishaiavrahami** [comment]
What about PhoneGap Build?

**Comment by jcesarmobile** [comment]
You can ask on phonegap build forums, but there are plenty of questions already and no official answer. If I were you I would start looking for an alternative.
