### ISSUE TITLE
ionic url

### ISSUE THREAD

**Issue by ukenpachi** [ionic-team/cordova-plugin-ionic-webview#541]
```
<preference name="Scheme" value="https" />
<preference name="Hostname" value="localhost" />
```
however on ios getting this error
```
Failed to load resource: the server responded with a status of 404 ()        ionic://localhost/index.js.map 
```
how do i change it, so it does not use `ionic:// ` it should be `https://` like for android. IOS is using `ionic://`
is it possible to change if not what is the ideal solution? Thank you

**Comment by jcesarmobile** [comment]
https://github.com/ionic-team/cordova-plugin-ionic-webview/tree/master#iosscheme

> Values like http, https or file are not valid and will use default value instead.
