### ISSUE TITLE
ionic:localhost problem

### ISSUE THREAD

**Issue by federicolucca** [ionic-team/cordova-plugin-ionic-webview#548]
Hi,

I am going crazy to resolve an issue. 

All my GET from my app to server A are stopped by CORS
All my GET from my app to server B are OK

I check the .htaccess and is fine,very similar . One is Prestashop, the other is Wordpress.
The same app on the browser works fine, installed to the phone work only server B

They works fine in the last 4 months, now the supplier move the website to another hosting, but i check everythings and are fine on server-side. 

I not understand what happen, i think the server but i am not sure that le GET from app starts with ionic:localhost before this issue

Ionic:

   Ionic CLI                     : 5.4.16
   Ionic Framework               : @ionic/angular 4.11.10
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.0, (and 17 other plugins)

Utility:

   cordova-res (update available: 0.12.1) : 0.8.0
   native-run (update available: 1.0.0)   : 0.2.9

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.2
   NodeJS     : v10.15.3 (.nvm/versions/node/v10.15.3/bin/node)
   npm        : 6.13.0
   OS         : macOS Catalina
   Xcode      : Xcode 11.4.1 Build version 11E503a

**Comment by jcesarmobile** [comment]
sorry, looks like they did something wrong when configuring CORS, but it's not a problem on the plugin
