### ISSUE TITLE
Stuck on splashscreen becuase CORS issue again

### ISSUE THREAD

**Issue by mchenx** [ionic-team/cordova-plugin-ionic-webview#549]
It was fine when using xcode 10.1 and recently to upgrade my iOS app on app store, per apple's request, I have to upgrade to xcode to 11, and after that I fixed a few compile problems by upgrading cordova to 8.1.2 and some library ref issue.

The app then can be compiled, installed successfully, but running on either my phone or emulator failed, it was stuch on the splashscreen. By attach it to safari dev tool, I can see below error, localhost:8080 was blocked.

![image](https://user-images.githubusercontent.com/1550186/79679265-f7797b00-8236-11ea-8f8d-a4bb8de1c554.png)

I did add allow-navigation in the config file when upgrade from UIWebView to WKWebView two years ago, and it works fine all the way until now

![image](https://user-images.githubusercontent.com/1550186/79679335-bdf53f80-8237-11ea-9c59-ba6af660698b.png)

ionic info followed

Ionic:

   ionic (Ionic CLI)  : 4.10.3 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 6.4.0, ios 5.1.1
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 1.2.1, (and 14 other plugins)

System:

   Android SDK Tools : 26.1.1 
   ios-deploy        : 1.9.2
   NodeJS            : v8.16.0 (/usr/local/bin/node)
   npm               : 6.4.1
   OS                : macOS Mojave
   Xcode             : Xcode 11.3.1 Build version 11C505

full npm outdated info
![image](https://user-images.githubusercontent.com/1550186/79679367-14627e00-8238-11ea-8f98-92ecf3244871.png)

**Comment by jcesarmobile** [comment]
that url doesn't look good, you are doing something wrong
