### ISSUE TITLE
Version 1.2.1 (iOS 9) and UiWebView

### ISSUE THREAD

**Issue by ulver2812** [ionic-team/cordova-plugin-ionic-webview#550]
Hi , I must use the 1.2.1 version of this plugin in order to run the app on ios 9 with WKWebView enabled, if I use the latest version I can't run the app on ios 9. 

The version 1.2.1 contains references about UiWebView ?

I'm asking this because the App Store will no longer accept new apps using UIWebView as of April 2020 and app updates using UIWebView as of December 2020. Instead of UIWebView Apple requires WKWebView.

Here the Apple announcement:
https://developer.apple.com/news/?id=12232019b

**Comment by jcesarmobile** [comment]
we don't support v1 anymore

**Comment by ulver2812** [comment]
there's a way to use the latest version of this plugin with ios 9 ?

**Comment by jcesarmobile** [comment]
no
