### ISSUE TITLE
Reopen #345 iOS: fail to load gapi.client on V2.3.2+ 

### ISSUE THREAD

**Issue by xinfengmich** [ionic-team/cordova-plugin-ionic-webview#552]
Please reopen #345 
With V2.4.1,  gapi.client loads fine on browser,  android and iOS, but with any above version of cordova-plugin-ionic-webview, gapi.client is not able to loaded on iOS. 
This issue is blocking us to upgrade cordova-plugin-ionic-webview plugin while we try to fix "ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of app updates that use UIWebView APIs starting from December 2020." .
I uploaded a sample app here. 
[myApp.zip](https://github.com/ionic-team/cordova-plugin-ionic-webview/files/4522967/myApp.zip)
Really appreciate your help. Thanks.

**Comment by jcesarmobile** [comment]
I can reproduce, but this can't be fixed, is related to the apps using `ionic://` scheme for loading the content and we won't change it because it's required for fixing some problems.

You can use v2.x of the plugin as it uses http.

I've noticed that using `<preference name="iosScheme" value="app" />` makes the gapi.client to load, but then fails with `ReferenceError: Can't find variable: googleapis`, despite `googleapis` object is available.

**Comment by xinfengmich** [comment]
Due to "ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of app updates that use UIWebView APIs starting from December 2020." , we have to upgrade to the latest version. 

As you mentioned about using <preference name="iosScheme" value="app" /> ,  I tried and got same result as: 
[Log] Ionic Native: deviceready event fired after 988 ms (cordova.js, line 1540)
[Error] The source list for Content Security Policy directive 'script-src' contains an invalid source: ''report-sample''. It will be ignored.
[Error] The source list for Content Security Policy directive 'script-src' contains an invalid source: ''strict-dynamic''. It will be ignored.
[Error] ReferenceError: Can't find variable: googleapis
	(anonymous function) (proxy.html:8)
	(anonymous function) (googleapis.proxy.js:15:250)
	fa (googleapis.proxy.js:8:679)
	B (googleapis.proxy.js:15:234)
	(anonymous function) (googleapis.proxy.js:15:329)
	(anonymous function) (googleapis.proxy.js:15:390)
	Global Code (cb=gapi.loaded_0:1)

Would be CSP error causing not find googleapis?

**Comment by marcopes** [comment]
hi @xinfengmich, I have a similar problem, did you solve it?

**Comment by xinfengmich** [comment]
We changed the direction to use firebase function and googleapis to load
the google calendars now.
