### ISSUE TITLE
can we config default scheme for url starts with "//" on android

### ISSUE THREAD

**Issue by mchenx** [ionic-team/cordova-plugin-ionic-webview#553]
We are encountering an issuse that urls that have no scheme use "file://" by default. For example, "//g.alicdn.com/sd/nvc/1.1.112/guide.js", it seams to be "http://" by default on iOS with WKWebView, so it can fetch from "https://g.alicdn.com/sd/nvc/1.1.112/guide.js"

But on android, it is "file://" by default, so it becomes "file://g.alicdn.com/sd/nvc/1.1.112/guide.js".

Is there a way that we can config to use "http://" for urls starts with "//" on android platform when using this plugin?

cordova 8.1.2
cordova-android 6.4.0
cordova-plugin-ionic-webview  1.2.1

**Comment by jcesarmobile** [comment]
it's possible on version 2. 3 or 4, but not on 1
