### ISSUE TITLE
Unable to send an Ajax request

### ISSUE THREAD

**Issue by usamacode** [ionic-team/cordova-plugin-ionic-webview#555]
I have installed the plugin on cordova app for Android only. below is the config.xml configurations:
```
    <preference name="Scheme" value="https" />
    <preference name="Hostname" value="localhost" />
    <preference name="ResolveServiceWorkerRequests" value="true" />
    <preference name="MixedContentMode" value="2" />
``` 
All the Ajax requests with https or the CDNs like font-awesome are not getting sent and getting {readyState: 0} for the ajax requests.
Application and requests are working properly on browser but not on device.
Any suggestions, please?

**Comment by jcesarmobile** [comment]
can you provide a sample app?

**Comment by usamacode** [comment]
The issue has been resolved.
I have upgraded Cordova to the latest version, created a new project and installed the plugin. Everything worked fine!

Thanks,
