### ISSUE TITLE
ITMS-90809: Deprecated API Usage - New apps that use UIWebView

### ISSUE THREAD

**Issue by joaolori** [ionic-team/cordova-plugin-ionic-webview#559]
Hello everyone,
I am facing an issue with the new WKWebView webview.
I have proceed following the migration but I am stilling getting that message from apple.

**ionic info**

```
Ionic:

   Ionic CLI                     : 6.1.0 (C:\Users\TheMillionaire\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.0.7
   @angular-devkit/build-angular : 0.803.26
   @angular-devkit/schematics    : 8.3.26
   @angular/cli                  : 8.3.26
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : not available

Utility:

   cordova-res : 0.11.0
   native-run  : 0.3.0

System:

   Android SDK Tools : 26.1.1 (C:\Users\TheMillionaire\AppData\Local\Android\Sdk)
   NodeJS            : v13.8.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.13.6
```

**cordova plugins ls**

```
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-facebook4 6.4.0 "Facebook Connect"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-firebase-analytics 4.2.0 "FirebaseAnalyticsPlugin"
cordova-plugin-firebase-messaging 4.3.1 "FirebaseMessagingPlugin"
cordova-plugin-inappbrowser 3.2.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-media-capture 3.0.3 "Capture"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.6.4 "SocialSharing"
cordova-sqlite-storage 4.0.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
cordova-support-android-plugin 1.0.2 "cordova-support-android-plugin"
cordova-support-google-services 1.4.0 "cordova-support-google-services"
es6-promise-plugin 4.2.2 "Promise"
```

**config.xml**

 ` <preference name="WKWebViewOnly" value="true" />`

**cordova info**

```
cordova-lib@9.0.1 with:
  cordova-common@3.2.1
  cordova-create@2.0.0
  cordova-fetch@2.0.1
  cordova-serve@3.0.0

Environment:
  OS: win32
  Node: v13.8.0
  npm: 6.13.6

Plugins:
  cordova-plugin-androidx
  cordova-plugin-androidx-adapter
  cordova-plugin-camera
  cordova-plugin-device
  cordova-plugin-facebook4
  cordova-plugin-file
  cordova-plugin-file-transfer
  cordova-plugin-firebase-analytics
  cordova-plugin-firebase-messaging
  cordova-plugin-inappbrowser
  cordova-plugin-ionic-keyboard
  cordova-plugin-ionic-webview
  cordova-plugin-media-capture
  cordova-plugin-splashscreen
  cordova-plugin-statusbar
  cordova-plugin-whitelist
  cordova-plugin-x-socialsharing
  cordova-sqlite-storage
  cordova-support-android-plugin
  cordova-support-google-services
  es6-promise-plugin
```

**cordova -v**
`9.0.0 (cordova-lib@9.0.1)`

**ionic -v**
`6.1.0`

What I am missing here? 
If I lookup for UIWebView I do find a few entry's but I believe the XCODE compiler take in consideration the config xml flag in order to use the  WKWebView 
Some help would be very much appreciated.

Thanks

**Comment by dotNetkow** [comment]
It's not the WebView, but likely one of the Cordova plugins. Unfortunately it's difficult to determine which one is the cause. Which one likely uses a WebView or its APIs in some fashion?

cordova-plugin-inappbrowser is all set - you're on latest.
The "core" plugins are OK - like file, device, and camera.

My guess would be the Facebook plugin. Try removing that (and others, if needed) then resubmitting the app until it goes through.

**Comment by joaolori** [comment]
Hi,
Thanks for the reply, if I search by "UIWebView" this is what being returned (under **platforms/ios** folder)

![image](https://user-images.githubusercontent.com/3897677/80809025-c09d5080-8bb8-11ea-8870-a650331c7dbb.png)

Following your idea @dotNetkow , the in app browser should be fine, the only thing remaining is the social sharing, right? the others are under CordovaLIB, which I believe is also up to date,

**Comment by phiasco12** [comment]
did you ever find out what the issue was? I'm facing the same issue. did you find out the offending plugin that was using UIWebView?

**Comment by phiasco12** [comment]
> Hi,
> Thanks for the reply, if I search by "UIWebView" this is what being returned (under **platforms/ios** folder)
> 
> ![image](https://user-images.githubusercontent.com/3897677/80809025-c09d5080-8bb8-11ea-8870-a650331c7dbb.png)
> 
> Following your idea @dotNetkow , the in app browser (in orange) should be fine, the only thing remaining is the social sharing, right? (in brown) the others are under CordovaLIB (in red), which I believe is also up to date,
> 
> **EDIT**:
> I raised a question on social sharing, ask for confirmation if the plugin works with the WKWebView webview [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#1098](https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/issues/1098)

did you ever find out what the issue was? I'm facing the same issue. did you find out the offending plugin that was using UIWebView?

**Comment by jcesarmobile** [comment]
this plugin doesn't use UIWebView, it uses WKWebView, the UIWebView usage comes from one of your plugins, probably firebase or facebook

**Comment by MLuan** [comment]
Hi, @joaolori  have you a solution? I'm facing this same problem.

**Comment by jorojas** [comment]
Oh My God dear people. Please tell me that you fixed this. I followed the steps on this link and can't get apple to accept my ionic v3 app.

https://ionicframework.com/blog/understanding-itms-90809-uiwebview-api-deprecation/

**Comment by joaolori** [comment]
Hello, 
For those facing the issue, the problem was one of the plugins was not compatible with the new webview so was trigger apple warning. The plugin was  https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/issues/1098
