### ISSUE TITLE
Enhancement Request -  Expose Default Webview PhotoPicker for Input file.

### ISSUE THREAD

**Issue by JohnRSim** [ionic-team/cordova-plugin-ionic-webview#560]
Within Mobile Chrome browser - selecting the following html inputs displays the photo picker and source selection released 2 years ago in Chrome 64.
```html
<input type="file" accept="image/*">
```
![screenshot_20200501-150508_android_system](https://user-images.githubusercontent.com/364208/80816569-a9199400-8bc7-11ea-8d16-d41ac3057446.jpg)

```html
<input type="file" accept="image/*;capture=camera">
```
![image](https://user-images.githubusercontent.com/364208/80816117-d4e84a00-8bc6-11ea-8fcc-9d2fed686a28.png)

The old xWalk project I believe worked on enhancing their webview to support this... Unfortunately intel no longer support the project.

Would it be possible to enhance the Ionic webview to support this capability within cordova? 

This is an old post but maybe something like this 
https://androidexample.com/Open_File_Chooser_With_Camera_Option_In_Webview_File_Option/index.php?view=article_discription&aid=128&aaid=148

here is the xwalk version
https://androidexample.com/Open_File_Chooser_With_Camera_Option_In_Webview_File_Option/index.php?view=article_discription&aid=128&aaid=148

**Comment by JohnRSim** [comment]
Looks like the only other option that other developers are using is by currently redeveloping the functionality with the DOM and camera plugin.

https://medium.com/enappd/image-cropper-in-ionic-4-7b76f1153ad9

**Comment by JohnRSim** [comment]
@dirkgroenen have you created anything similar to this :)

**Comment by jcesarmobile** [comment]
that's really cordova-android's job, pretty sure it's already reported on its github repository
