### ISSUE TITLE
Webview not syncing cookies on first launch IOS

### ISSUE THREAD

**Issue by juliannehalversen** [ionic-team/cordova-plugin-ionic-webview#564]
I have looked everyone where a solution to this and everything I've tried has either been outdated or hasn't solved my issue. I’m using Ionic 5 with Angular and Cordova. My app works perfect when testing on browsers and Android devices but when it’s first installed on my device (iphone) through Xcode the cookies are not received or sent properly. My app uses cookie based authentication so when I get my login response it will have a cookie that should be sent with all subsequent requests. However, on the first launch after install I cannot login at all. When I exit and relaunch my app it works perfectly. I believe this is due to the webview not syncing cookies correctly. I have tried all the solutions in this post: https://github.com/Telerik-Verified-Plugins/WKWebView/issues/247 and https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/22 but the plugins are so outdated I can’t get it to work properly. There are tons of questions for this bug but I can't seem to find an answer that works.

I have been looking for a solution for weeks and am completely stuck and exhausted at this point.  Any help would be greatly appreciated! I will provide whatever code or screenshots is helpful, just let me know what I should share.

**Comment by jcesarmobile** [comment]
it's a known issue, as you pointed out it's already reported on #22

**Comment by juliannehalversen** [comment]
Yes, it's a known issue. What I'm wondering is if there are any workaround for this bug for any updates to fix it (that aren't from 5 years ago).

**Comment by samulla** [comment]
I am facing the same issue as well. Need help!

**Comment by juliannehalversen** [comment]
> I am facing the same issue as well. Need help!

Here is the link to what I ending up doing to fix it: https://github.com/lucky3491/cordova-plugin-wkwebview-inject-cookie/issues/1#issuecomment-633614645

**Comment by tobyerbailey** [comment]
I am not sure it is 100% relevant to this issue but I found the penultimate paragraph of this page fixed my issue:
[App bound domains](https://webkit.org/blog/10882/app-bound-domains/)

Including the _NSCrossWebsiteTrackingUsageDescription_ key in the iOS info.plist and then finding the application in the iOS settings application and enabling **cross website tracking**  fixed it for my application. It does require user intervention but also fixed the authentication cookie issue for me.
