### ISSUE TITLE
[blocked] Access to geolocation was blocked over insecure connection to ionic://localhost.

### ISSUE THREAD

**Issue by arielhasidim** [ionic-team/cordova-plugin-ionic-webview#565]
👋
I have Cordova-Angular project (not Ionic), and I'm trying to use cordova-geolocation plugin to get current-location and device-orientation (compass heading) with a "location.service" I created.
Im using:
- @angular/cli 7.3.9
- cordova-lib@9.0.1
  - platforms:
    - android 8.1.0
    - ios 5.1.1
  - plugins (shorten):
    - cordova-plugin-ionic-webview 4.1.1 "cordova-plugin-ionic-webview"
    - cordova-plugin-geolocation 4.0.2 "Geolocation"

It used to work both on android and ios, now on ios, I get the location, but with an error for device orientation.

> [blocked] Access to geolocation was blocked over insecure connection to ionic://localhost.

> Geolocation PositionError {code: 1, message: "Origin does not have permission to use Geolocation service"

in my *.plist file:
<img width="769" alt="VLNcR" src="https://user-images.githubusercontent.com/23483971/81278307-29c01080-905e-11ea-9cfe-db1c7bb39d01.png">

My location.service:
```
import {Injectable} from '@angular/core';
import {BehaviorSubject, combineLatest, fromEvent, Observable, of, timer} from 'rxjs';
import {HttpClient} from '@angular/common/http';
import {map, switchMap} from 'rxjs/operators';
import { Globals } from '../globals';

export interface DefiLocation {
  accuracy: number;
  altitude: number;
  altitudeAccuracy: number;
  heading: number;
  latitude: number;
  longitude: number;
  speed: number;
  compass: number;
}

@Injectable({
  providedIn: 'root'
})
export class LocationService {
  errorMessage$: string;
  currentLocation$: BehaviorSubject<{
    accuracy?: number,
    altitude: number,
    altitudeAccuracy: number,
    heading: number,
    latitude: number,
    longitude: number,
    speed: number
  }> = new BehaviorSubject({
    accuracy: 0,
    altitude: 0,
    altitudeAccuracy: 0,
    heading: 0,
    latitude: 32.5,
    longitude: 35,
    speed: 0,
  });

  currentCompass$: BehaviorSubject<number> = new BehaviorSubject(0);
  currentCompass: number = 0;
  currentPosition: {
    accuracy: 0,
    altitude: 0,
    altitudeAccuracy: 0,
    heading: 0,
    latitude: 32.5,
    longitude: 35,
    speed: 0,
  };
  locationTimer;
  sendLocationError: boolean = true;

  constructor(public globals: Globals) {
    this.isCurrentPosition$.next(true);
    this.trackMe();
  }

  private trackMe() {
    if (this.globals.iphone) {
        window.addEventListener('deviceorientation', (event) => {
          this.currentCompass$.next(Math.round(event['webkitCompassHeading']));
        });
      // }
    } else {
      window.addEventListener('deviceorientationabsolute', (event) => {
        this.currentCompass$.next(360 - Math.round(event['alpha']));
      }, true);
    }


    if (navigator.geolocation) {
      this.locationTimer = timer(0, 100).subscribe(tick => {
        navigator.geolocation.getCurrentPosition((position) => {
          this.currentLocation$.next(position.coords);
          this.isCurrentPosition$.next(true);
          this.sendLocationError = true;
        }, (err) => {
          this.isCurrentPosition$.next(false);
          this.sendError(err.message);
          console.log(err);
          this.errorMessage$ = err.message;
          console.log(this.errorMessage$);
        }, {
          enableHighAccuracy: true
        });
      });

    } else {
      alert('Geolocation is not supported by this browser.');
      this.sendError('navigator.geolocation = null ("Geolocation is not supported by this browser.")');
    }
  }

  getCurrentLocation$(): Observable<DefiLocation> {
    return combineLatest(this.currentCompass$.asObservable(), this.currentLocation$.asObservable())
      .pipe(
        map(([compass, location]) => {
            return {
              longitude: location.longitude,
              latitude: location.latitude,
              accuracy: location.accuracy,
              altitude: location.altitude,
              altitudeAccuracy: location.altitudeAccuracy,
              heading: location.heading,
              speed: location.speed,
              compass
            };
          }
        ));
  }

  sendError(error) {
    if (this.sendLocationError) {
      this.sendLocationError = false;
      window['cordova'].plugins.firebase.analytics.logEvent('user_location_failed', {param1: error});
      setTimeout(function() { this.sendLocationError = true; }, 5000);
    }
  }
}
```

### Detailed logs:
When I run `cordova build ios`, and then run it from Xcode on my iPhone (ios 13.4.1) and check Safari's develop console: 
<img width="993" alt="qi8Fj" src="https://user-images.githubusercontent.com/23483971/81278533-7d325e80-905e-11ea-816b-78ffd6d0e551.png">
<img width="1287" alt="mxqf2" src="https://user-images.githubusercontent.com/23483971/81278546-815e7c00-905e-11ea-93d7-cdebdf7f6f8f.png">

Xcode console:

> 2020-05-07 12:27:07.181187+0300 איפה דפי?[19454:3874343] <Warning>: Please set a value for FacebookAutoLogAppEventsEnabled. Set the flag to TRUE if you want to collect app install, app launch and in-app purchase events automatically. To request user consent before collecting data, set the flag value to FALSE, then change to TRUE once user consent is received. Learn more: https://developers.facebook.com/docs/app-events/getting-started-app-events-ios#disable-auto-events.
> 2020-05-07 12:27:07.181288+0300 איפה דפי?[19454:3874343] <Warning>: You haven't set a value for FacebookAdvertiserIDCollectionEnabled. Set the flag to TRUE if you want to collect Advertiser ID for better advertising and analytics results. To request user consent before collecting data, set the flag value to FALSE, then change to TRUE once user consent is received. Learn more: https://developers.facebook.com/docs/app-events/getting-started-app-events-ios#disable-auto-events.
> 2020-05-07 12:27:07.185978+0300 איפה דפי?[19454:3874544]  - <AppMeasurement>[I-ACS036002] Analytics screen reporting is enabled. Call +[FIRAnalytics setScreenName:setScreenClass:] to set the screen name or override the default screen class name. To disable screen reporting, set the flag FirebaseScreenReportingEnabled to NO (boolean) in the Info.plist
> 2020-05-07 12:27:08.621269+0300 איפה דפי?[19454:3874343] Apache Cordova native platform version 5.1.1 is starting.
> 2020-05-07 12:27:08.621415+0300 איפה דפי?[19454:3874343] Multi-tasking -> Device: YES, App: YES
> 2020-05-07 12:27:08.638170+0300 איפה דפי?[19454:3874343] 
> 
> Started backup to iCloud! Please be careful.
> Your application might be rejected by Apple if you store too much data.
> For more information please read "iOS Data Storage Guidelines" at:
> https://developer.apple.com/icloud/documentation/data-storage/
> To disable web storage backup to iCloud, set the BackupWebStorage preference to "local" in the Cordova config.xml file
> 2020-05-07 12:27:08.647985+0300 איפה דפי?[19454:3874343] CDVWKWebViewEngine: trying to inject XHR polyfill
> 2020-05-07 12:27:08.773257+0300 איפה דפי?[19454:3874343] WF: === Starting WebFilter logging for process איפה דפי?
> 2020-05-07 12:27:08.773304+0300 איפה דפי?[19454:3874343] WF: _userSettingsForUser mobile: {
>     filterBlacklist =     (
>     );
>     filterWhitelist =     (
>     );
>     restrictWeb = 1;
>     useContentFilter = 0;
>     useContentFilterOverrides = 0;
>     whitelistEnabled = 0;
> }
> 2020-05-07 12:27:08.773333+0300 איפה דפי?[19454:3874343] WF: _WebFilterIsActive returning: NO
> 2020-05-07 12:27:08.794455+0300 איפה דפי?[19454:3874343] CDVWKWebViewEngine will reload WKWebView if required on resume
> 2020-05-07 12:27:08.794528+0300 איפה דפי?[19454:3874343] Using Ionic WKWebView
> 2020-05-07 12:27:08.794942+0300 איפה דפי?[19454:3874343] [CDVTimer][console] 0.053048ms
> 2020-05-07 12:27:08.795053+0300 איפה דפי?[19454:3874343] [CDVTimer][handleopenurl] 0.051975ms
> 2020-05-07 12:27:08.796433+0300 איפה דפי?[19454:3874343] Unlimited access to network resources
> 2020-05-07 12:27:08.796555+0300 איפה דפי?[19454:3874343] Unlimited access to network resources
> 2020-05-07 12:27:08.796606+0300 איפה דפי?[19454:3874343] [CDVTimer][intentandnavigationfilter] 1.518965ms
> 2020-05-07 12:27:08.796679+0300 איפה דפי?[19454:3874343] [CDVTimer][gesturehandler] 0.039935ms
> 2020-05-07 12:27:08.796765+0300 איפה דפי?[19454:3874343] [CDVTimer][inappbrowser] 0.057936ms
> 2020-05-07 12:27:08.797147+0300 איפה דפי?[19454:3874343] [CDVTimer][uiinappbrowser] 0.352979ms
> 2020-05-07 12:27:08.797444+0300 איפה דפי?[19454:3874343] [CDVTimer][wkinappbrowser] 0.250936ms
> 2020-05-07 12:27:08.798355+0300 איפה דפי?[19454:3874343] [CDVTimer][camerapreview] 0.876069ms
> 2020-05-07 12:27:08.798635+0300 איפה דפי?[19454:3874343] Starting Facebook Connect plugin
> 2020-05-07 12:27:08.798679+0300 איפה דפי?[19454:3874343] [CDVTimer][facebookconnectplugin] 0.286937ms
> 2020-05-07 12:27:08.799848+0300 איפה דפי?[19454:3874343] [CDVTimer][file] 1.121998ms
> 2020-05-07 12:27:08.800184+0300 איפה דפי?[19454:3874343] Starting Firebase Analytics plugin
> 2020-05-07 12:27:08.800426+0300 איפה דפי?[19454:3874544] 6.3.0 - [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) to your application initialization. Read more: https://goo.gl/ctyzm8.
> 2020-05-07 12:27:08.856879+0300 איפה דפי?[19454:3874545] 6.3.0 - [Firebase/Analytics][I-ACS023007] Analytics v.60002000 started
> 2020-05-07 12:27:08.857628+0300 איפה דפי?[19454:3874343] [CDVTimer][firebaseanalytics] 57.731986ms
> 2020-05-07 12:27:08.857999+0300 איפה דפי?[19454:3874545] 6.3.0 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
> 2020-05-07 12:27:08.859820+0300 איפה דפי?[19454:3874343] [CDVTimer][splashscreen] 2.135038ms
> 2020-05-07 12:27:08.860861+0300 איפה דפי?[19454:3874343] [CDVTimer][statusbar] 0.965953ms
> 2020-05-07 12:27:08.866959+0300 איפה דפי?[19454:3874343] [CDVTimer][universallinks] 6.036997ms
> 2020-05-07 12:27:08.867138+0300 איפה דפי?[19454:3874343] [CDVTimer][moforceappclose] 0.089049ms
> 2020-05-07 12:27:08.867170+0300 איפה דפי?[19454:3874343] [CDVTimer][TotalPluginStartup] 72.317004ms
> 2020-05-07 12:27:08.961708+0300 איפה דפי?[19454:3874343] FB Hybrid app events are enabled
> 2020-05-07 12:27:09.234344+0300 איפה דפי?[19454:3874343] IAB.close() called but it was already closed.
> 2020-05-07 12:27:09.234411+0300 איפה דפי?[19454:3874343] IAB.close() called but it was already closed.
> 2020-05-07 12:27:09.508346+0300 איפה דפי?[19454:3874579] [] tcp_input [C3.1:3] flags=[R] seq=241775220, ack=0, win=0 state=CLOSED rcv_nxt=241775220, snd_una=3103823183
> 2020-05-07 12:27:09.509557+0300 איפה דפי?[19454:3874579] [] tcp_input [C3.1:3] flags=[R] seq=241775220, ack=0, win=0 state=CLOSED rcv_nxt=241775220, snd_una=3103823183
> 2020-05-07 12:27:09.510460+0300 איפה דפי?[19454:3874579] [] tcp_input [C2.1:3] flags=[R] seq=280409344, ack=0, win=0 state=CLOSED rcv_nxt=280409344, snd_una=567355058
> 2020-05-07 12:27:09.511993+0300 איפה דפי?[19454:3874579] [] tcp_input [C2.1:3] flags=[R] seq=280409344, ack=0, win=0 state=CLOSED rcv_nxt=280409344, snd_una=567355058
> 2020-05-07 12:27:09.767806+0300 איפה דפי?[19454:3874579] [] tcp_input [C4.1:3] flags=[R] seq=20110131, ack=0, win=0 state=CLOSED rcv_nxt=20110131, snd_una=1907361087
> 2020-05-07 12:27:09.768062+0300 איפה דפי?[19454:3874579] [] tcp_input [C4.1:3] flags=[R] seq=20110131, ack=0, win=0 state=CLOSED rcv_nxt=20110131, snd_una=1907361087
> 2020-05-07 12:27:10.044980+0300 איפה דפי?[19454:3874343] WARN: 
> It looks like you're using the development build of the Firebase JS SDK.
> When deploying Firebase apps to production, it is advisable to only import
> the individual SDK components you intend to use.
> 
> For the module builds, these are available in the following manner
> (replace <PACKAGE> with the name of a component - i.e. auth, database, etc):
> 
> CommonJS Modules:
> const firebase = require('firebase/app');
> require('firebase/<PACKAGE>');
> 
> ES Modules:
> import firebase from 'firebase/app';
> import 'firebase/<PACKAGE>';
> 
> Typescript:
> import * as firebase from 'firebase/app';
> import 'firebase/<PACKAGE>';
> 2020-05-07 12:27:10.045085+0300 איפה דפי?[19454:3874343] this is cordova
> 2020-05-07 12:27:10.045142+0300 איפה דפי?[19454:3874343] 76
> 2020-05-07 12:27:10.045192+0300 איפה דפי?[19454:3874343] its right here:[object Object]
> 2020-05-07 12:27:10.045247+0300 איפה דפי?[19454:3874343] ready
> 2020-05-07 12:27:10.045424+0300 איפה דפי?[19454:3874343] ios
> 2020-05-07 12:27:10.046297+0300 איפה דפי?[19454:3874343] Found resource '/private/var/containers/Bundle/Application/777C5D2E-1E12-48A9-96E7-3778E5D08796/איפה דפי?.app/www/assets/sound/cpr.mp3' in the web folder.
> 2020-05-07 12:27:10.441984+0300 איפה דפי?[19454:3874545] [] tcp_input [C5.1:3] flags=[R] seq=1560651185, ack=0, win=0 state=CLOSED rcv_nxt=1560651185, snd_una=610067767
> 2020-05-07 12:27:10.463819+0300 איפה דפי?[19454:3874545] [] tcp_input [C5.1:3] flags=[R] seq=1560651185, ack=0, win=0 state=CLOSED rcv_nxt=1560651185, snd_una=610067767
> 2020-05-07 12:27:12.470954+0300 איפה דפי?[19454:3874343] {"createdAt":
>

**Comment by jcesarmobile** [comment]
you are using web geolocation instead of native geolocation, so probably the geolocation plugin was not correctly installed, try removing and adding ios platform.

**Comment by arielhasidim** [comment]
> you are using web geolocation instead of native geolocation, so probably the geolocation plugin was not correctly installed, try removing and adding ios platform.

Tried it, didn't work.
Why close so fast?

**Comment by jcesarmobile** [comment]
because it's clearly a problem in your app not in the plugin, github issues are for reporting real issues on the plugin, and this is not the case, sorry, you can ask on ionic forums or cordova slack

**Comment by arielhasidim** [comment]
thank you

> because it's clearly a problem in your app not in the plugin, github issues are for reporting real issues on the plugin, and this is not the case, sorry, you can ask on ionic forums or cordova slack
