### ISSUE TITLE
scalesPageToFit causes app to be stuck on splashscreen

### ISSUE THREAD

**Issue by sajallimbu** [ionic-team/cordova-plugin-ionic-webview#566]
I came across this issue recently and I scoured the net for possible solutions but could not find any mention of this particular problem. I studied the objective c code and commented out the scalesPageToFit part in MainViewController.m which seems to fix the problem and i have not run into any problem since. But, this is a pretty hacky solution and i'm looking for a legit proper way to solve this issue.

**Comment by jcesarmobile** [comment]
`scalesPageToFit` is not part of this plugin, so closing as invalid
