### ISSUE TITLE
Cookies are not persisting in http calls (android & IOS)

### ISSUE THREAD

**Issue by razam217** [ionic-team/cordova-plugin-ionic-webview#567]
I'm using latest version of this plugin. After adding this plugin, cookies are not working for both 
Android and IOS.

Cordova 9.0.0
Cordova-ios 5.1.1
Cordova-android 8.1.0

Not sure, what else Info should I share in order to understand the problem. Please let me know what else I need to share?

**Comment by razam217** [comment]
In Android it started working after I set $http.default.withCredentials=true.
There were some server side changes required to accomplish this, so I did that too. But still IOS is not persisting the cookies.

**Comment by razam217** [comment]
After investigation, I found that after setting withCredentials=true, cookies is working on IOS as well. It is only not working on simulators. :)

**Comment by rsgone** [comment]
@razam217 for simulators, Add following line inside <platform name="ios"></platform> of config.xml file.

<preference name="Hostname" value="your-domain" />

**Comment by razam217** [comment]
Actually even after setting withCredentials=true, the issue was still there. Its an issue with IOS Cookies Handling in WKWebView. My issue is resolved via this plugin:
https://github.com/CWBudde/cordova-plugin-wkwebview-inject-cookie
