### ISSUE TITLE
Access webview's content from the app

### ISSUE THREAD

**Issue by markopolojarvi** [ionic-team/cordova-plugin-ionic-webview#568]
Is there a way to access the webview's content?

For example, if I open foobar.com in a webview, can I somehow execute javascript in the foobar.com context and then pass the results back to the app?

**Comment by jcesarmobile** [comment]
the app is loaded in the webview, if you load a different website then it's not your app anymore and you can't communicate

you can probably use InAppBrowser plugin for that
