### ISSUE TITLE
deviceready not fired in Android 4.4 if scheme has changed

### ISSUE THREAD

**Issue by dpalou** [ionic-team/cordova-plugin-ionic-webview#570]
We found this error in a complex project, and it was quite hard to find what caused the issue because it's a combination of things. This is how you can reproduce the problem:

1. Create a new Cordova project (it doesn't have to be an Ionic project).
2. Add _cordova-plugin-ionic-webview_ plugin (we have version 4.2.1).
3. Add _cordova-plugin-device_ plugin (we have version 2.0.3).
4. In config.xml, change the scheme for Android. E.g.: `<preference name="Scheme" value="myscheme" />`. Update the CSP and _allow-navigation_ with the new scheme.
5. Run the app in an Android 4.4 or Android 5 device and check that deviceready isn't fired (the app will display the message "Connecting to device" forever).

I created an example project with this problem:

https://github.com/dpalou/ionic-webview-deviceready-error

I added the new schema to the CSP and also to allow-navigation, but the error still happens.

Please notice this app is working fine in our Android 5.0 device, but not in our Android 4.4 device or in simulators with Android 4.4 or 5. I guess it depends on the ROM. It also works fine in Android 8, 9 or 10 (haven't checked 6 and 7).

If I leave the default scheme it works fine in all devices. Also, removing the cordova-plugin-device plugin also makes it work.

Am I missing any configuration to make this work? I haven't found anything in the documentation besides updating allow-navigation, so I guess this is a bug caused by the combination of the two plugins.

**Comment by jcesarmobile** [comment]
next release of the plugin will drop support Android 4.4 support and google engineers have told us to discourage people from using a custom scheme, so closing as won't fix
