### ISSUE TITLE
cordova-plugin-ignore-mute-switch issue with this plugin!

### ISSUE THREAD

**Issue by phiasco12** [ionic-team/cordova-plugin-ionic-webview#572]
Hi,

I'm using this plugin and it works a treat but its conflicting with **cordova-plugin-ignore-mute-switch** plugin.

for some reason, when i use **cordova-plugin-ignore-mute-switch** with **cordova-plugin-ionic-webview**, the **cordova-plugin-ignore-mute-switch** doesn't work properly and the audios stop after a few seconds but when i remove the **cordova-plugin-ionic-webview** plugin from my project, **cordova-plugin-ignore-mute-switch** starts working fine!

is this a known issue and is there any workaround for this?

Thanks

**Comment by jcesarmobile** [comment]
that's probably because that "trick" the plugin uses to keep the audio running only works on UIWebView and this plugins uses WKWebView. There is an issue reported on Apple's issue tracker about audio stopping on WKWebView.
