### ISSUE TITLE
Restoring the webview's history stack/current url when reloading the app

### ISSUE THREAD

**Issue by pschinis** [ionic-team/cordova-plugin-ionic-webview#573]
I'm using version 4.1.2 of the plugin and I've noticed that (at least on Android) when the app's process gets killed (either by going into the background or the app gets closed by the user), the current history/url of the webview gets lost. So the next time you open the app it always opens to the base url and you have to navigate back to wherever you were. Is there an easy way to preserve the webview's history/current page like how mobile Chrome and other browsers do or is this something I have to develop myself?

**Comment by jcesarmobile** [comment]
you'll have to store the url every time the app navigates and then listen for cordova events to restore it, not a plugin issue, closing
