### ISSUE TITLE
Issue after migrating to WKWebView - application fails to start

### ISSUE THREAD

**Issue by NijsTom** [ionic-team/cordova-plugin-ionic-webview#575]
Since upgrading from UIWebView to WKWebView using this plugin, the application fails to start on iOS.

Testing with the preference name="AutoHideSplashScreen" gave the following results:

true resulted in the application being stuck on a white screen
false resulted in the application being stuck on the splash screen

In the logs, the following error is printed right before ** BUILD SUCCEEDED **, not sure if it's relevant but here it is:

RegisterExecutionPolicyException /path/to/app/platforms/ios/build/emulator/Example.app (in target 'Example' from project 'Example')
    cd /path/to/app/platforms/ios
    builtin-RegisterExecutionPolicyException /path/to/app/platforms/ios/build/emulator/Example.app
note: Execution policy exception registration failed and was skipped: Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted" (in target 'Example' from project 'Example')

The following plugins are installed:

    <plugin name="cordova-plugin-whitelist" spec="1.3.3" />
    <plugin name="cordova-plugin-statusbar" spec="2.4.2" />
    <plugin name="cordova-plugin-splashscreen" spec="5.0.2" />
    <plugin name="cordova-plugin-ionic-webview" spec="^4.0.0" />
    <plugin name="cordova-plugin-ionic-keyboard" spec="^2.0.5" />

I attempted tests with the following preferences, to no avail as well:
WKPort
iosScheme

both in tandem with my setup (ionic://localhost:8100)

I'm happy to supply any other information, please ask for whatever you need.

**Comment by jcesarmobile** [comment]
white screens are usually caused by javascript errors, you should debug your app using safari remote inspector
can you provide a sample app?

**Comment by jcesarmobile** [comment]
closing since there was no response
