### ISSUE TITLE
Cookie are not returned in AjaxCall using WKWebView in Cordova app

### ISSUE THREAD

**Issue by Developer3010** [ionic-team/cordova-plugin-ionic-webview#584]
Hi, I recently migrated to WKWebView since UIWebView has been deprecated.
With the new view I am having a lot of problems, especially regarding cookies during ajax calls, which are not maintained and consequently I cannot login to my app.
Can anyone tell me if they can somehow be saved so that the session_id is always the same and does not change with every single call?

I'm using:;
"cordova-ios": "^5.1.1",
"cordova-plugin-wkwebview-engine": "^1.2.1"
"cordova-plugin-wkwebview-inject-cookie": "1.0.6"

iPhone 6s -> 13.4
iPhone 11 -> 13.5

xcode 11.4.1

**Comment by jcesarmobile** [comment]
`cordova-plugin-wkwebview-engine` is a different plugin (https://github.com/apache/cordova-plugin-wkwebview-engine), this is `cordova-plugin-ionic-webview`
