### ISSUE TITLE
Android Hostname missing from request Origin, causing different origins between ios and android

### ISSUE THREAD

**Issue by ShayShaked** [ionic-team/cordova-plugin-ionic-webview#588]
Hi,
We are migrating our ionic 2 app to ionic 4.
With the latest ios requirements for migrating to WKwebview, ios scheme must differ from http, so we want to unify both android and ios platforms origins to be the same (scheme://Hostname), so that we wont need to deal with 2 different origins.

ios default is ionic://localhost
android default is http://localhost.

problem is, when assigning
`<preference name="Scheme" value="httpmyscheme" />` **for android**
`<preference name="iosScheme" value="httpmyscheme" />` **for ios**
 and `<preference name="Hostname" value="myhostname" />` in config.xml, **the origin on android devices is always "httpmyscheme://" without the hostname "myhostname"** defined in config.xml .
In ios devices, it works perfectly fine.

Ionic:

   Ionic CLI                     : 5.4.16 (C:\Users\Shay\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.7.1
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 9.1.0-dev
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 7 other plugins)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.15.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10

**Comment by jcesarmobile** [comment]
This is a webview/chromium "feature", I reported it long ago and they closed as won't fix because "it works as expected" according to them. 
There is nothing we can do about it and google engineers have told us to discourage people from using custom schemes on Android, see https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/484
