### ISSUE TITLE
(iOS) Open local html content

### ISSUE THREAD

**Issue by ternblom** [ionic-team/cordova-plugin-ionic-webview#589]
Due to apple's announcement to use WKWebview I've been migrating to the las version of ionic angular, the app has a functionality to open a local html file using InAppBrowser.

## Requirements

1. Download zip file from X endpoint to the app local storage
2. Unzip it
3. Open the downloaded website (html page with JS and CSS) using InAppBrowser

## Problem
When I try to open the file index.html after step (3) I got this problem.

**didStartProvisionalNavigation**
**webView:didFailProvisionalNavigation - -1002: unsupported URL**

## Information

**File Structure**

sample.zip
- style.css
- main.js
- index.html

**Plugins**

App previous version plugins
- cordova-plugin-file 6.0.1 "File"
- cordova-plugin-inappbrowser 3.1.0 "InAppBrowser"
- cordova-plugin-ionic-webview 2.4.0 "cordova-plugin-ionic-webview"
- cordova-plugin-whitelist 1.3.3 "Whitelist"
- ionic-plugin-deeplinks 1.0.20 "Ionic Deeplink Plugin"

App new version plugins
- cordova-plugin-file 6.0.2 "File"
- cordova-plugin-inappbrowser 4.0.0 "InAppBrowser"
- cordova-plugin-ionic-webview 4.2.1 "cordova-plugin-ionic-webview"
- cordova-plugin-whitelist 1.3.3 "Whitelist"

Using webview 2.4.0 (window.Ionic.WebView.convertFileSrc) **everything work perfectly**
Local file
file:///var/mobile/Containers/Data/Application/UUID/Documents/Content/sample/index.html
Url compatible with local server
http://localhost:8080/_app_file_/var/mobile/Containers/Data/Application/UUID/Documents/Content/sample/index.html 

Using webview 4.2.1 (window.Ionic.WebView.convertFileSrc) **problem**
Local file
file:///var/mobile/Containers/Data/Application/UUID/Documents/Content/sample/index.html

Url compatible with local server
ionic://localhost/_app_file_/var/mobile/Containers/Data/Application/UUID/Documents/Content/sample/index.html

**Version**

Ionic info:

   Ionic CLI                     : 6.10.0 (/node/v12.18.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.2.1
   @angular-devkit/build-angular : 0.901.8
   @angular-devkit/schematics    : 9.1.8
   @angular/cli                  : 9.1.8
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 14 other plugins)

Utility:

   cordova-res : 0.14.0
   native-run                             : 1.0.0

System:

   Android SDK Tools : 26.1.1 (/Library/Android/sdk)
   ios-deploy        : 1.10.0
   ios-sim           : 8.0.2
   NodeJS            : v12.18.0 (/node/v12.18.0/bin/node)
   npm               : 6.14.5
   OS                : macOS Catalina
   Xcode             : Xcode 11.3.1 Build version 11C504

## Question

I've been trying to figure this out for several days but can't get it to work. Any idea how to solve it?

**Comment by jcesarmobile** [comment]
InAppBrowser can't handle ionic:// urls, that's not an Ionic WebView bug, it's an InAppBrowser limitation, you should open the equivalent file:// url
