### ISSUE TITLE
ATS with Xcode 9.2

### ISSUE THREAD

**Issue by ycbayrak** [ionic-team/cordova-plugin-ionic-webview#59]
I'm still getting  this error even my API using HTTPS.
`ERROR: {"_body":{"isTrusted":true},"status":0,"ok":false,"statusText":"","headers":{},"type":3,"url":null}`

I've installed `cordova-plugin-whitelist` plugin and i've this configurations on my config.xml
```
<access allows-arbitrary-loads-for-media="true" allows-arbitrary-loads-in-web-content="true" origin="https://api.example.com/*" />
<access allows-arbitrary-loads-for-media="true" allows-arbitrary-loads-in-web-content="true" origin="https://api.example.com/token/" />
 ```

**Comment by sarawutl** [comment]
same error but working in https not http
but I'm want using in http

**Comment by ycbayrak** [comment]
It's not possible in iOS since iOS 9.0

**Comment by jcesarmobile** [comment]
looks like CORS problems, see the Ionic CORS docs
https://ionicframework.com/docs/troubleshooting/cors
