### ISSUE TITLE
Using UIWebView error

### ISSUE THREAD

**Issue by ladaniavadh** [ionic-team/cordova-plugin-ionic-webview#590]
Hello,
I am using the latest 5.0.0 version of plugin since it showing the reference  of using UIWebView in grep command and that's why my app is getting rejected from IOS.
Any solution how can I solve this error?
![Screenshot 2020-06-27 at 10 30 39 AM](https://user-images.githubusercontent.com/30779077/85971676-6ddeea00-b9eb-11ea-9ca5-69ad84ba99c6.png)

**Comment by jcesarmobile** [comment]
doesn't look like you updated the plugin correctly, that code is not there anymore
https://github.com/ionic-team/cordova-plugin-ionic-webview/blob/master/src/ios/CDVWKWebViewEngine.m#L741-L748
