### ISSUE TITLE
MCVE: Regression in loading ionic1 apps while upgrading from cordova-ios@5.1.1 to cordova-ios@6.1.0

### ISSUE THREAD

**Issue by shankari** [ionic-team/cordova-plugin-ionic-webview#594]
I'm using the ionic webview to display my ionic1 app. This worked fine in cordova-ios@5.1.1, but none of the HTML pages load properly on upgrade to cordova-ios@6.1.0

According to https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/582 this plugin should work with cordova-ios@6.1.0

I created an MCVE to reproduce/highlight the issue:
https://github.com/shankari/ionic-webview-mcve

The MCVE repo has two copies of an ionic1 sample app (https://github.com/ccoenraets/directory-angular-ionic). The only plugins are `cordova-plugin-ionic-webview` and `cordova-plugin-ionic`

```
    "plugins": {
      "cordova-plugin-ionic": {
        "APP_ID": "<redacted>",
        "CHANNEL_NAME": "Production",
        "UPDATE_METHOD": "none",
        "UPDATE_API": "https://api.ionicjs.com",
        "MAX_STORE": "2"
      },
      "cordova-plugin-ionic-webview": {
        "ANDROID_SUPPORT_ANNOTATIONS_VERSION": "27.+"
      }
    }
  },
```

The only difference between them is the cordova-ios version

```
$ diff -r -uw working_copy broken_copy
diff -r -uw working_copy/package.json broken_copy/package.json
--- working_copy/package.json	2020-07-15 20:56:06.000000000 -0700
+++ broken_copy/package.json	2020-07-15 20:54:30.000000000 -0700
@@ -30,7 +30,7 @@
     }
   },
   "dependencies": {
-    "cordova-ios": "^5.1.1",
+    "cordova-ios": "^6.1.0",
     "cordova-plugin-ionic": "5.4.7",
     "cordova-plugin-ionic-webview": "5.0.0"
   }
```

The working copy loads normally; the broken copy doesn't.

## Result

| Working copy | Broken copy |
| -----------  | ----------- |
| ![working_copy](https://raw.githubusercontent.com/shankari/ionic-webview-mcve/master/result_screenshots/working_screenshot.png) | ![broken_copy](https://raw.githubusercontent.com/shankari/ionic-webview-mcve/master/result_screenshots/broken_screenshot.png)

**Comment by jcesarmobile** [comment]
`cordova-plugin-ionic` adds `<preference name="AutoHideSplashScreen" value="false"/>` to the `config.xml`

On your first app it's not a problem since you don't install `cordova-plugin-splashscreen`, but in cordova-ios 6 that plugin  was integrated into the platform, so that preference is preventing the splash from hiding.

Just add `<preference name="AutoHideSplashScreen" value="true" />` in your `config.xml` or call `navigator.splashscreen.hide();` on device ready event, any of them will hide the splash screen.

**Comment by shankari** [comment]
I can confirm that adding `<preference name="AutoHideSplashScreen" value="true" />` to `config.xml` fixes the problem.

**Comment by shankari** [comment]
@jcesarmobile is this only a problem for ionic1 apps, or for all ionic apps? Wondering if this is should be in the README to help others.

**Comment by jcesarmobile** [comment]
It depends on if the app hide the splash on device ready or not, recent ionic templates have a hide call, so shouldn’t be a problem for them.
