### ISSUE TITLE
handle cross origin * with webview

### ISSUE THREAD

**Issue by indraraj26** [ionic-team/cordova-plugin-ionic-webview#595]
It is not good to provide access origin * to access backend APIs from any short of source.

Is there any good way to bypass and restrict to hits from my app only.

I dont want to use native http it is hard to debug in web app and takes more time of dev to finish the project

Thank you

**Comment by ljudbane** [comment]
If you have control over API server then you can implement this by having a list of allowed origins. The `Access-Control-Allow-Origin` header only allows one value. So on your server you need to take the origin of request, check if it is allowed and then set the header to that origin.

For instance if request came from origin `http://localhost` (webview by default), you return header `Access-Control-Allow-Origin: http://localhost`. That's how i will be implementing it on the API server.

**Comment by indraraj26** [comment]
Hi @ljudbane , there is iOS scheme too that also need to whitelist ionic://localhost, I don't know custom scheme is allowed to whitelist, have you tried with iOS?

**Comment by ljudbane** [comment]
@indraraj26 I just started testing on iOS and had to add `ionic://localhost` to the list of allowed origins on API server. So my allowed list now looks like this:
```
'http://localhost',     // webview on Android device
'ionic://localhost',    // webview on iOS device
'http://localhost:8100' // ionic serve
```
