### ISSUE TITLE
Linker command failed xcode 8.3

### ISSUE THREAD

**Issue by Gamerakki** [ionic-team/cordova-plugin-ionic-webview#6]
HI ,

When i install plugin and try to run the app i get errror at linking sayin Apple Mac o linker failed.

Please app ass the development has got stuck due to this

**Comment by legarland** [comment]
I am seeing this same issue. Cannot get cordova to build

172 duplicate symbols for architecture x86_64

**Comment by Gamerakki** [comment]
hi legarland..

have u got any solution for this... the development has got stuck due to this

**Comment by manucorporat** [comment]
1. Make sure `cordova-plugin-ionic-webview` is the only WebKit plugin in you config.xml
You are probably installing several plugins, you will need to remove the old ones.

2. Remove plugins/ and platforms/ folders and recreate the cordova from scratch:
```
ionic cordova build ios
```

**Comment by Gamerakki** [comment]
thnx you closing the issue...
