### ISSUE TITLE
Cookies lost on Android after app restart

### ISSUE THREAD

**Issue by kfrederix** [ionic-team/cordova-plugin-ionic-webview#611]
We are having a strange issue on Android, with Ionic 5: it seems like most of the time (not always) our session cookies "disappear" after the app is restarted.

We have tested and observed this behaviour on several different android devices, so it's not device-specific. Also (as said above, it does work sometimes, which is especially strange...)

To make sure it's not caused by any other plugins, I have started a new blank Ionic 5 app with cordova. Then added only a little bit of code to:
- authenticate by http request to /auth endpoint --> sets sessions cookies from response
- fetch some data by calling an endpoint with `withCredentials: true`

Observed behaviour:

1. install app
2. launch app
3. authenticate (session cookies get attached to domain with Max-Age properly set)
4. fetch data (`withCredentials: true`) --> SUCCESS
5. can make authenticated calls all day long... works every time
6. close app
7. launch app again
8. fetch data (`withCredentials: true`)  --> FAILS, because session cookies were missing

Version info:
- Ionic 5.3.2
- cordova-android: 9.0.0
- cordova-plugin-ionic-webview: 5.0.0  (also tested with 4.2.1 --> seems to make no difference)

I could upload a "clean" project which can be used for testing/debugging if that helps...

**Comment by kfrederix** [comment]
I have figured out the problem: it seems there is a 30 second timer on the sync process between WebView and CookieManager on android. We can solve this by manually flushing the CookieManager on android level.
Solution can be found here: https://github.com/apache/cordova-android/issues/802#issuecomment-526100035.

Closing this issue.

**Comment by signalpoint** [comment]
@kfrederix That is bizarre! Same thing observed over here with just plain old Cordova. Thank you.
