### ISSUE TITLE
ionic iOS app stuck on Splash screen

### ISSUE THREAD

**Issue by prabhashibuddhima** [ionic-team/cordova-plugin-ionic-webview#626]
Hi, 

I have created my ionic v6 mobile app installing  **cordova-plugin-ionic-webview** and when I try to run the app on my device, the app getting stuck on splash screen and no errors are logging. After I remove the plugin and retry it, it works fine. But my app couldn't submit to AppStore due to the UIWebView issue.

**Comment by devsgtech** [comment]
Update splash screen plugin using the link [https://ionicframework.com/docs/native/splash-screen](https://ionicframework.com/docs/native/splash-screen)
This fixed same issue for me.

**Comment by prabhashibuddhima** [comment]
> This fixed same issue for me.

hi,

I tried this and still having same issue

**Comment by prabhashibuddhima** [comment]
I have solved the issue by running the below commands to my project directory:

`npm install `
`sudo gem install cocoapods`
`pod repo update`
`ionic cordova platform add ios@5.1.0`
`cordova plugin update cordova-plugin-ionic-webview@latest` 

then I add the following to my config.xml under ios platform

```
<feature name="CDVWKWebViewEngine">
<param name="ios-package" value="CDVWKWebViewEngine" />
</feature>
<preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />
```
**do not add**   <preference name="WKWebViewOnly" value="true" />

the again in project directory,

`ionic cordova prepare ios`
`cordova build ios`

**Comment by mjindal92** [comment]
@prabhashibuddhima 

I did follow the above steps but still, my screen was stuck on the splash screen.

Can you please share any other solutions?

Thanks

**Comment by gleisonkz** [comment]
I'm facing the same problem here, and even after do all the steps metioned by @prabhashibuddhima. stucked on splashscreen

**Comment by Hassan-Shahriar-1** [comment]
i am facing same issue. tried everything , none of them work. did anyone solve it?

**Comment by TongQuangThanh** [comment]
@Hassan-Shahriar-1 I have same issue, do you have any fix worked for your issue?

**Comment by oschluet** [comment]
If you have this Issue using Firebase Authentication, this will probably fix it:

https://youtu.be/U7RvTTF9dnk?t=2182  
https://stackoverflow.com/questions/71062347/how-to-write-authguard-in-ionic-angular-with-angularfire7-that-works-on-ios 

In your app.module.ts 

change:

`provideAuth(() => getAuth()), `

to:

`   provideAuth(() => {
      if (Capacitor.isNativePlatform()) {
        return initializeAuth(getApp(), {
          persistence: indexedDBLocalPersistence,
        });
      } else {
        return getAuth();
      }
    }),`
