### ISSUE TITLE
Simulator gives "Not Found" error for index.html with this plugin

### ISSUE THREAD

**Issue by stib** [ionic-team/cordova-plugin-ionic-webview#63]
I followed the instructions in [this blog post](https://blog.ionicframework.com/ios-11-checklist/) to update my ionic-v1 app to support iPhone X and iOS 11. After making the updates I found that when I run it in Xcode on a simulator I get the error below.

![image](https://user-images.githubusercontent.com/310258/34737021-b15cb908-f529-11e7-9014-7aaae487b90c.png)

and my Xcode output has this error at the beginning.
`[ERROR] Failed binding IPv4 listening socket: Address already in use (48)`

Same app when run on an actual device runs fine. And copy of my original code (without the updates in the blog post) runs fine on the simulator.

I tried changing the port in the config.xml file from 8080 (referenced below) to other ports but get the same result (removed and added the ios platform before testing)
```
<allow-navigation href="http://localhost:8080/*"/>
<feature name="CDVWKWebViewEngine">
  <param name="ios-package" value="CDVWKWebViewEngine" />
</feature>

<preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />
```
Would appreciate any help in addressing this problem. I originally posted this issue on ionic-v1 repository [here](https://github.com/ionic-team/ionic-v1/issues/356)  but having narrowed the problem down to this webview plugin I am posting it here so it has visibility and hopefully I can get some guidance.

I am also wondering whether I need this plugin for my App as my code seems to run fine in the simulator after all other updates from the above blogpost but without this plugin. I am wondering how can I be sure I don't need this plugin (the blog post seems to imply I should have it) and if so move forward without it.

Thanks,
Sanjay.

**Comment by ghenry22** [comment]
The problem is that something else is using the port that the built in webserver wants.  You can't just change the port in the config file by default as this changes where ionic looks for the file but doesn't change the port that the web server is running on.

Try my fork of the wkwebview plugin

Install from github url:
https://github.com/ghenry22/cordova-plugin-ionic-webview#integratedFixes

in your config.xml include the following value:
    <preference name="WKPort" value="8321" />

update your allow-navigation to the new port (you can use any high numbered port).

**Comment by camolin3** [comment]
Is it planned to iterate over ports until finding an available one?

**Comment by ghenry22** [comment]
@camolin3 this is not possible.  The port is defined before the application is built so there is no way to tell what other ports may be in use on the users device or to change it dynamically.  So just pick something random :)
