### ISSUE TITLE
What exactly is this plugin?

### ISSUE THREAD

**Issue by ParaSpl01t** [ionic-team/cordova-plugin-ionic-webview#630]
Recently stumbled upon this plugin while researching about ionic for Android. Is this a custom webview like crosswalk was?
According to README.md :

> This plugin uses WKWebView on iOS and the latest evergreen webview on Android.

It's unclear to me weather the app using this plugin will use default webview present on Android device or the app will be packaged with a webview (like crosswalk)?

**Comment by timbru31** [comment]
It uses the default WebView engine of Android. (such as Chrome if installed or the Android System WebView)

**Comment by ParaSpl01t** [comment]
> It uses the default WebView engine of Android. (such as Chrome if installed or the Android System WebView)

Thanks for clarifying. I have one more question. 
Doesn't cordova do the same by default? Are there other functionalities of this plugin that I's missing?

**Comment by timbru31** [comment]
Yes, Cordova does the same by default. This plugin "enhances" the WebView for special support of Ionic Appflow - it's a fork of the https://github.com/apache/cordova-plugin-wkwebview-engine. For Android they've developed a local webserver, too - cordova-android serves from the file protocol.

Unless you plan to use Ionic Appflow and to do live deployments/hot code push, you can just use the built in WebView's of cordova-ios and cordova-android.
