### ISSUE TITLE
Cannot go pass splash screen due to CORS error using this plugin.

### ISSUE THREAD

**Issue by csantanu** [ionic-team/cordova-plugin-ionic-webview#631]
Migrating from UIView to WKWebview for our ionic app as it got rejected by Apple, we have added the following in the apache server side - 

Header always set Access-Control-Allow-Origin "ionic://localhost"

In the mobile client, config.xml this is set:

platform name="ios"
<preference name="WKWebViewOnly" value="true" /
<allow-navigation href="*" /
platform

Ionic info:

Ionic:

   Ionic CLI          : 6.12.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.4

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : ios 6.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 25 other plugins)

Utility:

   cordova-res                          : 0.15.2
   native-run (update available: 1.3.0) : 0.2.8

System:

   ios-deploy : 1.11.3
   ios-sim    : 8.0.2
   NodeJS     : v14.15.0 (/usr/local/bin/node)
   npm        : 6.14.9
   OS         : macOS Catalina
   Xcode      : Xcode 12.2 Build version 12B45b

Cordova plugin list-
cordova-plugin-advanced-http 2.1.1 "Advanced HTTP plugin"
cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-camera 3.0.0 "Camera"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-file-transfer 2.0.0-dev "File Transfer"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-firebase-analytics 5.0.0 "FirebaseAnalyticsPlugin"
cordova-plugin-inappbrowser 4.1.0 "InAppBrowser"
cordova-plugin-insomnia 4.3.0 "Insomnia (prevent screen sleep)"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 5.0.0 "cordova-plugin-ionic-webview"
cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"
cordova-plugin-network-information 1.3.4 "Network Information"
cordova-plugin-privacyscreen 0.3.1 "PrivacyScreenPlugin"
cordova-plugin-screen-orientation 3.0.2 "Screen Orientation"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-plugin-wkwebviewxhrfix 1.0.0 "Cordova WKWebView File XHR Fix"
cordova-plugin-x-socialsharing 5.4.0 "SocialSharing"
cordova-plugin-x-toast 2.7.2 "Toast"
cordova-sqlite-storage 4.0.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
cordova-support-google-services 1.3.2 "cordova-support-google-services"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
onesignal-cordova-plugin 2.11.2 "OneSignal Push Notifications"

The app loads and does not go past the splash screen. Safari web-inspector gives the following errors:
Access-Control-Allow-Origin cannot contain more than one origin.
XMLHttpRequest cannot load https://example.com/api/v1 due to access control checks.

What we are doing wrong ? Any help will be highly appreciated.

**Comment by billymahmood** [comment]
Hey guys,

Any luck with this issue? I am having the same issue with this plugin and the AWS-S3 plugin, and also keyboard covering inputs

**Comment by csantanu** [comment]
Mine was resolved after updating cordova-plugin-splashscreen 5.0.3 "Splashscreen" to the latest version 6.0. So I am closing the issue.
