### ISSUE TITLE
iosScheme can't be set as "https://"

### ISSUE THREAD

**Issue by danijel2017** [ionic-team/cordova-plugin-ionic-webview#637]
I am going to use https:// origin for ionic framework.
in config.xml, I set it like this.
<preference name="iosScheme" value="https" />
But app request api with ionic://** origin.
How can I fix this problem?
Please help me!!
It is urgent.

**Comment by jcesarmobile** [comment]
https://github.com/ionic-team/cordova-plugin-ionic-webview#iosscheme
