### ISSUE TITLE
IOS 11, I can not change the "music lock screen / control center", when replaying any audio

### ISSUE THREAD

**Issue by JuanSeBestia** [ionic-team/cordova-plugin-ionic-webview#64]
In iOS 11
Whenever any audio content sounds, it is displayed in the audio controls of the audio src, and the play and pause event, if synchronized with the content, but there is no possible way to change the title, the artist and the image or enable the next and previous buttons.

I have tried all the possible solutions that implement some plugins, I have also tried it natively without any positive results.

![6a1b701d-35e3-4b89-a803-91268a8a3d39](https://user-images.githubusercontent.com/7362688/35053165-610a3814-fb77-11e7-9f84-03ca46f74af5.png)
![dce46352-079d-478e-949a-504b813b7b7f](https://user-images.githubusercontent.com/7362688/35053166-613fed88-fb77-11e7-8ca8-8e4c6c3ac80d.png)

**Comment by ghenry22** [comment]
@jsdussanc https://github.com/homerours/cordova-music-controls-plugin will let you set the metadata for the lock screen and control center.

BUT if you are using the HTML5 audio tag to play audio then the browser will override it with a url everytime.  If you use the native media plugin for your audio then everything works.

I would love it if someone would figure out how to stop the webview over riding this info.

**Comment by codinronan** [comment]
Or just use a plugin explicitly written for this scenario:

cordova-plugin-playlist ;)

**Comment by ghenry22** [comment]
@mlynch this isn't an ionic-webview issue and could be closed

**Comment by jcesarmobile** [comment]
As ghenry22 said, this is not a webview plugin issue, closing
