### ISSUE TITLE
IOS11 how to call schema for another app?

### ISSUE THREAD

**Issue by aibeb** [ionic-team/cordova-plugin-ionic-webview#65]
IOS11 how to call schema for another app?

`window.location.href = facebook:// `
The error:

unsupported URL

**Comment by jdnichollsc** [comment]
Try using **InAppBrowser** plugin instead 👍

**Comment by jcesarmobile** [comment]
You have to add `<allow-intent href="facebook:*" />` and the url should be inside '' or "", i.e `window.location.href = 'facebook://';`
