### ISSUE TITLE
err_connection_refused with cordova-android@10.0.1

### ISSUE THREAD

**Issue by fbrun** [ionic-team/cordova-plugin-ionic-webview#650]
On android, i set globally `<preference name="Hostname" value="xxxx" /> with <allow-navigation href="https://xxxx/*"/> and <preference name="Scheme" value="https" /> (for this last one under <platform name="android">)`

I install new android-cordova@10.0.1 and remove deprecated cordova-plugn-whitelist as mentionned on their github page.

But when i start my app i've an error that ionic could'nt load https://localhost/index.html page. It seems that it doesn't care of setting Hostname or/and allow-navigation settings

**Comment by bigbo26** [comment]
Thanks fbrun for the post.
I get the same error.

**Comment by sacav1** [comment]
hi everyone ! Same issue here :'(

**Comment by lawrence-yong** [comment]
once i install this plugit, i start myApp with file:///android_asset/www/index.html and blank page.

**Comment by MarijaPopovic** [comment]
Same here, installed cordova-android@10 and removed whitelist. Is there any update on this? This is really blocking.

**Comment by MarijaPopovic** [comment]
Try to upgrade to cordova-android@10.1.0 and problem should be removed

**Comment by sacav1** [comment]
great ! it works ! Thanks for your reply

**Comment by marcxploit** [comment]
Add these tags to the config.xml file

<preference name="hostname" value="localhost" />
<preference name="AndroidInsecureFileModeEnabled" value="true" />

**Comment by chitgoks** [comment]
> <allow-navigation href="https://xxxx/*"/>

adding those 2 results in err file not found file:///android_asset/www/index.html
other than that, i tried so many alternatives but i still end up with err_connection_refused and in the debug window it says website not available.

**Comment by zhangv** [comment]
> Add these tags to the config.xml file
> 
> ```
> <preference name="hostname" value="localhost" />
> <preference name="AndroidInsecureFileModeEnabled" value="true" />
> ```

This really saves my day.
Here is my problem: (just in case someone got into the same problem)
I use presentation api to launch another html file which will be displayed in the secondary screen. If I did not add the:
`<preference name="hostname" value="localhost" />`
It will not be able to find the second.html and just give the "err connection refused". Thanks.
