### ISSUE TITLE
Cannot use WKWebView without workarounds

### ISSUE THREAD

**Issue by paulsynth** [ionic-team/cordova-plugin-ionic-webview#66]
Hi! We are not able to:

- Work with WKWebView in iOS < 11 due to the message:  '[<WKWebViewConfiguration 0x6040001ef700> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key _requiresUserActionForMediaPlayback.'. To solve it, we're setting this preference in config.xml file from Cordova:

<preference name="CordovaWebViewEngine" value="CDVUIWebViewEngine" />

So we're not leveraging any feature of this evolved engine. 

- Load assets to draw markers of google maps (. We're specifying routes like: icon: 'assets/icon.png', icon: './assets/icon.png', icon: '/assets/icon.png', icon: file:///assets/icon.png, etc etc, obtaining always the following message:

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSCache setObject:forKey:cost:]: attempt to insert nil value (key: http:/localhost:8080/var/containers/Bundle/Application/XXXX-XXXXXX/AppName.app/www/index.html#/./assets/icon.png)'

This is not happening when using UIWebView. 

Can you help us? Thanks.

**Comment by mlynch** [comment]
Possibly fixed with ab22a992150e0f500224cd75b01a2d7ec25088ce
