### ISSUE TITLE
GCDWebServerDataRequest.h

### ISSUE THREAD

**Issue by mreggiardo** [ionic-team/cordova-plugin-ionic-webview#67]
I have problems trying to compile a ionic 1 project with this plugin.
the workaround to fix it , after check  the the ionic forum for the answer is :
change in the GCDWebServerDataRequest.h the 
@property(nonatomic, readonly) NSData* data;  to @property(nonatomic, readonly) NSMutableData* data;  to match the  GCDWebServerDataRequest.m file.

I dont know is this is an error , the data property is diferent. or is ok, and the xcode 7.1 has an issue.
Whatever.. this seems to be the fix.. hope it help!

**Comment by jcesarmobile** [comment]
Xcode 9 is now required for submitting apps to App Store. I can't reproduce this on Xcode 9, so it was probably a Xcode 7 issue
