### ISSUE TITLE
Unstable app behaviour on iOS

### ISSUE THREAD

**Issue by ycbayrak** [ionic-team/cordova-plugin-ionic-webview#69]
![jan-31-2018 21-57-20](https://user-images.githubusercontent.com/9295668/35641836-54e7fa6a-06d2-11e8-8f92-725c06f5a378.gif)

Is this a kind of bug? Or just related to CSS?

````
ionic/cli: 3.19.0
cordova-ios": "~4.5.4
cordova-plugin-ionic-webview: "^1.1.16"

````

**Comment by diegodotta** [comment]
Hi, if your problem is the color you need to change your body background to the specific color (blue), or put a border on header. But if your problem is the boucing on ion-content, you can remove setting <ion-content has-bouncing="false">

**Comment by matejkramny** [comment]
If the "Welcome" page is a navigation bar, it shouldn't be scrolling.

Try adding the following to your config.xml.

```
    <preference name="webviewbounce" value="false" />
    <preference name="UIWebViewBounce" value="false" />
    <preference name="DisallowOverscroll" value="true" />
```

**Comment by jcesarmobile** [comment]
I can't reproduce with latest Ionic and latest webview plugin, it was probably some setting missing like the `<preference name="DisallowOverscroll" value="true" />` mentioned by matejkramny (the other two mentioned don't exist)
