### ISSUE TITLE
POST requests fails "Preflight response is not successful"

### ISSUE THREAD

**Issue by malwatte** [ionic-team/cordova-plugin-ionic-webview#70]
Ionic: 1.3.5 (angular 1.5.3)
cordova cli: 8.0.0
ionic cli: 3.19.1
cordova-plugin-ionic-webview: v1.1.16

plugin list:
```
call-number 0.0.2 "Cordova Call Number Plugin"
com.plugin.imei 0.0.1 "IMEI"
com.xmartlabs.cordova.market 1.2.0 "Market"
cordova-plugin-android-fingerprint-auth 1.4.0 "FingerprintAuth"
cordova-plugin-device 1.1.1 "Device"
cordova-plugin-device-name 1.0.0 "Device-Name"
cordova-plugin-dialogs 1.3.1 "Notification"
cordova-plugin-email 1.2.6 "EmailComposer"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-globalization 1.0.3 "Globalization"
cordova-plugin-google-analytics 1.7.3 "Google Universal Analytics Plugin"
cordova-plugin-inappbrowser 1.5.0 "InAppBrowser"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-media 5.0.1 "Media"
cordova-plugin-migrate-localstorage 0.0.2 "Migrate WebView Data"
cordova-plugin-network-information 1.3.4 "Network Information"
cordova-plugin-secure-storage 2.6.3 "SecureStorage"
cordova-plugin-splashscreen 5.0.1 "Splashscreen"
cordova-plugin-statusbar 2.4.2-dev "StatusBar"
cordova-plugin-touchid 0.4.0 "Touch ID"
cordova-plugin-vibration 2.1.3 "Vibration"
cordova-plugin-whitelist 1.2.1 "Whitelist"
ionic-plugin-keyboard 1.0.8 "Keyboard"
phonegap-plugin-push 1.8.4 "PushPlugin"

```

CORS filters in the server
```
headers.add("Access-Control-Allow-Origin", "http://localhost:8080");
headers.add("Access-Control-Allow-Methods", "GET, POST, DELETE, PUT, OPTIONS");
headers.add("Access-Control-Allow-Headers", "X-Requested-With, Content-Type, Authorization, Origin, Accept");
```

POST requests fail. Error is "Failed to load resource: Preflight response is not successful",
![preflight error 1](https://user-images.githubusercontent.com/2534778/35667901-53786718-0755-11e8-883b-761a1f801fa4.png)

![preflight error 2](https://user-images.githubusercontent.com/2534778/35667910-5b60c2a4-0755-11e8-8cdd-8a6751fae2fc.png)

But GET requests work fine. I used the CURL command and did a preflight (OPTIONS) request. 
`curl -H "Origin: http://localhost:8080" -H "Access-Control-Request-Method: POST" -H "Access-Control-Request-Headers: Accept" -X OPTIONS --verbose https://xxxxxxxxxxxxxxx.com/api/v1/mobile-device`

Here is the output.
```
< HTTP/1.1 401 Unauthorized
< Date: Thu, 01 Feb 2018 07:22:53 GMT
< Server: 
< Access-Control-Allow-Origin: http://localhost:8080
< Access-Control-Allow-Methods: GET, POST, DELETE, PUT, OPTIONS
< Access-Control-Allow-Headers: X-Requested-With, Content-Type, Authorization, Origin, Accept
< Allow: 
< Content-Type: text/html;charset=ISO-8859-1
< Content-Length: 148
< Cache-Control: max-age=0,private
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Set-Cookie: MDROUTEID=md.t2; path=/;
```

It looks like it is not a CORS Origin/Method/Header issue. But looks like server returning 401 for OPTIONS requests.
Does the server has to return http 200?(https://www.html5rocks.com/static/images/cors_server_flowchart.png)

Anyone experienced this issue? Can anyone help me to get this fixed?

Thanks you.

**Comment by suzo** [comment]
Is this issue fixed ? If so , could you please share the solution ?

**Comment by malwatte** [comment]
@suzo,
Two options,
1. Enable CORS in servers.

**Comment by suzo** [comment]
@malwatte Thanks for the reply, 
I've added all the headers to enable CORS but it's still throwing the same error. 
I think I'll go with the Cordova native http plugin for now.

**Comment by malwatte** [comment]
@suzo,
Make a OPTIONS request (rest client) to your end point and check the response.
It should be something like this,

"access-control-allow-headers : Content-Type, Authorization, Content-Length, X-Requested-With"
"access-control-allow-methods :GET,PUT,POST,DELETE,OPTIONS"
"access-control-allow-origin : http://localhost:8080"
200 OK

**Comment by camilaazuma** [comment]
@malwatte I had the same problem and solved it by downgrading the webview from WKWebview to UIWebview, as described at [ionic docs](https://ionicframework.com/docs/wkwebview/#downgrading-to-uiwebview) 😄

P.S.: No need of third-party plugins or to make changes on server

**Comment by malwatte** [comment]
@camilaazuma 
I think you should not downgrade to UIWebView. Apple recommends to use WKWebView and not to use UIWebView.
https://developer.apple.com/documentation/uikit/uiwebview

And you will not be able to fix the UI for iPhone X because there is a safe-area bug in UIWebView.
https://github.com/ionic-team/ionic-v1/issues/362

**Comment by malwatte** [comment]
Closing since I was able to fix it by implementing CORS in server side.
