### ISSUE TITLE
Input field types has no effect on the virtual keyboard on iOS

### ISSUE THREAD

**Issue by stevesum** [ionic-team/cordova-plugin-ionic-webview#72]
If we use this WKWebview on iOS platform, then for the input field we always get the regular virtual keyboard.

For example we have an input field with type="search". On the UIWebview we get a virtual keyboard with 'Search' button if the user interact with this field. With the WKWebview we get a virtual keyboard with simple 'Enter' button.

Same with the other input types 'number', 'email', etc.

**Comment by matthuston** [comment]
The keyboard is rendered incorrectly to begin with.  We had to go back to a previous version and use cordova 6.5 with an old release to fix our keyboard problems (https://github.com/driftyco/cordova-plugin-wkwebview-engine.git#618380f).

I've included a screenshot of the 6.5 vs 8.0 (latest webview) vs ios 11 mail client to show the difference.

![ios11](https://user-images.githubusercontent.com/3996142/35925458-c41ff34e-0bf3-11e8-85dc-bdd858cafd1a.png)

**Comment by noxiousmobile** [comment]
My prediction bar is not working on iOS anymore.

**Comment by jcesarmobile** [comment]
I can reproduce the input search not showing "search" as button, but that's a WKWebView bug, not something we can fix.
On iOS 13.x Apple added `enterkeyhint` attribute that can be used for search and other values
https://html.spec.whatwg.org/multipage/interaction.html#input-modalities:-the-enterkeyhint-attribute

For the other inputs mentioned, I can't see any problems with them, so might be some other WKWebView bug, but as iOS 11 it's working fine and that's the oldest iOS version supported by the plugin, so closing.
