### ISSUE TITLE
Wrong webview size on load (visible in low power mode)

### ISSUE THREAD

**Issue by 7freaks-otte** [ionic-team/cordova-plugin-ionic-webview#74]
First of all, sorry for just filing a bug without providing the fix as pull request.

Low power mode seems to throttle WKWebView rendering that much that every now and then (seems to depend on how busy my iPhone 6s is) the following visually annoying bug appears:

On startup after hiding the splash screen my app starts in a small dark box (320x460) with white space at the right and at the bottom. After about 1sec it gets resized to fullscreen (375x667). This sometimes even prevents Ionic from correctly sizing headers and scroll content.

This only happens or at least is only visible in low power mode due to iOS' performance throttling.

When digging into `CDVWKWebViewEngine.m` I found that WKWebView gets initialized with `self.frame` which in my case was `{{0, 0}, {320, 460}}` according to NSLog. My workaround:

```
WKWebView* wkWebView = [[WKWebView alloc] initWithFrame:self.frame configuration:configuration];
```

could be changed to

```
CGRect fullframe = [[UIScreen mainScreen] bounds];
WKWebView* wkWebView = [[WKWebView alloc] initWithFrame:fullframe configuration:configuration];
```

as `[[UIScreen mainScreen] bounds]` is in my case `{{0, 0}, {375, 667}}` and would initialize WKWebView at the correct size from the beginning.

Maybe it's just my app that is so busy at startup or my iPhone 6s that is so slow in low power mode but maybe this helps someone else in preventing the same visual glitch and maybe someone would even be so kind to consider committing this change when fixing another bug. ;-)

**Comment by Hirbod** [comment]
I can confirm this bug, specially when using fullscreen videos played inline + the app was started with low power mode. It gets a nasty black box

Ping @mlynch

**Comment by amritk** [comment]
I have the same problem!!! Users are reporting it on various phones from iPhone 6 to iPX

**Comment by amritk** [comment]
hey @7freaks-otte I tried your fix and it seems to have worked, give it a test on https://github.com/amritk/cordova-plugin-ionic-webview I'm going to create a pull request

**Comment by amritk** [comment]
Looks like this could be the fix
https://github.com/apache/cordova-plugin-wkwebview-engine/commit/81eeadeb542fefc05c4cd5e68ba0221e6a965c73

**Comment by 7freaks-otte** [comment]
Hey @amritk Thanks, your integration of my code still works in my situation and fixes the small box and white margin issue. But I still have another problem which seems to come from the same wrong webview size:

On the very first rendered view, Ionic seems to incorrectly calculate the viewport bounds, especially the content inset of the status bar, which results in 20px of the scroll content being hidden underneath the header bar until I force a content relayout.

My ugly work around (since I don't want to use content.resize()) is to trigger an orientation change after a 200, 500 and just to be safe after a 1000ms delay in ngOnInit.

`window.dispatchEvent(new Event('orientationchange'));`

The window resize event does not seem to trigger any layout update. Although the "hack" above works for me, it is still visible to the user and we need to find a better fix.

**Comment by mzealey** [comment]
This fix mentioned in the first entry works for me too... Suggest you redo the pr?
