### ISSUE TITLE
iOS App Crash with new version of Google Maps API 

### ISSUE THREAD

**Issue by filippodicostanzo** [ionic-team/cordova-plugin-ionic-webview#75]
From today with a new release of google maps API
the app crashes when i try to interact with map component.

I use a google maps web api version

New release is 3.32. 
`    http://maps.google.com/maps/api/js?key=' + this.apiKey + '&callback=mapInit`
 
No error with 3.31
`    https://maps.googleapis.com/maps/api/js?v=3.31&key=' + this.apiKey + '&callback=mapInit`

cli packages: (C:\Users\User\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 7.0.1

local packages:

    @ionic/app-scripts : 3.1.8
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.0.2
    Node              : v8.9.1
    npm               : 5.5.1

**Comment by marutifh** [comment]
Were you able to render Map with WKWebView?

**Comment by filippodicostanzo** [comment]
@marutifh no.
I downgraded to the previous version of Gmaps API

**Comment by UniBrowse** [comment]
Hi @filippodicostanzo, Have you managed to get the latest Gmaps JS API update working yet? I am not working in Ionic but experienced the behavior you described (using Framework7). I have tried for ages to get it working but it always crashes on user touch events. The only solution I have found is downgrading but I would ideally like to be able to use the latest API. Do you know if there is a bug-ticket open for this somewhere?

**Comment by AonanLi** [comment]
Hi @filippodicostanzo,
My app has a quite similar problem with the new api, but it doesn't use ng2-pdf-viewer. Could you please tell me how you manage to find out which plugin is causing this issue? Thanks very much.

**Comment by UniBrowse** [comment]
@AonanLi , I am also not using the ng2-pdf-viewer plugin but am still experiencing the problem. I am trying to isolate the conflict but have had no luck as of yet. I am assuming it is related to another plugin that might be tracking multi-touch events (catering for pinch-zoom or something). As I mentioned, I am not using Ionic so am assuming there is a broader JS conflict.

**Comment by filippodicostanzo** [comment]
@AonanLi your issuee also occurs in the browser when you launch the "ionic serve" command?

**Comment by AonanLi** [comment]
@filippodicostanzo I'm not using ionic. The app will crash when I pinch-zoom with markers showing on the map. If there isn't any marker, the app won't crash.

**Comment by AonanLi** [comment]
@UniBrowse Here are the dependencies and cordova plugins I'm using:

```
 "dependencies": {
        "accounting": "0.4.1",
        "axios": "0.15.0",
        "bootstrap": "3.3.7",
        "cordova-app-loader": "markmarijnissen/cordova-app-loader#1.2.0",
        "cordova-promise-fs": "1.1.1",
        "fastclick": "1.0.6",
        "immutable": "3.8.1",
        "lodash": "4.16.4",
        "lz-string": "1.4.4",
        "material-ui": "^0.20.0",
        "mocha": "3.1.2",
        "moment": "2.21.0",
        "number-to-letter": "^1.0.1",
        "onsenui": "2.9.2",
        "phonegap-build-zip": "1.0.2",
        "precss": "^3.1.0",
        "react": "16.2.0",
        "react-addons-css-transition-group": "15.6.2",
        "react-beautiful-dnd": "^7.1.3",
        "react-dimensions": "1.3.1",
        "react-dom": "16.2.0",
        "react-google-maps": "9.4.3",
        "react-image-lightbox": "^4.6.0",
        "react-infinite-scroll-component": "^4.0.2",
        "react-onsenui": "1.10.0",
        "react-redux": "5.0.6",
        "react-touch": "0.4.3",
        "redux": "3.6.0",
        "redux-localstorage": "0.4.1",
        "redux-logger": "2.7.0",
        "redux-thunk": "2.1.0",
        "reselect": "2.5.4",
        "should": "11.1.1",
        "turf-bbox": "3.0.12",
        "turf-buffer": "3.0.12",
        "uuid": "2.0.3",
        "webworkify-webpack": "1.1.7"
    },
    "devDependencies": {
        "aws-sdk": "2.7.0",
        "babel-core": "6.17.0",
        "babel-eslint": "^7.2.3",
        "babel-loader": "6.2.5",
        "babel-plugin-transform-decorators-legacy": "1.3.4",
        "babel-preset-es2015": "6.16.0",
        "babel-preset-react": "6.16.0",
        "babel-preset-stage-2": "^6.24.1",
        "better-npm-run": "~0.0.1",
        "copy-webpack-plugin": "3.0.1",
        "css-loader": "0.25.0",
        "env2": "2.1.1",
        "eslint": "^4.19.1",
        "eslint-config-prettier": "^2.9.0",
        "eslint-config-react-app": "^2.1.0",
        "eslint-plugin-flowtype": "^2.46.3",
        "eslint-plugin-import": "^2.11.0",
        "eslint-plugin-jsx-a11y": "^5.1.1",
        "eslint-plugin-prettier": "^2.6.0",
        "eslint-plugin-react": "^7.7.0",
        "extract-text-webpack-plugin": "^1.0.1",
        "file-loader": "0.9.0",
        "html-webpack-plugin": "^2.30.1",
        "json-loader": "0.5.4",
        "libxmljs": "^0.18.0",
        "mocha": "3.1.2",
        "phonegap-build-api": "0.4.0",
        "progress-bar-webpack-plugin": "^1.10.0",
        "react-hot-loader": "3.1.3",
        "should": "11.1.1",
        "style-loader": "0.13.1",
        "transform-loader": "0.2.3",
        "unirest": "0.5.1",
        "url-loader": "0.5.7",
        "webpack": "1.13.2",
        "webpack-dev-server": "1.16.2",
        "webpack-shell-plugin": "0.4.3",
        "webworkify-webpack": "1.1.3"
    }
```
```
<plugin name="cordova-plugin-whitelist" spec="1.3.0"/>
    <plugin name="cordova-plugin-file" spec="4.3.0"/>
    <plugin name="cordova-plugin-file-transfer" spec="1.6.0"/>
    <plugin name="cordova-plugin-geolocation" spec="2.4.0"/>
    <plugin name="cordova-plugin-app-version" spec="0.1.9"/>
    <plugin name="cordova-plugin-headercolor" spec="1.0.0"/>
    <plugin name="cordova-plugin-splashscreen" spec="5.0.2"/>
    <plugin name="cordova-plugin-network-information" spec="1.3.0"/>
    <plugin name="cordova-plugin-secure-storage" spec="2.6.3"/>
    <plugin name="cordova-plugin-inappbrowser" spec="3.0.0"/>
    <plugin name="cordova-plugin-camera" spec="4.0.2"/>
    <plugin name="cordova-plugin-file" spec="6.0.1"/>
    <plugin name="es.keensoft.fullscreenimage" spec="0.2.10"/>
    <plugin name="uk.co.workingedge.phonegap.plugin.launchnavigator" spec="4.1.5"/>
```

**Comment by UniBrowse** [comment]
Thanks for the info @AonanLi, I am still working on finding the conflict. I will let you know when I find something.

**Comment by UniBrowse** [comment]
@AonanLi, I have managed to find the conflict in my code. I was using a js library called [PDF.js](https://mozilla.github.io/pdf.js/). It was being loaded locally from the client instead of from an external source. For some reason loading the same library from an external server has resolved my issue. I have tried to find some code which could suggest the reason but with no luck. 

Looking through your dependencies, I can't see anything which looks similar but I'm guessing one of those js libraries is using a similar technique. All I could suggest is trial and error - just removing dependencies until you find the conflict (that's what I ended up doing). Sorry I couldn't be of more help.

**Comment by AonanLi** [comment]
@UniBrowse  I think there are some legacy Monaca libraries loaded locally in my project. I will try to remove them when get back to work. Thanks very much for your help. Will let you know when I find out which library is causing this issue.

**Comment by AonanLi** [comment]
@UniBrowse I tried to create a simple test app which doesn't have many dependencies, and it still crashed. The new released googlemaps api 3.35 does fix the problem though.

**Comment by UniBrowse** [comment]
Hey @AonanLi, Strange that there was still a conflict with very few dependencies, I would have thought other people would also have noticed the issue. I am glad 3.35 seems to be working though - I am also going to be updating soon.

**Comment by aqua3090** [comment]
Hi @AonanLi and @UniBrowse , I am facing a similar issue with my cordova ios app when I pinch-zoom. I am using the latest version of Google maps api -  v 3.35. The map does render and I am able to place a marker but the moment I pinch and zoom/drag , i.e these touch events the app crashes. I have noticed that pinch and zoom causes continuous create 1000+ requests to https://maps.googleapis.com/maps/api/js/ViewportInfoService.GetViewportInfo? 1m6&1m2&1dNaN&2dNaN&2m2&1dNaN&2dNaN&2uNaN&4...............&callback= and this may be causing a out of memory issue but I am not sure. Please let me know if there is a solution.

**Comment by AonanLi** [comment]
@aqua3090 I am using cordova as well. I used to have [app crashes before v3.35](https://stackoverflow.com/questions/53014715/cordova-phonegap-app-crash-on-googlemaps-new-api-when-zoom-with-marker-on-the-ma), and v3.35 fixed it for me.

The issue you are facing is similar but not exactly the same. Before v3.35 I had to pin-zoom/double tap to a certain zoom level to see the crash (not all the time). You may want to create a simple test cordova app which only contains googlemaps to see if it still crashes.

**Comment by aqua3090** [comment]
@AonanLi thanks for your reply. I don't face the issue when the map renders but rather when i pin-zoom/double tap.

**Comment by UniBrowse** [comment]
@aqua3090, my issue sounds exactly the same as yours (only caused by pinch-zoom/double tap). The problem had to do with a conflict between the google maps js api and a js PDF library I was using. I imagine it was triggered because the PDF library was also listening on global touch events. My only recommendation would be trying to disable extensions/plugins that might conflict with the touch events - trial by error. Sorry I don't have more info.
