### ISSUE TITLE
Error loading local files since iOS 11.2.5

### ISSUE THREAD

**Issue by doender** [ionic-team/cordova-plugin-ionic-webview#76]
Since  iOS 11.2.5, I have the following issues:

* Images and audio files cached through imgcache.js cannot be shown anymore, although they are downloaded correctly: 
![image](https://user-images.githubusercontent.com/4175777/36244763-d3ba8c12-1227-11e8-948d-331e71f48dc6.png)

* Local json files (with translations) requested through Angular's http client are not loaded properly.

This all worked in earlier versions of iOS 11. 

The last issue can be solved by installing this plugin: https://github.com/TheMattRay/cordova-plugin-wkwebviewxhrfix, but this wasn't needed in earlier versions.

```
$ ionic info

cli packages: (node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 6.3.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2
    ios-sim    : 6.1.2
    Node       : v9.5.0
    npm        : 2.15.12
    OS         : macOS High Sierra
    Xcode      : Xcode 9.2 Build version 9C40b

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

```
> cordova plugin ls
code-push 2.0.5 "CodePushAcquisition"
cordova-custom-config 5.0.2 "cordova-custom-config"
cordova-plugin-audioinput 0.3.0 "Audio Input"
cordova-plugin-camera 4.0.2 "Camera"
cordova-plugin-code-push 1.11.3 "CodePush"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-crop 0.3.1 "CropPlugin"
cordova-plugin-crosswalk-webview 2.4.0 "Crosswalk WebView Engine"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-image-picker 1.1.1 "ImagePicker"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-media 5.0.2 "Media"
cordova-plugin-network-information 1.3.3 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
cordova-sqlite-storage 2.0.4 "Cordova sqlite storage plugin"
cordova.plugins.diagnostic 3.9.2 "Diagnostic"
```

**Comment by cryo243** [comment]
Is there a fix for the  issue images and audio files cached through imgcache.js cannot be shown issue? this  is  becoming mores recurrent on my app

**Comment by Maistho** [comment]
You can remove the `file://` from the beginning of the file path and it should work. I'm unfortunately not sure if imgcache.js could do this automatically, since there is no good way to find out if you are running in wkwebview or uiwebview as far as I know.

**Comment by mlynch** [comment]
Make sure to replace all `file://` protocols with `http://localhost:8080` as this plugin doesn't support loading file urls and this is a practice that we strongly discourage moving forward.

Here's an example of what that file should look like:

`http://localhost:8080/path/to/image.jpg`

Can't speak for `imgcache.js` as we have no control over that library

**Comment by Maistho** [comment]
Is there a way to tell if we are running in WKWebView or in UIWebView? imgcache probably doesn't want to change this for UIWebView users, but it would be nice if we could detect it and automatically perform these changes.

**Comment by Maistho** [comment]
@mlynch Oooh, that seems really handy. :heart:

I'll test it out and make a PR to imgcache.js if it works.

**Comment by muhammad-zohaib-ehsan** [comment]
Thanks for the help
I used normalizeURL. It worked on iOS. but its not working in android.
It keeps the file:// protocol in android.
Any help will be appreciated.
