### ISSUE TITLE
<base href="/"> breaks application

### ISSUE THREAD

**Issue by sinedied** [ionic-team/cordova-plugin-ionic-webview#77]
I am using this plugin for a Ionic/Angular app, but when I add `<base href="/">` to my `index.html` it breaks the app loading with errors like `404: scripts not found http://localhost:8080/cordova.js`.

If I use `<base href="./">` the app starts, but breaks with angular subroutes like `/hero/:heroId`.

If I remove <base href>` meta completely, I have a looping error in the console: `failed to load resource: unsupported url gap://ready`.

So what can I do? Seems that the best fix would be for this plugin to support `<base href="/">` properly.

**Comment by mlynch** [comment]
Should be fixed with ab22a992150e0f500224cd75b01a2d7ec25088ce
