### ISSUE TITLE
WKWebView got rejected in iOS App Review

### ISSUE THREAD

**Issue by Mathijs003** [ionic-team/cordova-plugin-ionic-webview#78]
Hi All, 

I tried uploading a new version of my application on the app store but it got rejected due to 

```

Your app uses or references the following non-public APIs:

“WKContentView”

The use of non-public APIs is not permitted on the App Store because it can lead to a poor user experience should these APIs change. 
```

I think this plugin is quite necessary? Anyone else got the same problem?

**Comment by revie** [comment]
I had a number of successful projects submitted through the Apple App Store with the latest version of the plugin without issue, and even had one accepted last night.  Maybe there is a different plugin you're using that is using WKContentView incorrectly?  Or maybe try using the latest version of this plugin?

**Comment by Mathijs003** [comment]
Yeah, my app got approved 3 weeks ago with the same version as right now. It looks like it depends on the person who reviews the applications? 

It's remarkable how biased these reviewers are..

**Comment by revie** [comment]
Ain't that the truth.  Good luck.

**Comment by mlynch** [comment]
Any other reports of this? We use it for keyboard functionality

**Comment by Hirbod** [comment]
Two apps of mine just landed inside the stores without an issue

**Comment by Andrewpk** [comment]
This issue should not be closed. This plugin exposes and uses a private API which is against Apple's developer agreement. Just because some get through, doesn't mean we should be banking on that.

`_alwaysRunsAtForegroundPriority` needs to be removed asap.
