### ISSUE TITLE
Differences with the apache cordova-plugin-wkwebview-engine

### ISSUE THREAD

**Issue by ccorcos** [ionic-team/cordova-plugin-ionic-webview#88]
Hey there, I'm not seeing a ton of documentation about this plugin but I seems like you guys are moving fast and fixing bugs like the input focus but in iOS 11.3 so I'm eager to use it. But I'm not sure what else it does relative to the [apache](https://github.com/apache/cordova-plugin-wkwebview-engine) plugin. Is this written out anywhere?

**Comment by JoxC** [comment]
+1

**Comment by chuchuva** [comment]
It looks like cordova-plugin-ionic-webview uses local web server but cordova-plugin-wkwebview-engine does not.

**Comment by mlynch** [comment]
Main differences are the use of webserver to avoid the `file://` protocol, and some tweaks to better work with Ionic apps (scrolling, input focus, etc.). We absolutely recommend using this plugin if using Ionic. If not using Ionic, then you'll need to compare the two and see which works better for you. Cheers.
