### ISSUE TITLE
POST request error with Ionic WebView

### ISSUE THREAD

**Issue by mifkys** [ionic-team/cordova-plugin-ionic-webview#9]
I receive next error when trying to POST request with Ionic WebView:
`XMLHttpRequest cannot load https://domain.com/api/login/. Cannot use wildcard in Access-Control-Allow-Origin when credentials flag is true.`

Code:
``` 
let headers = new Headers({ 'Content-Type': 'application/x-www-form-urlencoded' });
let options = new RequestOptions({ headers: headers, withCredentials: true });
let seq = this.api.post('login/?v=2.0&get_photo', accountInfo, options).share();
...
```

api.ts:
```
import { Injectable } from '@angular/core';
import { Http, RequestOptions, URLSearchParams } from '@angular/http';
import 'rxjs/add/operator/map';

@Injectable()
export class Api {

...
  
  post(endpoint: string, body?: any, options?: RequestOptions) {
    let seq =  this.http.post(this.url + '/' + endpoint, body, options);
    ...
    return seq;
  }

}
```

If I remove `withCredentials: true` I receive 401 error code from API on next requests after login.

**Comment by manucorporat** [comment]
Looks like a CORS issue:
https://stackoverflow.com/questions/19743396/cors-cannot-use-wildcard-in-access-control-allow-origin-when-credentials-flag-i

we can't do anything about it, it is WebKit from Apple.

https://ionicframework.com/docs/wkwebview/#i-cant-implement-cors
