### ISSUE TITLE
v1.2.0 can't display image from the camera

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/cordova-plugin-ionic-webview#93]
**I'm submitting a:**
[X ] bug report

**Current behavior:**
After the update from v1.1.19 to v1.2.0 cordova-plugin-ionic-webview I'm not able to display anymore images taken or uploaded from the camera with the cordova-plugin-camera plugin (FILE_URI)

**Workaround:**
Reverting to v1.1.19 solve this issue

**More info:**
I have plugged my iPhone 6s with a cable to my computer in order to debug with the Safari developer console. I do see correctly the < img /> tag correctly rendered in the DOM with a correct URI but Safari tells me that it can't access the file. Instead of that it just rendered a small empty square like when an img URI is broken

I'm up-to-date with all plugins/platforms etc.

**Comment by wilk-polarny** [comment]
Hi, to us, it seems that  this not camera related. Files cannot be accessed (through the webserver at http://127.0.0.1:8080/) any more by us since upgrading to v1.1.19.
Requests only return a HTTP 404 Code.

We were able to work around this issue by downgrading to **v1.1.16**.

**Comment by jamescodesthings** [comment]
Same issue with local images stored in the app's data directory, using the url rewrite described in the readme.

All requests to the image on 1.1.20 were throwing 404s.

Reverting to 1.1.19 fixed the issue.

**Comment by creemerica** [comment]
Having the same issue here. Downgraded to 1.1.16 and now it works.

**Comment by peterpeterparker** [comment]
v1.2.1 is a rollback to v1.1.19 and therefore I don't face this problem anymore with the last version of the plugin. 

I close my issue for that reason.

**Comment by vevisystems** [comment]
Unfortunatelly 1.2.1 does not solve the issue with iOS 11.3. It is working correctly on iOS <= 11.2, though.

**Comment by creemerica** [comment]
1.2.1 seems to fix the issues for me. @vevisystems you may have something else going on.

**Comment by wilk-polarny** [comment]
1.2.1 fixed this issue for us on iOS <= 11.3

**Comment by peterpeterparker** [comment]
v1.2.1 = v.1.1.19

if you face an issue related to a version < v1.1.19 or >= v1.2.1 you should open a new issue
