### ISSUE TITLE
v1.1.19 breaks Microsoft code push updates

### ISSUE THREAD

**Issue by bterres** [ionic-team/cordova-plugin-ionic-webview#97]
My project uses Microsoft Code Push to update local files. I love this plugin, and somewhat to my surprise, it has worked seamlessly with MS Code Push up until recently. Now updated files from codepush are not served but rather the original files get served. Thanks to @Donil's comment on this thread, I tried reverting to 1.16 and everything works beautifully again.
https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/95#issuecomment-381945984

I'd love to keep using Ionic Webview. I realize my combination of plugins is a somewhat niche application, but considering the issues mentioned on the other thread, it seems that the relatively minor changes at v1.1.19 have undermined ability the 'cordova-plugin-ionic-webview' to be a perfect drop-in replacement for UI webview for most situations. I don't understand enough about how either plugin works to recommend a remedy, but it would be great if the team could apply some dev love here to get this plugin back to its previous awesomeness!

Let me know if I can help with any info.

https://github.com/Microsoft/cordova-plugin-code-push

**Comment by jcesarmobile** [comment]
closing as we are in v4 and I think Microsoft made code-push compatible
