### ISSUE TITLE
Querystring in image url referencing file causes crash in iOS 11

### ISSUE THREAD

**Issue by etchen99** [ionic-team/cordova-plugin-ionic-webview#98]
In switching from 1.1.19 to 1.2.0, we had to modify the formatting of image urls that referenced local files in iOS 11.

Previously in our Ionic pages, in 1.1.9 and earlier, we were able to use urls of the form:
```
/var/mobile/Containers/Data/Application/6B967CAF-6A49-4167-B0C0-F121F905F5B0/Library/NoCloud/image0/myphoto_0.jpg?q=8948628204
```

Now in 1.2.0, the above url format will not result in the pages showing the image, so in order for the images to appear, we found we needed to use urls of the form:
```
http://localhost:8080/_ionicwk_//var/mobile/Containers/Data/Application/0EA5E921-8678-4D37-AEAC-427C00422938/Library/NoCloud/image0/myphoto_0.jpg?q=4762199329
```
which we get via ionic-angular `normalizeURL`.

Note however, that we attach a querystring to the file b/c we need to bust the cache.  Without the querystring, 1.2.0 works fine, but with the querystring, we get a SIGABRT in GCDWebServerFileResponse.m, line 82, GWS_NOT_REACHED():
```
- (instancetype)initWithFile:(NSString*)path byteRange:(NSRange)range isAttachment:(BOOL)attachment mimeTypeOverrides:(NSDictionary*)overrides {
  struct stat info;
  if (lstat([path fileSystemRepresentation], &info) || !(info.st_mode & S_IFREG)) {
    GWS_DNOT_REACHED();
    return nil;
  }
```

The presence of the querystring does not result in a crash in 1.1.19, when using the earlier form of the url.

**Comment by NeoLSN** [comment]
I can also confirm this issue.

```
[The latest build : error]
http://localhost:8080/_ionicwk_//var/mobile/Containers/Data/Application/ACC3AFC6-22B7-4E4F-94CC-C55FD5902E92/Library/Caches/logo.png?1524107716302
```
```
[The previous build : success]
http://localhost:8080/var/mobile/Containers/Data/Application/9A6688DE-FDBD-44BE-8819-F305B60A06DB/Library/Caches/logo.png?1524107774964
```

**Comment by troyanskiy** [comment]
Also confirm the issue
![image](https://user-images.githubusercontent.com/1538862/39179572-ef2659dc-47b4-11e8-9860-d4a8d47a192b.png)

**Comment by sfaizanh** [comment]
Can any one confirm in 1.2.1?

**Comment by peterpeterparker** [comment]
I think this was reverted in v1.2.1 with the following commit

https://github.com/ionic-team/cordova-plugin-ionic-webview/commit/8cc9b4c0a39d03a11178df21dddb36db5ab9eb59

**Comment by troyanskiy** [comment]
Yes, the issue can be closed.
